'use client';
import {useState} from 'react';
import {defaultAudioSettings,parseSiteDocument,type SiteDocument} from '@wiffeyyyy/content';
import {changeConfiguration} from '../lib/configuration-actions';
import MediaLibrary from './media-library';
const button='rounded-xl border px-3 py-2 text-sm disabled:opacity-40';
export function AudioWorkspace({siteId,initial,initialRevision,canWrite}:{siteId:string;initial:SiteDocument;initialRevision:number;canWrite:boolean}){
 const [document,setDocument]=useState(initial),[revision,setRevision]=useState(initialRevision),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[picker,setPicker]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');const audio=document.audio??defaultAudioSettings;
 const change=(patch:Partial<SiteDocument>)=>{setDocument(v=>({...v,...patch}));setDirty(true);setMessage('')};
 const save=async(publish:boolean)=>{setBusy(true);setError('');try{const checked=parseSiteDocument(document);let next=revision;if(dirty)next=await changeConfiguration(siteId,checked,next,false);setRevision(next);setDirty(false);if(publish){next=await changeConfiguration(siteId,null,next,true);setRevision(next)}setMessage(publish?'Soundtrack and site settings published.':'Soundtrack draft saved.')}catch(e){setError(e instanceof Error?e.message:'Unable to save soundtrack')}finally{setBusy(false)}};
 return <section className="space-y-5"><header><h1 className="text-2xl font-semibold">Birthday soundtrack</h1><p className="mt-2 text-sm">Choose reusable audio, arrange the playlist and set playback defaults. Publishing here publishes the complete saved site configuration.</p></header>{message&&<p role="status">{message}</p>}{error&&<p role="alert" className="text-red-800">{error}</p>}<fieldset disabled={!canWrite||busy} className="space-y-4 rounded-2xl border bg-white p-5"><legend className="px-2 font-semibold">Playback rules</legend><label className="block text-sm">Default volume ({Math.round(document.defaultVolume*100)}%)<input className="ml-3" type="range" min={0} max={1} step={.05} value={document.defaultVolume} onChange={e=>change({defaultVolume:Number(e.target.value)})}/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={document.defaultMuted} onChange={e=>change({defaultMuted:e.target.checked})}/>Start muted</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={audio.loop} onChange={e=>change({audio:{...audio,loop:e.target.checked}})}/>Loop playlist</label><label className="block text-sm">Background playback<select className="ml-2 rounded border p-2" value={audio.background} onChange={e=>change({audio:{...audio,background:e.target.value as 'continue'|'home-only'}})}><option value="continue">Continue across apps</option><option value="home-only">Home screen only</option></select></label><p className="text-xs">Playback starts only after a visitor presses Play. Other app audio pauses the soundtrack. It stays paused until the visitor presses Play again; hidden tabs pause audio.</p></fieldset>
 <div className="space-y-3"><h2 className="font-semibold">Track order</h2>{!audio.tracks.length&&<p className="text-sm">Add an audio file from the media library.</p>}{audio.tracks.map((track,index)=><fieldset key={track.assetId} disabled={!canWrite||busy} className="space-y-3 rounded-2xl border bg-white p-4"><label className="block text-sm">Title<input className="ml-2 rounded border p-2" maxLength={120} value={track.title} onChange={e=>change({audio:{...audio,tracks:audio.tracks.map(t=>t.assetId===track.assetId?{...t,title:e.target.value}:t)}})}/></label><label className="flex gap-2 text-sm"><input type="radio" name="default-track" checked={audio.defaultTrack===track.assetId} onChange={()=>change({audio:{...audio,defaultTrack:track.assetId}})}/>Default track</label><audio controls preload="metadata" src={'/media/'+track.assetId}/><label className="block text-sm">Transcript / text equivalent<textarea className="mt-1 w-full rounded border p-2" rows={3} maxLength={20000} value={track.transcript} onChange={e=>change({audio:{...audio,tracks:audio.tracks.map(t=>t.assetId===track.assetId?{...t,transcript:e.target.value}:t)}})}/></label>{[-1,1].map(direction=><button key={direction} className={button+' mr-2'} disabled={index+direction<0||index+direction>=audio.tracks.length} onClick={()=>{const tracks=[...audio.tracks];[tracks[index],tracks[index+direction]]=[tracks[index+direction],tracks[index]];change({audio:{...audio,tracks}})}}>Move {direction<0?'up':'down'}</button>)}<button className={button} onClick={()=>{const tracks=audio.tracks.filter(t=>t.assetId!==track.assetId);change({audio:{...audio,tracks,defaultTrack:audio.defaultTrack===track.assetId?tracks[0]?.assetId??null:audio.defaultTrack}})}}>Remove track</button></fieldset>)}</div>
 {canWrite&&<div className="flex gap-3"><button className={button} disabled={busy||audio.tracks.length>=50} onClick={()=>setPicker(true)}>Add from media</button><button className={button} disabled={busy||!dirty} onClick={()=>save(false)}>Save draft</button><button className={button+' bg-[#302a28] text-white'} disabled={busy} onClick={()=>save(true)}>Save and publish site settings</button></div>}{picker&&<div className="rounded-2xl border bg-white p-5"><MediaLibrary siteId={siteId} kind="audio" canWrite={canWrite} onClose={()=>setPicker(false)} onPick={media=>{if(audio.tracks.some(t=>t.assetId===media.id)){setError('This track is already in the playlist.');return}change({audio:{...audio,defaultTrack:audio.defaultTrack??media.id,tracks:[...audio.tracks,{assetId:media.id,title:media.caption||media.filename,transcript:media.transcript??''}]}});setPicker(false)}}/></div>}
 </section>;
}
