'use client';
import {useDeferredValue,useEffect,useMemo,useRef,useState} from 'react';
import EditorMediaPicker from './editor-media-picker';
import {defaultSiteDocument,parseCinematicSettings,resolveCinematicSettings,renderCountdownHtml,renderFinalReelHtml,parseSiteDocument,type CinematicSettings,type SiteDocument} from '@wiffeyyyy/content';
type Group='before'|'after'|'access'|number;
const labels:Record<string,string>={eyebrow:'Small heading',titleLine:'Title',titleEmphasis:'Emphasized title',sub:'Message',lockLabel:'Unlock button',lockNote:'Unlock note',title:'Password dialog title',text:'Password hint'};
export function CinematicEditor({document,mode,disabled,onChange,siteId}:{siteId:string;document:SiteDocument;mode:'countdown'|'reveal';disabled:boolean;onChange:(value:CinematicSettings)=>void}){
 const [group,setGroup]=useState<Group>('before'),[scene,setScene]=useState(0),frame=useRef<HTMLIFrameElement>(null),documentRef=useRef<HTMLElement>(null);
 const [photoPicker,setPhotoPicker]=useState(false);
 const value=resolveCinematicSettings(document);
 let validationError='';try{parseCinematicSettings(value)}catch(error){validationError=error instanceof Error?error.message:'Invalid controls'}
 const change=(update:(next:CinematicSettings)=>void)=>{const next=structuredClone(value);update(next);onChange(next)};
 const preview=useMemo(()=>{let safe=document;try{safe=parseSiteDocument(document)}catch{try{const {cinematic,...base}=document;safe=parseSiteDocument(base)}catch{safe=defaultSiteDocument}}return mode==='countdown'?renderCountdownHtml(safe,{view:group==='after'||group==='access'?'after':'before',access:group==='access',seconds:typeof group==='number'?value.countdown.phases[group].seconds:86400}):renderFinalReelHtml(safe,undefined,scene)},[document,mode,group,scene,value]);
 useEffect(()=>{const receive=(event:MessageEvent)=>{if(event.source!==frame.current?.contentWindow||event.data?.type!=='cinematic:select')return;if(mode==='reveal'&&Number.isInteger(event.data.scene)&&event.data.scene>=0&&event.data.scene<14){setScene(event.data.scene);requestAnimationFrame(()=>{const field=documentRef.current?.querySelector<HTMLTextAreaElement>(`textarea[data-field="${String(event.data.key).replace(/[^a-z0-9]/gi,'')}"]`);field?.focus()})}};window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive)},[mode]);
 const deferredPreview=useDeferredValue(preview);
 const field=(key:string,text:string,update:(text:string)=>void)=><label key={key} className="admin-form-field">{labels[key]||(key.startsWith('copy')?'Scene text':key)}<textarea data-field={key} rows={text.length>100?4:2} maxLength={2000} value={text} onChange={event=>update(event.target.value)}/></label>;
 const timestamp=(seconds:number)=>`${Math.floor(seconds/60)}:${String(Math.round(seconds%60)).padStart(2,'0')}`;
 return <section ref={documentRef} aria-label={mode==='countdown'?'Countdown visual editor':'Final reveal visual editor'} className="grid items-start gap-6 xl:grid-cols-[minmax(280px,.8fr)_minmax(0,1.2fr)]">
  {validationError&&<p role="alert" className="text-sm text-red-700 xl:col-span-2">{validationError}. The preview uses default timing until this is corrected.</p>}
  <fieldset disabled={disabled} className="space-y-4 min-w-0"><legend className="mb-3 font-semibold">{mode==='countdown'?'Countdown screens & last minutes':'Final Reel scenes & reveal'}</legend>
   {mode==='countdown'?<>
    <label className="admin-form-field">Screen to edit<select value={String(group)} onChange={event=>setGroup(/^[0-6]$/.test(event.target.value)?Number(event.target.value):event.target.value as Group)}><option value="before">Main countdown</option>{value.countdown.phases.map((p,i)=><option key={p.key} value={i}>{timestamp(p.seconds)} remaining · stage {i+1}</option>)}<option value="after">Birthday reached</option><option value="access">Password unlock dialog</option></select></label>
    {typeof group==='number'?<><label className="admin-form-field">Show this stage at seconds remaining<input type="number" min={1} max={3600} step={1} value={value.countdown.phases[group].seconds} onChange={event=>change(next=>{next.countdown.phases[group].seconds=Number(event.target.value)})}/><span className="text-xs font-normal">Stages must descend toward zero. Current timestamp: {timestamp(value.countdown.phases[group].seconds)} before the birthday.</span></label>{field('Stage message',value.countdown.phases[group].text,text=>change(next=>{next.countdown.phases[group].text=text}))}{(['eyebrow','titleLine','titleEmphasis','sub'] as const).map(key=>field(key,value.countdown.phases[group][key],text=>change(next=>{next.countdown.phases[group][key]=text})))}<p className="text-xs text-[#766a65]">Leave headings or message empty to inherit the main countdown screen. Its lighting, motion, and countdown display appear in the preview at this exact timestamp.</p></>:Object.entries(value.countdown[group]).map(([key,text])=>field(key,text,text=>change(next=>{(next.countdown[group] as Record<string,string>)[key]=text})))}
    <p className="text-xs text-[#766a65]">Use {'{nickname}'} for her nickname. Birthday date, time and timezone come from Personalization; the password stays DDMMYYYY.</p>
   </>:<>
    <label className="admin-form-field">Scene to edit<select value={scene} onChange={event=>setScene(Number(event.target.value))}>{value.reel.sceneSeconds.map((seconds,i)=><option key={i} value={i}>{i===0?'Opening / play screen':`Scene ${i} · ${seconds.toFixed(1)}s`}{i===13?' · final reveal':''}</option>)}</select></label>
    {scene>1&&<label className="admin-form-field">Scene starts at seconds after Play<input type="number" min={0} max={3600} step={.1} value={value.reel.sceneSeconds[scene]} onChange={event=>change(next=>{next.reel.sceneSeconds[scene]=Number(event.target.value)})}/></label>}
    {value.reel.copy.filter(item=>item.scene===scene).map((item,i)=>field(item.key,item.text,text=>change(next=>{next.reel.copy.find(p=>p.key===item.key)!.text=text})))}
    {scene===5&&<div className="space-y-3"><button type="button" className="admin-button" onClick={()=>setPhotoPicker(open=>!open)}>Choose / upload favorite photo</button><button type="button" className="admin-button" disabled={!value.reel.favoritePhoto} onClick={()=>change(next=>{next.reel.favoritePhoto=''})}>Use In My Heart photo</button>{photoPicker&&<EditorMediaPicker siteId={siteId} kind="image" canWrite={!disabled} onPick={asset=>{change(next=>{next.reel.favoritePhoto='/media/'+asset.id});setPhotoPicker(false)}}/>}</div>}
    {scene===13&&(['actuallySeconds','birthdaySeconds','actionsSeconds'] as const).map((key,i)=><label key={key} className="admin-form-field">{['“…actually” appears at','Birthday reveal appears at','Replay / return controls appear at'][i]} (seconds)<input type="number" min={0} max={3600} step={.1} value={value.reel[key]} onChange={event=>change(next=>{next.reel[key]=Number(event.target.value)})}/></label>)}
    <p className="text-xs text-[#766a65]">Times run from pressing Play and must increase in order. Choose the favorite photo in Scene 5, or use the photo from In My Heart. Use {'{nickname}'} for her name in the closing message.</p>
   </>}
  </fieldset>
  <div className="min-w-0"><div className="mb-3 flex justify-between gap-3"><h3 className="text-sm font-semibold">Private visual preview</h3><span className="text-xs text-[#766a65]">{mode==='countdown'&&typeof group==='number'?`${timestamp(value.countdown.phases[group].seconds)} remaining`:mode==='reveal'?`Scene ${scene}`:'Selected screen'}</span></div><iframe ref={frame} title={mode==='countdown'?'Countdown draft preview':'Final reveal draft preview'} srcDoc={deferredPreview} sandbox="allow-scripts allow-same-origin" className="w-full rounded-2xl border border-black/10 bg-black" style={{height:'min(72vh,700px)',minHeight:440}}/><p className="mt-3 text-xs text-[#766a65]">The preview uses draft settings. Save, then publish to update the live site.</p></div>
 </section>;
}
