"use client";
import {useState} from 'react';
import {type SiteDocument} from '@wiffeyyyy/content';
import {changeConfiguration} from '../lib/configuration-actions';
export function ConfigurationEditor({siteId,initial,initialRevision,canWrite}:{siteId:string;initial:SiteDocument;initialRevision:number;canWrite:boolean}){
 const [document,setDocument]=useState(initial),[revision,setRevision]=useState(initialRevision),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false);
 const change=(key:string,value:string|number|boolean)=>{setDocument(x=>({...x,[key]:value}));setDirty(true)};
 const run=async(publish:boolean)=>{setBusy(true);setMessage('');try{setRevision(await changeConfiguration(siteId,document,revision,publish));if(!publish)setDirty(false);setMessage(publish?'Saved settings published.':'Draft saved; public site unchanged.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}};
 return <><div className="grid gap-6 lg:grid-cols-2"><section className="space-y-3">{Object.entries(document).filter(([key])=>key!=='schemaVersion').map(([key,value])=><label key={key} className="block text-sm">{key.replace(/([A-Z])/g,' $1')}<input aria-label={key} disabled={!canWrite||busy} type={typeof value==='boolean'?'checkbox':typeof value==='number'?'number':['background','surface','text','accent'].includes(key)?'color':key==='birthdate'?'date':'text'} checked={typeof value==='boolean'?value:undefined} value={typeof value==='boolean'?undefined:value} step={key==='defaultVolume'?0.05:1} min={typeof value==='number'?0:undefined} max={key==='defaultVolume'?1:key==='radius'?64:undefined} onChange={e=>change(key,typeof value==='boolean'?e.target.checked:typeof value==='number'?Number(e.target.value):e.target.value)} className="ml-3 rounded border p-2"/></label>)}</section><section aria-label="Local settings preview" style={{background:document.background,color:document.text,borderRadius:document.radius,padding:24,maxWidth:430}}><p>Private local settings preview</p><h2>{document.siteTitle}</h2><p>{document.name}</p><h3>{document.greeting}, {document.nickname}.</h3><p>{document.welcomeMessage}</p><p>{document.birthdate?`Birthday: ${document.birthdate}`:'Birthday not set'} · {document.timezone}</p><button type="button" style={{background:document.accent,color:document.surface,borderRadius:document.radius,padding:12}}>{document.enterLabel}</button><p>Default volume: {Math.round(document.defaultVolume*100)}% · {document.defaultMuted?'Muted':'Sound enabled after tapping play'}</p></section></div><div className="mt-6 flex gap-3"><button disabled={!canWrite||busy} onClick={()=>run(false)} className="rounded border p-3">Save draft</button><button disabled={!canWrite||busy||dirty} onClick={()=>run(true)} className="rounded border p-3">Publish saved settings</button><button disabled={busy} onClick={()=>{setDocument(initial);setDirty(true)}} className="rounded border p-3">Reset to loaded values</button></div><p role="status">{message}</p><p className="text-sm">Save before publishing. Publishing applies site settings only; pages are published separately.</p></>;
}
