"use client";
import {useState} from 'react';
import {type SiteDocument} from '@wiffeyyyy/content';
import {changeConfiguration} from '../lib/configuration-actions';
export function ConfigurationEditor({siteId,initial,initialRevision,canWrite}:{siteId:string;initial:SiteDocument;initialRevision:number;canWrite:boolean}){
 const [document,setDocument]=useState(initial),[revision,setRevision]=useState(initialRevision),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[dirty,setDirty]=useState(false),[failed,setFailed]=useState(false);
 const change=(key:string,value:string|number|boolean)=>{setDocument(x=>({...x,[key]:value}));setDirty(true)};
 const run=async(publish:boolean)=>{if(busy||!canWrite)return;setBusy(true);setMessage('');setFailed(false);try{setRevision(await changeConfiguration(siteId,document,revision,publish));if(!publish)setDirty(false);setMessage(publish?'Saved settings published.':'Draft saved; public site unchanged.')}catch(e){setFailed(true);setMessage((e as Error).message)}finally{setBusy(false)}};
 return <><div className="grid gap-6 xl:grid-cols-2"><section className="grid content-start gap-4 sm:grid-cols-2">{Object.entries(document).filter(([key])=>key!=='schemaVersion').map(([key,value])=><label key={key} className={typeof value==='boolean'?'flex items-center gap-3 text-sm sm:col-span-2':'admin-form-field'}>{key.replace(/([A-Z])/g,' $1').replace(/^./,letter=>letter.toUpperCase())}<input aria-label={key} disabled={!canWrite||busy} type={typeof value==='boolean'?'checkbox':typeof value==='number'?'number':['background','surface','text','accent'].includes(key)?'color':key==='birthdate'?'date':'text'} checked={typeof value==='boolean'?value:undefined} value={typeof value==='boolean'?undefined:value} step={key==='defaultVolume'?0.05:1} min={typeof value==='number'?0:undefined} max={key==='defaultVolume'?1:key==='radius'?64:undefined} onChange={e=>change(key,typeof value==='boolean'?e.target.checked:typeof value==='number'?Number(e.target.value):e.target.value)} className={typeof value==='boolean'?'':'w-full'}/></label>)}</section><section aria-label="Local settings preview" style={{background:document.background,color:document.text,borderRadius:document.radius,padding:24,maxWidth:430}}><p>Private local settings preview</p><h2>{document.siteTitle}</h2><p>{document.name}</p><h3>{document.greeting}, {document.nickname}.</h3><p>{document.welcomeMessage}</p><p>{document.birthdate?`Birthday: ${document.birthdate}`:'Birthday not set'} · {document.timezone}</p><button type="button" style={{background:document.accent,color:document.surface,borderRadius:document.radius,padding:12}}>{document.enterLabel}</button><p>Default volume: {Math.round(document.defaultVolume*100)}% · {document.defaultMuted?'Muted':'Sound enabled after tapping play'}</p></section></div><div className="mt-6 flex flex-wrap gap-3"><button disabled={!canWrite||busy||!dirty} onClick={()=>run(false)} className="admin-button">{busy?'Working…':'Save draft'}</button><button disabled={!canWrite||busy||dirty} onClick={()=>run(true)} className="admin-button admin-button-primary">Publish saved settings</button><button disabled={!canWrite||busy} onClick={()=>{setDocument(initial);setDirty(true)}} className="admin-button">Reset to loaded values</button></div><p role={failed?'alert':'status'} className={'mt-3 text-sm '+(failed?'text-red-700':'text-emerald-700')}>{message}</p><p className="mt-3 text-xs leading-5 text-[#766a65]">Save before publishing. Publishing applies site settings only; pages are published separately.</p></>;
}
