'use client';
import {useMemo,useState,type ReactNode} from 'react';
import {defaultOsSettings,resolveOsSettings,parseSiteDocument,osSettingFields,installPhoneHome,createDefaultPage,type OsSettings,type SiteDocument,type PageDocument} from '@wiffeyyyy/content';
import {DocumentSettingsProvider} from '@wiffeyyyy/ui/page-layout';
import {OsSettingsSurface} from '@wiffeyyyy/ui/os-settings-surface';
import {PhoneHome} from '@wiffeyyyy/ui/phone-home';
import {SiteNavigationProvider,type PublicNavigationItem} from '@wiffeyyyy/ui/navigation';
import dynamic from 'next/dynamic';
import EditorMediaPicker from './editor-media-picker';
import {changeConfiguration} from '../lib/configuration-actions';
import {documentsEqual} from '../lib/control-panel';
const CinematicEditor=dynamic(()=>import('./cinematic-editor').then(module=>module.CinematicEditor));
const workspaces=[['personalization','Personalization'],['interface','OS interface'],['appearance','Appearance'],['chrome','Status bar & dock'],['motion','Motion & notifications'],['countdown','Countdown editor'],['reveal','Final reveal editor']] as const;
type Workspace=typeof workspaces[number][0];
const personalFields=[['name','Her name','text'],['nickname','Nickname','text'],['birthdate','Birthday','date'],['birthtime','Birthday time','time'],['timezone','Timezone','text'],['siteTitle','Site title','text'],['greeting','Greeting','text'],['welcomeMessage','Welcome message','textarea'],['enterLabel','Enter button text','text']] as const;
const themeFields=[['background','Outside background'],['surface','Shared surface'],['text','Shared text'],['accent','Primary accent']] as const;
const normalize=(settings:SiteDocument):SiteDocument=>({...settings,os:resolveOsSettings(settings)});
export function ConfigurationEditor({siteId,initial,initialRevision,canWrite,homeDocument,navigation=null,revealPhoto}:{siteId:string;initial:SiteDocument;initialRevision:number;canWrite:boolean;homeDocument?:PageDocument;revealPhoto?:string;navigation?:PublicNavigationItem[]|null}){
 const loaded=useMemo(()=>normalize(initial),[initial]);
 const [document,setDocument]=useState(loaded),[saved,setSaved]=useState(loaded),[revision,setRevision]=useState(initialRevision),[workspace,setWorkspace]=useState<Workspace>('personalization'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[failed,setFailed]=useState(false);
 const [wallpaperPicker,setWallpaperPicker]=useState(false);
 const cinematicWorkspace=workspace==='countdown'||workspace==='reveal';
 const dirty=!documentsEqual(document,saved),os=resolveOsSettings(document);
 const change=(key:string,value:string|number|boolean)=>{setDocument(old=>({...old,[key]:value}));setMessage('');setFailed(false)};
 const changeOs=(key:keyof OsSettings,value:string|number|boolean)=>{setDocument(old=>({...old,os:{...resolveOsSettings(old),[key]:value}}));setMessage('');setFailed(false)};
 const preview=useMemo(()=>{try{return parseSiteDocument(document)}catch{return saved}},[document,saved]);
 const phone=useMemo(()=>installPhoneHome(homeDocument??createDefaultPage('home')),[homeDocument]);
 const run=async(publish:boolean)=>{if(busy||!canWrite||publish&&dirty)return;setBusy(true);setMessage('');setFailed(false);try{const validated=parseSiteDocument(document);setRevision(await changeConfiguration(siteId,validated,revision,publish));if(!publish)setSaved(validated);setMessage(publish?'Saved global settings published.':'Draft saved. Your public settings stay unchanged.')}catch(error){setFailed(true);setMessage(error instanceof Error?error.message:'Unable to save settings.')}finally{setBusy(false)}};
 const resetGroup=()=>{if(workspace==='personalization')return;const next={...os};for(const [key,field] of Object.entries(osSettingFields))if(field.group===workspace)Object.assign(next,{[key]:defaultOsSettings[key as keyof OsSettings]});setDocument(old=>({...old,os:next}));setMessage('Workspace defaults restored in draft.');setFailed(false)};
 const baseInput=(key:string,label:string,type:string):ReactNode=>{const value=document[key as keyof SiteDocument];return <label key={key} className="admin-form-field">{label}{type==='textarea'?<textarea rows={4} maxLength={2000} value={String(value)} onChange={event=>change(key,event.target.value)}/>:<input type={type} value={String(value)} maxLength={120} onChange={event=>change(key,event.target.value)}/>} {key==='timezone'&&<span className="text-xs font-normal text-[#766a65]">For example Asia/Kolkata. The live clock uses this timezone.</span>}</label>};
 return <div>
  <nav aria-label="Global settings workspaces" className="mb-5 flex flex-wrap gap-2">{workspaces.map(([key,label])=><button key={key} type="button" className={'admin-button '+(workspace===key?'bg-[#f7e7ed] text-[#9b4361]':'')} aria-pressed={workspace===key} onClick={()=>setWorkspace(key)}>{label}</button>)}</nav>
  {cinematicWorkspace?<CinematicEditor revealPhoto={revealPhoto} siteId={siteId} document={document} mode={workspace as 'countdown'|'reveal'} disabled={!canWrite||busy} onChange={cinematic=>{setDocument(old=>({...old,cinematic}));setMessage('');setFailed(false)}}/>:<div className="grid items-start gap-6 2xl:grid-cols-[minmax(0,1fr)_minmax(300px,.85fr)]">
   <section aria-label={workspaces.find(([key])=>key===workspace)?.[1]}>
    <form onSubmit={event=>{event.preventDefault();void run(false)}}><fieldset disabled={!canWrite||busy} className="grid gap-4 sm:grid-cols-2">
     <legend className="mb-4 text-base font-semibold">{workspaces.find(([key])=>key===workspace)?.[1]}</legend>
     {workspace==='personalization'&&<>{personalFields.map(([key,label,type])=>baseInput(key,label,type))}<label className="admin-form-field">Default audio volume<input type="range" min={0} max={1} step={.05} value={document.defaultVolume} onChange={event=>change('defaultVolume',Number(event.target.value))}/><span className="text-xs">{Math.round(document.defaultVolume*100)}%</span></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={document.defaultMuted} onChange={event=>change('defaultMuted',event.target.checked)}/>Mute audio by default</label><p className="text-xs text-[#766a65] sm:col-span-2">Sound starts after the visitor interacts with the page.</p></>}
     {workspace==='appearance'&&<>{themeFields.map(([key,label])=>baseInput(key,label,'color'))}<label className="admin-form-field">Shared corner radius<input type="number" min={0} max={64} value={document.radius} onChange={event=>change('radius',Number(event.target.value))}/></label></>}
     {Object.entries(osSettingFields).filter(([,field])=>field.group===workspace).map(([key,field])=>{const value=os[key as keyof OsSettings];return <label key={key} className={field.type==='boolean'?'flex items-center gap-2 text-sm':'admin-form-field'}>{field.type==='boolean'?<><input type="checkbox" checked={Boolean(value)} onChange={event=>changeOs(key as keyof OsSettings,event.target.checked)}/>{field.label}</>:<>{field.label}{field.type==='select'?<select value={String(value)} onChange={event=>changeOs(key as keyof OsSettings,event.target.value)}>{field.options?.map(option=><option key={option} value={option}>{option==='12'?'12-hour':option==='24'?'24-hour':option.replace(/^./,letter=>letter.toUpperCase())}</option>)}</select>:<input type={field.type==='color'?'color':field.type==='time'?'time':field.type==='number'?'number':'text'} min={field.min} max={field.max} step={field.type==='number'?(['width','height','gridColumns'].includes(key)?1:'any'):undefined} maxLength={field.type==='url'?2048:undefined} value={String(value)} onChange={event=>changeOs(key as keyof OsSettings,field.type==='number'?Number(event.target.value):event.target.value)}/>}</>}</label>})}
     {workspace==='interface'&&<><p className="text-xs leading-5 text-[#766a65] sm:col-span-2">The frame scales uniformly to fit the viewport. Current screen ratio: {os.width} : {os.height}. Preferred scale is limited by the available screen space.</p><button type="button" className="admin-button" onClick={()=>{setDocument(old=>({...old,os:{...resolveOsSettings(old),width:390,height:830,scale:1}}))}}>Use iPhone dimensions</button></>}
     {workspace==='appearance'&&<div className="space-y-3 sm:col-span-2"><h3 className="text-sm font-semibold">Mobile OS wallpaper</h3><div className="flex flex-wrap gap-2"><button type="button" className="admin-button" onClick={()=>setWallpaperPicker(open=>!open)}>{wallpaperPicker?'Close photo picker':'Choose / upload wallpaper'}</button><button type="button" className="admin-button" disabled={!os.wallpaper} onClick={()=>changeOs('wallpaper','')}>Use home page wallpaper</button></div>{wallpaperPicker&&<EditorMediaPicker siteId={siteId} kind="image" canWrite={canWrite} onPick={asset=>{changeOs('wallpaper','/media/'+asset.id);setWallpaperPicker(false)}}/>}<p className="text-xs leading-5 text-[#766a65]">Choose a photo, then adjust its fit, brightness and dimming above. The phone preview shows your changes.</p></div>}
     {workspace==='motion'&&<p className="text-xs leading-5 text-[#766a65] sm:col-span-2">Visitor and device reduced-motion preferences take precedence. Disabling notifications hides the shade and its trigger throughout the site.</p>}
     {workspace!=='personalization'&&<button type="button" className="admin-button justify-self-start" onClick={resetGroup}>Restore workspace defaults</button>}
     <button type="submit" className="sr-only" tabIndex={-1}>Save draft</button>
    </fieldset></form>
   </section>
   <section aria-label="Local settings preview" className="min-w-0"><div className="mb-3 flex items-center justify-between gap-3"><h3 className="text-sm font-semibold">Private phone preview</h3><span className="text-xs text-[#766a65]">Unsaved changes</span></div><div onClickCapture={event=>{if((event.target as HTMLElement).closest('a[href]'))event.preventDefault()}}><DocumentSettingsProvider value={preview}><SiteNavigationProvider value={navigation}><OsSettingsSurface settings={preview} preview><PhoneHome document={phone} contained/></OsSettingsSurface></SiteNavigationProvider></DocumentSettingsProvider></div><div className="mt-3 rounded-xl border border-black/10 p-4 text-sm" style={{background:preview.surface,color:preview.text,borderRadius:preview.radius}}><h3>{preview.greeting}, {preview.nickname}.</h3><p className="mt-2">{preview.welcomeMessage}</p><p className="mt-2 text-xs">{preview.siteTitle} · {preview.birthdate||'Birthday not set'} at {preview.birthtime} · {preview.timezone}</p><p className="mt-2 text-xs">{preview.enterLabel} · Volume {Math.round(preview.defaultVolume*100)}%</p></div></section>
  </div>}
  <div className="mt-6 flex flex-wrap items-center gap-3"><button disabled={!canWrite||busy||!dirty} onClick={()=>run(false)} className="admin-button">{busy?'Working…':'Save draft'}</button><button disabled={!canWrite||busy||dirty} onClick={()=>run(true)} className="admin-button admin-button-primary">Publish saved settings</button><button disabled={!canWrite||busy} onClick={()=>{setDocument(saved);setMessage('Unsaved changes discarded.');setFailed(false)}} className="admin-button">Discard unsaved changes</button><span className="text-xs text-[#766a65]">{dirty?'Unsaved changes':'Draft saved'} · revision {revision}</span></div>
  <p role={failed?'alert':'status'} className={'mt-3 text-sm '+(failed?'text-red-700':'text-emerald-700')}>{message}</p><p className="mt-3 text-xs leading-5 text-[#766a65]">Save before publishing. Publishing applies global settings only; page content is published separately.</p>
 </div>;
}
