'use client';
import {useEffect,useRef,useState} from 'react';
import {
 addArchiveMemory,getInspectorCapabilities,mediaDirectPatch,mediaSelectionPatch,normalizeInspectorValue,resetNodeProperty,resetResponsive,updateNode,
 type CMSField,type CMSNode,type InspectorCapability,type InspectorField,type InspectorGroup,type MediaTargetContract,type PageDocument
} from '@wiffeyyyy/content';
import MediaLibrary from './media-library';
const button='rounded-md border border-[#c9cccf] bg-white px-3 py-2 text-[13px] font-medium text-[#303030] hover:bg-[#f6f6f7] disabled:cursor-not-allowed disabled:opacity-40';
const input='mt-1.5 h-9 w-full rounded-md border border-[#8c9196] bg-white px-3 text-[13px] text-[#303030] outline-none focus:border-[#005bd3] focus:ring-1 focus:ring-[#005bd3]';
function FieldControl({field,value,capability,inherited,disabled,onApply,onReset,onPickMedia}:{field:InspectorField;value:CMSField|undefined;capability:InspectorCapability;inherited?:boolean;disabled:boolean;onApply:(value:CMSField)=>void;onReset:()=>void;onPickMedia?:()=>void}){
 const [message,setMessage]=useState('');
 const apply=(raw:string)=>{if(raw===String(value??''))return;try{onApply(normalizeInspectorValue(field,raw));setMessage('')}catch(error){setMessage(error instanceof Error?error.message:'Invalid value')}};
 return <div className="py-3" title={capability.storagePath}><div className="flex items-start gap-2"><label className="min-w-0 flex-1 text-[13px] font-medium text-[#303030]">{field.label}{field.type==='textarea'?<textarea key={String(value)} className="mt-1.5 min-h-20 w-full resize-y rounded-md border border-[#8c9196] bg-white px-3 py-2 text-[13px] outline-none focus:border-[#005bd3] focus:ring-1 focus:ring-[#005bd3]" defaultValue={String(value??'')} rows={3} disabled={disabled} onBlur={e=>apply(e.target.value)}/>:field.type==='select'?<select className={input} value={String(value??'')} disabled={disabled} onChange={e=>apply(e.target.value)}>{field.options?.map(option=><option key={option} value={option}>{option}</option>)}</select>:<input key={String(value)} className={input} defaultValue={String(value??'')} disabled={disabled} type={field.type==='number'?'number':'text'} min={field.min} max={field.max} step={field.step} placeholder={field.type==='color'?'#ffffff or transparent':undefined} onBlur={e=>apply(e.target.value)}/>} {inherited&&<span className="mt-1 block text-[11px] font-normal text-[#6d7175]">Inherited from Default</span>}</label><button type="button" className="mt-6 text-[11px] font-medium text-[#005bd3] hover:underline disabled:opacity-40" disabled={disabled} onClick={onReset}>{capability.resetPolicy==='component-default'?'Reset':'Clear'}</button></div>{onPickMedia&&<button type="button" className={button+' mt-2 w-full'} disabled={disabled} onClick={onPickMedia}>Choose {capability.media?.label.toLowerCase()}</button>}{capability.dependency&&<p className="mt-1.5 text-[11px] leading-4 text-[#6d7175]">{capability.dependency}</p>}{message&&<p role="alert" className="mt-1.5 text-[11px] text-[#d72c0d]">{message}</p>}</div>;
}
type CommitResult=PageDocument|{document:PageDocument;selectedId:string|null};
export default function EditorInspectorFields({document,node,pageSlug,siteId,canWrite,busy,group,designScope,onDesignScope,onCommit}:{document:PageDocument;node:CMSNode;pageSlug:string;siteId?:string;canWrite:boolean;busy:boolean;group:InspectorGroup;designScope:'base'|'mobile'|'tablet'|'desktop';onDesignScope:(scope:'base'|'mobile'|'tablet'|'desktop')=>void;onCommit:(operation:()=>CommitResult)=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const [mediaTarget,setMediaTarget]=useState<(MediaTargetContract&{nodeId:string})|null>(null);
 useEffect(()=>{if(mediaTarget)dialog.current?.showModal()},[mediaTarget]);
 const all=getInspectorCapabilities(pageSlug,document,node),capabilities=all.filter(cap=>cap.group===group).filter(cap=>group!=='appearance'||designScope==='base'||cap.responsive);const disabled=!canWrite||busy;const patch=(props:Record<string,CMSField>)=>onCommit(()=>updateNode(document,node.id,{props}));
 return <div className="divide-y divide-[#e1e3e5]">
  {group==='content'&&<div className="pb-3"><label className="text-[13px] font-medium text-[#303030]">Layer name<input className={input} value={node.label??node.component} disabled={disabled} maxLength={200} onChange={e=>onCommit(()=>updateNode(document,node.id,{label:e.target.value}))}/></label><p className="mt-1.5 text-[11px] leading-4 text-[#6d7175]">Only used in the editor hierarchy.</p></div>}
  {group==='content'&&node.props.archivePart==='collection'&&<div className="py-3"><button type="button" className={button+' w-full'} disabled={disabled} onClick={()=>onCommit(()=>addArchiveMemory(document,node.id,()=>crypto.randomUUID()))}>+ Add memory</button><p className="mt-1.5 text-[11px] leading-4 text-[#6d7175]">Adds a complete editable memory with generic text and an empty photo placeholder. Existing memories are never changed.</p></div>}
  {group==='behavior'&&<label className="flex items-center justify-between py-3 text-[13px] font-medium text-[#303030]">Show this section or block<input type="checkbox" checked={node.visible} disabled={disabled} onChange={e=>onCommit(()=>updateNode(document,node.id,{visible:e.target.checked}))}/></label>}
  {group==='appearance'&&<div className="py-3"><label className="block text-[13px] font-medium text-[#303030]">Device setting<select className={input} value={designScope} disabled={disabled} onChange={e=>onDesignScope(e.target.value as 'base'|'mobile'|'tablet'|'desktop')}><option value="base">Default</option><option value="mobile">Mobile</option><option value="tablet">Tablet</option><option value="desktop">Desktop</option></select></label>{designScope!=='base'&&<button type="button" className={button+' mt-2 w-full'} disabled={disabled} onClick={()=>onCommit(()=>resetResponsive(document,node.id,designScope))}>Reset {designScope} overrides</button>}</div>}
  {capabilities.map(cap=>{const storageKey=group==='appearance'&&designScope!=='base'?designScope+':'+cap.field.key:cap.field.key;const overridden=node.props[storageKey]!==undefined;const value=group==='appearance'&&designScope!=='base'?(node.props[storageKey]??node.props[cap.field.key]):node.props[cap.field.key];return <FieldControl key={node.id+storageKey+String(value)} field={cap.field} value={value} capability={cap} inherited={group==='appearance'&&designScope!=='base'&&!overridden} disabled={disabled} onApply={next=>{if(cap.media)patch(mediaDirectPatch(cap.media,String(next)));else patch({[storageKey]:next})}} onReset={()=>onCommit(()=>resetNodeProperty(document,node.id,storageKey,designScope==='base'&&cap.hasDefault,cap.defaultValue))} onPickMedia={siteId&&cap.media?()=>setMediaTarget({...cap.media!,nodeId:node.id}):undefined}/>})}
  {mediaTarget&&siteId&&<dialog ref={dialog} onClose={()=>setMediaTarget(null)} aria-modal="true" aria-label={'Choose '+mediaTarget.label} className="fixed inset-4 z-50 m-auto max-h-[90vh] w-[min(1100px,95vw)] overflow-auto rounded-lg border border-[#c9cccf] bg-white p-5 shadow-2xl" onCancel={()=>setMediaTarget(null)}><div className="mb-4 flex items-center justify-between"><div><p className="text-xs text-[#6d7175]">Media</p><h2 className="font-semibold text-[#303030]">{mediaTarget.label}</h2></div><button type="button" className={button} onClick={()=>setMediaTarget(null)}>Close</button></div><MediaLibrary siteId={siteId} canWrite={canWrite} kind={mediaTarget.kind} onClose={()=>setMediaTarget(null)} onPick={media=>{onCommit(()=>updateNode(document,mediaTarget.nodeId,{props:mediaSelectionPatch(mediaTarget,media)}));setMediaTarget(null)}}/></dialog>}
 </div>;
}
