'use client';
import {useEffect,useRef} from 'react';
import type {MediaAsset} from '../lib/media-policy';
import {adjacentMediaId} from '../lib/media-preview';
import {MediaPreview} from './media-preview';
export function MediaViewer({assets,id,onChange,onClose,hasMore,onLoadMore,loading}:{assets:MediaAsset[];id:string;onChange:(id:string)=>void;onClose:()=>void;hasMore:boolean;onLoadMore:()=>void;loading:boolean}){
 const dialog=useRef<HTMLDialogElement>(null),asset=assets.find(item=>item.id===id),previous=adjacentMediaId(assets,id,-1),next=adjacentMediaId(assets,id,1);
 useEffect(()=>{const node=dialog.current,overflow=document.body.style.overflow;node?.showModal();document.body.style.overflow='hidden';return()=>{node?.close();document.body.style.overflow=overflow}},[]);
 useEffect(()=>{if(!asset)onClose()},[asset,onClose]);
 if(!asset)return null;
 return <dialog ref={dialog} aria-label="Full-screen media viewer" onCancel={event=>{event.preventDefault();onClose()}} onKeyDown={event=>{if(event.target instanceof HTMLInputElement||event.target instanceof HTMLTextAreaElement||event.target instanceof HTMLVideoElement||event.target instanceof HTMLAudioElement)return;if(event.key==='ArrowLeft'&&previous){event.preventDefault();onChange(previous)}if(event.key==='ArrowRight'&&next){event.preventDefault();onChange(next)}}} className="fixed inset-0 m-0 h-dvh max-h-none w-screen max-w-none bg-[#151416] p-4 text-white backdrop:bg-black/80 sm:p-6"><div className="flex h-full flex-col gap-4"><header className="flex items-center justify-between gap-4"><div className="min-w-0"><h2 className="truncate font-medium">{asset.filename}</h2><p className="text-xs text-white/60">{assets.findIndex(item=>item.id===id)+1} of {assets.length} loaded files{hasMore?' · more available':''}</p></div><button type="button" autoFocus onClick={onClose} className="rounded-lg border border-white/30 px-4 py-2">Close</button></header><div className="flex min-h-0 flex-1 items-center justify-center overflow-auto"><MediaPreview key={asset.id} asset={asset} fullScreen/></div><footer className="flex flex-wrap items-center justify-center gap-3"><button type="button" disabled={!previous} onClick={()=>previous&&onChange(previous)} className="rounded-lg border border-white/30 px-4 py-2 disabled:opacity-30">Previous</button><button type="button" disabled={!next} onClick={()=>next&&onChange(next)} className="rounded-lg border border-white/30 px-4 py-2 disabled:opacity-30">Next</button>{!next&&hasMore&&<button type="button" disabled={loading} onClick={onLoadMore} className="rounded-lg border border-white/30 px-4 py-2 disabled:opacity-30">{loading?'Loading…':'Load more files'}</button>}</footer></div></dialog>;
}
