'use client';
import {useEffect,useRef,useState} from 'react';
import {uploadMedia,type UploadAttempt} from '../lib/media-upload';
import {mediaKind,validateMedia,type MediaKind} from '../lib/media-policy';
type Job={id:string;file:File;attempt:UploadAttempt;state:'queued'|'uploading'|'failed'|'complete';percent:number;message:string};
export function MediaUploadQueue({siteId,kind,onComplete,disabled=false}:{siteId:string;kind?:MediaKind;disabled?:boolean;onComplete:(id:string)=>void}){
 const [jobs,setJobs]=useState<Job[]>([]),[drag,setDrag]=useState(false),[error,setError]=useState('');const running=useRef(false),alive=useRef(true),callback=useRef(onComplete);callback.current=onComplete;
 useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[]);
 const update=(id:string,patch:Partial<Job>)=>{if(alive.current)setJobs(rows=>rows.map(row=>row.id===id?{...row,...patch}:row))};
 useEffect(()=>{const job=jobs.find(j=>j.state==='queued');if(!job||running.current||disabled)return;running.current=true;update(job.id,{state:'uploading'});
  uploadMedia(siteId,job.file,(message,percent)=>update(job.id,{message,percent:percent??0}),job.attempt).then(id=>{update(job.id,{state:'complete',percent:100,message:'Ready to use'});if(alive.current)callback.current(id)}).catch(e=>update(job.id,{state:'failed',message:e instanceof Error&&!/Server Components render|specific message is omitted/i.test(e.message)?e.message:'Unable to upload. Refresh this page, then retry. The site owner may need to check media storage.'})).finally(()=>{running.current=false;if(alive.current)setJobs(rows=>[...rows])});
 },[jobs,siteId,disabled]);
 const add=(files:File[])=>{if(disabled)return;setError('');if(files.length+jobs.filter(j=>j.state!=='complete').length>20){setError('Queue up to 20 files at a time.');return}const accepted:Job[]=[];for(const file of files){const type=mediaKind(file.type);const check=type?validateMedia(type,file.size,file.type):{ok:false,error:'Unsupported media type'};if(!check.ok||kind&&type!==kind){setError(file.name+': '+(check.error??'Choose '+kind+' files'));continue}accepted.push({id:crypto.randomUUID(),file,attempt:{completed:new Set()},state:'queued',percent:0,message:'Waiting'})}setJobs(rows=>[...rows,...accepted])};
 return <div className={'space-y-3 rounded-2xl border border-dashed p-4 '+(drag?'bg-pink-100':'bg-[#fbf5ef]')} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);add(Array.from(e.dataTransfer.files))}}><label className="block text-sm font-medium">Drop files here or choose files<input type="file" multiple disabled={disabled} accept={kind?kind+'/*':'image/*,video/*,audio/*'} className="mt-3 block max-w-full" onChange={e=>{add(Array.from(e.target.files??[]));e.target.value=''}}/></label><p className="text-xs">Images up to 8 MB · video 50 MB · audio 25 MB. Uploads stay private until publication. Keep this tab open while uploading.</p>{error&&<p role="alert">{error}</p>}<ul className="space-y-3" aria-label="Upload queue">{jobs.map(job=><li key={job.id} className="rounded-xl border bg-white p-3"><p className="break-words text-sm font-medium">{job.file.name}</p><progress aria-label={job.file.name+' upload progress'} value={job.percent} max={100} className="w-full"/><p role="status" className="text-xs">{job.message} · {job.percent}%</p>{job.state==='failed'&&<button className="mt-2 rounded-lg border px-3 py-1 text-sm" disabled={disabled} onClick={()=>update(job.id,{state:'queued',message:'Waiting to retry'})}>Retry</button>}{['failed','complete','queued'].includes(job.state)&&<button className="ml-2 text-xs underline" onClick={()=>setJobs(rows=>rows.filter(row=>row.id!==job.id))}>{job.state==='complete'?'Dismiss':'Remove from queue'}</button>}</li>)}</ul></div>;
}
