'use client';
import { useEffect, useState } from 'react';
import { listMediaAssets, updateMediaMetadata, archiveMedia } from '../lib/media-actions';
import { uploadMedia } from '../lib/media-upload';
import type { MediaAsset, MediaKind } from '../lib/media-policy';
const button='rounded-xl border px-3 py-2 text-sm disabled:opacity-40';
export default function MediaLibrary({siteId,canWrite,kind,onPick,onClose}:{siteId:string;canWrite:boolean;kind?:MediaKind;onPick?:(media:MediaAsset)=>void;onClose?:()=>void}){
 const [assets,setAssets]=useState<MediaAsset[]>([]),[error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState<MediaKind|''>(kind??''),[archived,setArchived]=useState(false),[selected,setSelected]=useState<string|null>(null);
 const reload=async()=>{setError('');try{setAssets(await listMediaAssets(siteId,archived,!!onPick))}catch(e){setError(e instanceof Error?e.message:'Unable to load media')}};
 useEffect(()=>{let active=true;setError('');listMediaAssets(siteId,archived,!!onPick).then(data=>{if(active)setAssets(data)}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Unable to load media')});return()=>{active=false}},[siteId,archived,!!onPick]);
 const perform=async(action:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await action();await reload()}catch(e){setStatus('');setError(e instanceof Error?e.message:'Media action failed')}finally{setBusy(false)}};
 const visible=assets.filter(m=>(!filter||m.kind===filter)&&m.filename.toLowerCase().includes(search.toLowerCase()));const current=assets.find(m=>m.id===selected);
 return <section aria-label="Media library" className="space-y-5"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">Media library</h1><p className="mt-1 text-sm text-[#81736d]">Images, videos and audio for your pages. Latest 200 files.</p></div>{onClose&&<button className={button} onClick={onClose}>Close media picker</button>}</header>
 <div className="flex flex-wrap items-center gap-3"><label className="text-sm">Search<input className="ml-2 rounded-lg border p-2" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Filename"/></label>{!kind&&<label className="text-sm">Type<select className="ml-2 rounded-lg border p-2" value={filter} onChange={e=>setFilter(e.target.value as MediaKind|'')}><option value="">All media</option>{['image','video','audio'].map(x=><option key={x}>{x}</option>)}</select></label>}{!onPick&&<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={archived} onChange={e=>{setArchived(e.target.checked);setSelected(null)}}/>Archived</label>}<button className={button} disabled={busy} onClick={reload}>Refresh</button></div>
 {canWrite&&!archived&&<div className="rounded-2xl border border-dashed bg-[#fbf5ef] p-4"><label className="block text-sm font-medium">Upload media<input type="file" accept={kind==='image'?'image/jpeg,image/png,image/webp,image/gif':kind==='audio'?'audio/mpeg,audio/mp4,audio/wav,audio/ogg':kind==='video'?'video/mp4,video/webm':'image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,audio/mpeg,audio/mp4,audio/wav,audio/ogg'} disabled={busy} className="mt-3 block max-w-full text-sm" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)perform(async()=>{const id=await uploadMedia(siteId,file,setStatus);setSelected(id)})}}/></label><p className="mt-2 text-xs text-[#81736d]">Images up to 8 MB · videos up to 50 MB · audio up to 25 MB. Uploads stay private until used on a published page.</p></div>}
 {status&&<p role="status" className="text-sm">{status}</p>}{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}
 <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_280px]"><div className="grid content-start gap-3 sm:grid-cols-2 xl:grid-cols-3">{!visible.length&&<p className="col-span-full rounded-2xl border p-8 text-center text-sm text-[#81736d]">{search?'No matching files.':archived?'No archived files.':'Your library is empty. Upload your first file.'}</p>}{visible.map(m=><button key={m.id} className={'overflow-hidden rounded-2xl border text-left '+(selected===m.id?'ring-2 ring-[#d86f91]':'')} onClick={()=>setSelected(m.id)} aria-pressed={selected===m.id}>{m.kind==='image'&&m.status==='ready'?<img src={m.previewUrl} alt={m.alt_text??''} loading="lazy" className="h-36 w-full bg-[#f7f5f3] object-cover"/>:<div className="flex h-36 items-center justify-center bg-[#fbf5ef] text-4xl" aria-hidden="true">{m.kind==='video'?'▶':'♫'}</div>}<div className="p-3"><p className="truncate text-sm font-medium">{m.filename}</p><p className="mt-1 text-xs text-[#81736d]">{m.status==='pending'?'Incomplete upload':m.kind} · {(m.byte_size/1048576).toFixed(2)} MB</p></div></button>)}</div>
 {current&&<aside aria-label="Selected media" className="space-y-3 rounded-2xl border p-4"><h2 className="break-words font-semibold">{current.filename}</h2>{current.status!=='ready'?<p className="rounded-xl bg-amber-50 p-3 text-sm">This upload did not finish. Upload the file again, then archive this incomplete entry.</p>:current.kind==='video'?<video controls preload="metadata" src={current.previewUrl} className="w-full rounded-xl"/>:current.kind==='audio'?<audio controls preload="metadata" src={current.previewUrl} className="w-full"/>:<img src={current.previewUrl} alt={current.alt_text??''} className="max-h-64 w-full rounded-xl object-contain"/>}<p className="text-xs">{current.mime_type}<br/>{current.width&&current.height?current.width+' × '+current.height+' px':''}{current.duration_ms?' · '+(current.duration_ms/1000).toFixed(1)+' seconds':''}<br/>{current.metadata.variants?.length?'WebP sizes: '+current.metadata.variants.join(', ')+' px':'Original file'}</p><label className="block text-sm">Alternative text<textarea key={current.id+current.alt_text} defaultValue={current.alt_text??''} maxLength={2000} disabled={!canWrite||busy} className="mt-1 w-full rounded-lg border p-2" rows={3} onBlur={e=>{const text=e.target.value;if(text!==(current.alt_text??''))perform(()=>updateMediaMetadata(current.id,text))}}/></label>{onPick&&<button className={button+' w-full bg-[#d86f91] text-white'} disabled={busy||archived} onClick={()=>onPick(current)}>Use this {current.kind}</button>}{canWrite&&!onPick&&<><button className={button+' w-full'} disabled={busy} onClick={()=>perform(async()=>{await archiveMedia(current.id,!archived);setSelected(null);setStatus(archived?'Media restored':'Media archived')})}>{archived?'Restore to library':'Archive'}</button><p className="text-xs text-[#81736d]">Archiving hides files from the picker. Existing pages and saved versions keep their media.</p></>}</aside>}</div>
 </section>;
}
