"use client";
import {useState} from 'react';
import Link from 'next/link';
import type {NavigationItem} from '@wiffeyyyy/content';
import {saveNavigation} from '../lib/navigation-actions';
export function NavigationEditor({siteId,initial,initialRevision,pages,canWrite}:{siteId:string;initial:NavigationItem[];initialRevision:number;pages:{id:string;title:string;slug:string}[];canWrite:boolean}){
 const [items,setItems]=useState(initial),[revision,setRevision]=useState(initialRevision),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const update=(next:NavigationItem[])=>{setItems(next);setDirty(true)};
 const field=(id:string,key:string,value:unknown)=>update(items.map(n=>n.id===id?{...n,[key]:value}:n));
 const run=async(publish:boolean)=>{setBusy(true);try{setRevision(await saveNavigation(siteId,items,revision,publish));setMessage(publish?'Saved navigation published.':'Draft saved; public navigation unchanged.');if(!publish)setDirty(false)}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}};
 return <><Link href="/navigation/preview" className="underline">Preview saved draft navigation</Link><p>Order below controls the home grid. A menu without a destination groups its children. Publish destination pages first; built-in apps can use sample content.</p><fieldset disabled={!canWrite||busy} className="mt-5 space-y-4">{items.map((n,index)=><article key={n.id} className="rounded-2xl border bg-white p-4"><div className="grid gap-2 md:grid-cols-2"><label>Label<input value={n.label} maxLength={120} onChange={e=>field(n.id,'label',e.target.value)} className="ml-2 rounded border p-2"/></label><label>Icon<input value={n.icon} maxLength={24} onChange={e=>field(n.id,'icon',e.target.value)} className="ml-2 rounded border p-2"/></label><label>Description<input value={n.description} maxLength={300} onChange={e=>field(n.id,'description',e.target.value)} className="ml-2 rounded border p-2"/></label><label>Destination<select value={n.pageId??''} onChange={e=>field(n.id,'pageId',e.target.value||null)}><option value="">Menu group</option>{pages.map(p=><option key={p.id} value={p.id}>{p.title} ({p.slug})</option>)}</select></label><label>Parent menu<select value={n.parentId??''} onChange={e=>field(n.id,'parentId',e.target.value||null)}><option value="">Home grid</option>{items.filter(p=>p.id!==n.id).map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><label><input type="checkbox" checked={n.visible} onChange={e=>field(n.id,'visible',e.target.checked)}/> Visible</label><label><input type="checkbox" checked={n.startHere} onChange={e=>field(n.id,'startHere',e.target.checked)}/> Start here badge</label></div><div className="mt-3 flex gap-3">{[-1,1].map(delta=><button key={delta} disabled={index+delta<0||index+delta>=items.length} onClick={()=>{const next=[...items];[next[index],next[index+delta]]=[next[index+delta],next[index]];update(next)}}>{delta<0?'Move up':'Move down'}</button>)}<button onClick={()=>update(items.filter(p=>p.id!==n.id).map(p=>p.parentId===n.id?{...p,parentId:null}:p))}>Remove</button></div></article>)}<button onClick={()=>update([...items,{id:crypto.randomUUID(),parentId:null,pageId:null,label:'New menu',icon:'♡',description:'',visible:true,startHere:false}])}>Add navigation item</button></fieldset><div className="mt-5 flex gap-3"><button disabled={!canWrite||busy} onClick={()=>run(false)}>Save draft</button><button disabled={!canWrite||busy||dirty} onClick={()=>run(true)}>Publish saved navigation</button></div><p role="status">{message}</p><p>Hidden menus hide their descendants; visibility does not restrict direct page access.</p></>;
}
