'use client';
import {useMemo,useState,type ReactNode} from 'react';
import Link from 'next/link';
import {getExperience,runtimeExperiences,upgradeNavigation,navigationPlacement,moveNavigationItem,navigationDescendants,navigationVisible,removeNavigationItem,type NavigationItem} from '@wiffeyyyy/content';
import {saveNavigation} from '../lib/navigation-actions';
import {AdminIcon} from './admin-icon';

type DestinationPage={id:string;title:string;slug:string;published_version_id?:string|null};
const placements=[['grid','Home screen'],['dock','Dock'],['journey','Journey / back links']] as const;
export function NavigationEditor({siteId,initial,initialRevision,pages,canWrite}:{siteId:string;initial:NavigationItem[];initialRevision:number;pages:DestinationPage[];canWrite:boolean}){
 const upgraded=useMemo(()=>upgradeNavigation(initial),[initial]);
 const [items,setItems]=useState(upgraded),[revision,setRevision]=useState(initialRevision),[dirty,setDirty]=useState(JSON.stringify(upgraded)!==JSON.stringify(initial)),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[selected,setSelected]=useState<string|null>(upgraded[0]?.id??null),[dragged,setDragged]=useState<string|null>(null);
 const current=items.find(item=>item.id===selected);
 const update=(next:NavigationItem[])=>{setItems(next);setDirty(true);setError('');setMessage('')};
 const field=(id:string,key:string,value:unknown)=>update(items.map(item=>item.id===id?{...item,[key]:value}:item));
 const move=(id:string,parentId:string|null,beforeId:string|null=null)=>{try{update(moveNavigationItem(items,id,parentId,beforeId))}catch(e){setError(e instanceof Error?e.message:'Unable to move this item.')}};
 const run=async(publish:boolean)=>{if(busy||!canWrite)return;setBusy(true);setError('');setMessage('');try{setRevision(await saveNavigation(siteId,items,revision,publish));if(!publish)setDirty(false);setMessage(publish?'Saved navigation published.':'Draft saved; live navigation stays unchanged.')}catch(e){setError(e instanceof Error?e.message:'Unable to save navigation.')}finally{setBusy(false)}};
 const resolve=(item:NavigationItem)=>item.runtimeSlug?getExperience(item.runtimeSlug)?.livePath:item.pageId?(()=>{const page=pages.find(page=>page.id===item.pageId);return page?getExperience(page.slug)?.livePath??'/pages/'+page.slug:null})():null;
 const renderTree=(parentId:string|null,depth=0):ReactNode=><ul className={depth?'ml-4 border-l border-black/10 pl-3':'space-y-2'}>{items.filter(item=>item.parentId===parentId).map(item=>{const siblings=items.filter(n=>n.parentId===parentId),position=siblings.findIndex(n=>n.id===item.id);return <li key={item.id} className="mt-2">
  <div className={'flex flex-wrap items-center gap-2 rounded-xl border p-3 '+(selected===item.id?'border-[#d86f91] bg-[#fff5f8]':'border-black/10 bg-white')} onDragOver={event=>{if(canWrite&&!busy)event.preventDefault()}} onDrop={event=>{event.preventDefault();event.stopPropagation();if(!canWrite||busy)return;const id=event.dataTransfer.getData('text/plain')||dragged;if(id)move(id,parentId,item.id);setDragged(null)}}>
   <button type="button" className="admin-button px-2" draggable={canWrite&&!busy} disabled={!canWrite||busy} aria-label={'Drag '+item.label} onDragStart={event=>{setDragged(item.id);event.dataTransfer.setData('text/plain',item.id);event.dataTransfer.effectAllowed='move'}} onDragEnd={()=>setDragged(null)}><AdminIcon name="menu" className="h-4 w-4"/></button>
   <button className="min-w-0 flex-1 text-left" onClick={()=>setSelected(item.id)} aria-pressed={selected===item.id}><span className="block truncate text-sm font-semibold">{item.icon} {item.label}</span><span className="block text-xs text-[#766a65]">{navigationPlacement(items,item)} · {navigationVisible(items,item)?resolve(item)||'Menu group':'Hidden by item or parent'}</span></button>
   {item.startHere&&<span className="admin-status admin-status-draft">Start here</span>}{!item.visible&&<span className="text-xs text-[#766a65]">Hidden</span>}
   <div className="flex gap-1"><button className="admin-button px-2" disabled={!canWrite||busy||position===0} aria-label={'Move '+item.label+' up'} onClick={()=>move(item.id,parentId,siblings[position-1]?.id??null)}>↑</button><button className="admin-button px-2" disabled={!canWrite||busy||position===siblings.length-1} aria-label={'Move '+item.label+' down'} onClick={()=>move(item.id,parentId,siblings[position+2]?.id??null)}>↓</button></div>
  </div>
  {canWrite&&<div className={'rounded-lg px-3 py-1 text-[11px] '+(dragged?'bg-[#f7e7ed] text-[#9b4361]':'text-[#8d807a]')} onDragOver={event=>{if(!busy)event.preventDefault()}} onDrop={event=>{event.preventDefault();event.stopPropagation();if(busy)return;const id=event.dataTransfer.getData('text/plain')||dragged;if(id)move(id,item.id);setDragged(null)}}>Drop here to nest inside {item.label}</div>}
  {renderTree(item.id,depth+1)}
 </li>})}</ul>;
 const parentOptions=current?items.filter(item=>item.id!==current.id&&!navigationDescendants(items,current.id).has(item.id)):[];
 const preview=(parentId:string|null,placement:string):ReactNode=>items.filter(item=>item.parentId===parentId&&navigationVisible(items,item)&&(navigationPlacement(items,item))===placement).map(item=><div key={item.id} className="rounded-xl border border-black/10 bg-white p-3"><span className="text-xl" aria-hidden="true">{item.icon||'♡'}</span><p className="mt-1 text-sm font-semibold">{item.label}</p>{item.startHere&&<p className="text-xs text-[#9b4361]">Start here</p>}<p className="mt-1 text-xs text-[#766a65]">{item.description}</p>{resolve(item)&&<p className="mt-1 break-all text-[10px] text-[#8c807a]">{resolve(item)}</p>}{items.some(child=>child.parentId===item.id&&navigationVisible(items,child))&&<div className="mt-2 space-y-2 border-l pl-2">{preview(item.id,placement)}</div>}</div>);
 return <div>
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Navigation tree</h2><p className="mt-1 text-xs leading-5 text-[#766a65]">Drag to reorder or nest. On touch or keyboard, use move buttons and the parent selector.</p></div><Link className="admin-button" href="/navigation/preview" target="_blank">Preview saved draft</Link></div>
  <div className="mt-5 grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(300px,.85fr)]">
   <section aria-label="Navigation hierarchy"><fieldset disabled={!canWrite||busy}>{renderTree(null)}{!items.length&&<p className="rounded-xl border border-dashed p-6 text-center text-sm text-[#766a65]">No navigation items yet. Add a menu or destination below.</p>}<div className="mt-3 rounded-xl border border-dashed p-3 text-center text-xs text-[#766a65]" onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();if(!canWrite||busy)return;const id=event.dataTransfer.getData('text/plain')||dragged;if(id)move(id,null);setDragged(null)}}>Drop here to move to the top level</div><button className="admin-button mt-3" disabled={items.length>=50} onClick={()=>{const id=crypto.randomUUID();update([...items,{id,parentId:null,pageId:null,label:'New menu',icon:'♡',description:'',visible:true,startHere:false,placement:'grid'}]);setSelected(id)}}>Add navigation item</button></fieldset></section>
   <section aria-label="Navigation item settings" className="rounded-xl border border-black/10 bg-[#faf8f7] p-4">{current?<fieldset className="space-y-4" disabled={!canWrite||busy}><h3 className="font-semibold">{current.label}</h3><label className="admin-form-field">Label<input maxLength={120} value={current.label} onChange={e=>field(current.id,'label',e.target.value)}/></label><label className="admin-form-field">Icon<input maxLength={24} value={current.icon} onChange={e=>field(current.id,'icon',e.target.value)}/></label><label className="admin-form-field">Description<textarea maxLength={300} value={current.description} onChange={e=>field(current.id,'description',e.target.value)}/></label>
    <label className="admin-form-field">Destination<select value={current.runtimeSlug?'runtime:'+current.runtimeSlug:current.pageId??''} onChange={event=>{const value=event.target.value;update(items.map(item=>{if(item.id!==current.id)return item;const {runtimeSlug,...rest}=item;return value.startsWith('runtime:')?{...rest,pageId:null,runtimeSlug:value.slice(8) as NavigationItem['runtimeSlug']}:{...rest,pageId:value||null}}))}}><option value="">Menu group (no destination)</option><optgroup label="Pages">{pages.map(page=><option key={page.id} value={page.id}>{getExperience(page.slug)?.title??page.title}{!page.published_version_id&&!getExperience(page.slug)?.livePath?' · unpublished':''}</option>)}</optgroup><optgroup label="Runtime apps">{runtimeExperiences.map(app=><option key={app.slug} value={'runtime:'+app.slug}>{app.title}</option>)}</optgroup></select></label>
    <label className="admin-form-field">Parent menu<select value={current.parentId??''} onChange={e=>move(current.id,e.target.value||null)}><option value="">Top level</option>{parentOptions.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label>
    <label className="admin-form-field">Placement<select disabled={Boolean(current.parentId)} value={navigationPlacement(items,current)} onChange={e=>field(current.id,'placement',e.target.value)}>{placements.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={current.visible} onChange={e=>field(current.id,'visible',e.target.checked)}/>Visible</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={current.startHere} onChange={e=>field(current.id,'startHere',e.target.checked)}/>Start here badge</label><button className="admin-button text-red-700" onClick={()=>{update(removeNavigationItem(items,current.id));setSelected(null)}}>Remove item</button><p className="text-xs text-[#766a65]">Removing a menu promotes its children. Hidden parents hide their descendants.</p>
   </fieldset>:<p className="text-sm text-[#766a65]">Select a menu or destination to edit its settings.</p>}</section>
  </div>
  <section aria-label="Unsaved navigation preview" className="mt-6 rounded-xl border border-black/10 bg-[#f6f4f2] p-4"><h2 className="font-semibold">Draft preview</h2><p className="mt-1 text-xs text-[#766a65]">Includes your unsaved changes. Destinations are shown without opening the live site.</p><div className="mt-4 grid gap-4 lg:grid-cols-3">{placements.map(([key,label])=><section key={key}><h3 className="mb-2 text-sm font-semibold">{label}</h3><div className="space-y-2">{preview(null,key)}{!items.some(item=>item.parentId===null&&navigationVisible(items,item)&&(navigationPlacement(items,item))===key)&&<p className="text-xs text-[#766a65]">No items in this placement.</p>}</div></section>)}</div></section>
  <div className="mt-5 flex flex-wrap items-center gap-3"><button className="admin-button" disabled={!canWrite||busy||!dirty} onClick={()=>run(false)}>{busy?'Working…':'Save draft'}</button><button className="admin-button admin-button-primary" disabled={!canWrite||busy||dirty} onClick={()=>run(true)}>Publish saved navigation</button><span className="text-xs text-[#766a65]">{dirty?'Unsaved changes':'Draft saved'} · revision {revision}</span></div>
  {message&&<p role="status" className="mt-3 text-sm text-emerald-700">{message}</p>}{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}
 </div>;
}
