'use client';
import {useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';
import {parseRuntimeAppConfig,type RuntimeAppConfig,type RuntimeAppConfigSlug} from '@wiffeyyyy/content';
import {changeRuntimeAppConfiguration} from '../lib/runtime-app-actions';
import {buildPublicHref,type EditorPageItem} from '../lib/editor-pages';
import {EditorPageSelector} from './editor-page-selector';
import MediaLibrary from './media-library';

type Field={key:string;label:string;kind?:'text'|'textarea'|'color'|'boolean'|'image'};
const fields:Record<RuntimeAppConfigSlug,{content:Field[];appearance:Field[]}>= {
 camera:{content:[{key:'appTitle',label:'App title'},{key:'permissionTitle',label:'Permission title'},{key:'permissionBody',label:'Permission message',kind:'textarea'},{key:'enableLabel',label:'Enable camera button'},{key:'retryLabel',label:'Retry button'},{key:'openingLabel',label:'Opening status'},{key:'photoLabel',label:'Photo mode label'},{key:'videoLabel',label:'Video mode label'},{key:'galleryTitle',label:'Gallery title'},{key:'galleryEmptyTitle',label:'Empty gallery title'},{key:'galleryEmptyBody',label:'Empty gallery message',kind:'textarea'},{key:'savedLabel',label:'Saved status'},{key:'pardanasheenLabel',label:'Pardanasheen link'},{key:'gridDefault',label:'Show grid by default',kind:'boolean'}],appearance:[{key:'background',label:'Background',kind:'color'},{key:'surface',label:'Surface',kind:'color'},{key:'text',label:'Text',kind:'color'},{key:'accent',label:'Accent',kind:'color'}]},
 vault:{content:[{key:'eyebrow',label:'Eyebrow'},{key:'title',label:'Title'},{key:'subtitle',label:'Subtitle',kind:'textarea'},{key:'question',label:'Memory question'},{key:'placeholder',label:'Answer placeholder'},{key:'unlockLabel',label:'Unlock button'},{key:'unlockingLabel',label:'Unlocking status'},{key:'errorLabel',label:'Incorrect answer message',kind:'textarea'},{key:'backLabel',label:'Back label'},{key:'footnote',label:'Privacy note'}],appearance:[{key:'background',label:'Background',kind:'color'},{key:'surface',label:'Surface',kind:'color'},{key:'text',label:'Text',kind:'color'},{key:'accent',label:'Accent',kind:'color'}]},
 pieces:{content:[{key:'appTitle',label:'App title'},{key:'subtitle',label:'Subtitle',kind:'textarea'},{key:'instructions',label:'Instructions',kind:'textarea'},{key:'shuffleLabel',label:'Shuffle button'},{key:'resetLabel',label:'Reset button'},{key:'completionTitle',label:'Completion title'},{key:'completionBody',label:'Completion message',kind:'textarea'},{key:'giftLabel',label:'Reward button'},{key:'puzzleImage',label:'Puzzle image',kind:'image'}],appearance:[{key:'background',label:'Background',kind:'color'},{key:'surface',label:'Surface',kind:'color'},{key:'text',label:'Text',kind:'color'},{key:'accent',label:'Accent',kind:'color'}]}
};
const control='mt-1.5 w-full rounded-md border border-[#8c9196] bg-white px-3 text-[13px] text-[#303030] outline-none focus:border-[#005bd3] focus:ring-1 focus:ring-[#005bd3]';
const button='rounded-md border border-[#c9cccf] bg-white px-3 py-2 text-[13px] font-medium text-[#303030] hover:bg-[#f6f6f7] disabled:opacity-40';

function RuntimePreview({slug,document}:{slug:RuntimeAppConfigSlug;document:RuntimeAppConfig}){
 const d=document as unknown as Record<string,unknown>,bg=String(d.background),surface=String(d.surface),text=String(d.text),accent=String(d.accent);
 return <div className="mx-auto flex h-full min-h-[540px] w-full max-w-[330px] flex-col overflow-hidden rounded-[36px] border-[8px] border-[#202020] shadow-2xl" style={{background:bg,color:text}} data-runtime-draft-preview={slug}>
  <div className="mx-auto mt-2 h-5 w-24 rounded-full bg-black"/>
  {slug==='camera'?<div className="flex flex-1 flex-col"><header className="flex items-center justify-between px-5 py-4 text-sm"><span>‹</span><strong>{String(d.appTitle)}</strong><span>▦</span></header><div className="mx-3 grid flex-1 place-items-center rounded-2xl" style={{background:surface}}><div className="max-w-[250px] text-center"><div className="mx-auto mb-4 grid h-14 w-14 place-items-center rounded-2xl bg-[#dedede] text-2xl text-black">▧</div><h2 className="text-lg font-semibold">{String(d.permissionTitle)}</h2><p className="mt-2 text-xs opacity-70">{String(d.permissionBody)}</p><button className="mt-4 rounded-full px-5 py-2 text-xs font-semibold" style={{background:accent,color:bg}}>{String(d.enableLabel)}</button></div></div><div className="p-5 text-center text-[10px] opacity-70">{String(d.savedLabel)}</div></div>:slug==='vault'?<div className="grid flex-1 place-items-center p-5"><div className="w-full rounded-3xl border p-5" style={{background:surface,borderColor:accent+'55'}}><p className="text-[10px] uppercase tracking-[.2em] opacity-65">{String(d.eyebrow)}</p><h2 className="mt-2 text-3xl font-semibold">{String(d.title)}</h2><p className="mt-2 text-sm opacity-70">{String(d.subtitle)}</p><p className="mt-8 text-sm font-medium">{String(d.question)}</p><div className="mt-3 rounded-xl border px-3 py-3 text-xs opacity-60" style={{borderColor:accent+'66'}}>{String(d.placeholder)}</div><button className="mt-3 w-full rounded-xl py-3 text-sm font-semibold" style={{background:accent,color:bg}}>{String(d.unlockLabel)}</button><p className="mt-5 text-center text-[10px] opacity-50">{String(d.footnote)}</p></div></div>:<div className="flex flex-1 flex-col p-5"><h2 className="mt-6 text-2xl font-semibold">{String(d.appTitle)}</h2><p className="mt-2 text-sm opacity-70">{String(d.subtitle)}</p><div className="mt-6 grid aspect-square grid-cols-3 gap-1 overflow-hidden rounded-2xl p-2" style={{background:surface}}>{Array.from({length:9},(_,i)=><div key={i} className="rounded-md border" style={{borderColor:accent+'44',background:i%2?accent+'22':surface}}/>)}</div><p className="mt-5 text-xs opacity-70">{String(d.instructions)}</p><div className="mt-auto flex gap-2"><button className="flex-1 rounded-xl border py-2 text-xs" style={{borderColor:accent}}>{String(d.shuffleLabel)}</button><button className="flex-1 rounded-xl py-2 text-xs font-semibold" style={{background:accent,color:bg}}>{String(d.resetLabel)}</button></div></div>}
 </div>;
}

export default function RuntimeAppEditor({siteId,slug,initialDocument,initialRevision,pages,publicSiteUrl,canWrite,canPublish}:{siteId:string;slug:RuntimeAppConfigSlug;initialDocument:RuntimeAppConfig;initialRevision:number;pages:EditorPageItem[];publicSiteUrl:string;canWrite:boolean;canPublish:boolean}){
 const router=useRouter(),[document,setDocument]=useState(initialDocument),[revision,setRevision]=useState(initialRevision),[saved,setSaved]=useState(initialDocument),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[section,setSection]=useState<'content'|'appearance'>('content'),[picker,setPicker]=useState(false);
 const dirty=useMemo(()=>JSON.stringify(document)!==JSON.stringify(saved),[document,saved]),config=fields[slug],livePath=pages.find(page=>page.slug===slug)?.livePath??('/app/'+slug),liveHref=buildPublicHref(publicSiteUrl,livePath);
 const value=(key:string)=>(document as unknown as Record<string,unknown>)[key];
 const patch=(key:string,next:unknown)=>{if(!canWrite||busy)return;setDocument(current=>parseRuntimeAppConfig(slug,{...(current as unknown as Record<string,unknown>),[key]:next}))};
 const persist=async(publish=false)=>{if(busy)return;setBusy(true);setError('');setNotice('');try{const next=await changeRuntimeAppConfiguration(siteId,slug,document,revision,publish);setRevision(next);if(!publish)setSaved(document);setNotice(publish?'Published runtime app presentation.':'Draft saved.')}catch(e){setError(e instanceof Error?e.message:'Unable to save')}finally{setBusy(false)}};
 return <main className="flex h-screen flex-col overflow-hidden bg-[#f6f6f7] text-[#303030]" data-t10-runtime-editor={slug}>
  <header className="flex h-[50px] shrink-0 items-center border-b border-[#d2d5d8] bg-white"><div className="flex w-[292px] items-center gap-2 border-r border-[#e1e3e5] px-3"><a href="/" className="grid h-8 w-8 place-items-center rounded-md hover:bg-[#f1f1f1]" aria-label="Exit editor">↩</a><span className="text-sm font-semibold">Runtime app</span></div><div className="flex min-w-0 flex-1 justify-center"><EditorPageSelector pages={pages} currentSlug={slug} busy={busy} onSelect={page=>{if(page.editorHref)router.push(page.editorHref)}}/></div><div className="flex w-[312px] justify-end gap-2 border-l border-[#e1e3e5] px-3">{liveHref&&<a href={liveHref} target="_blank" rel="noreferrer" className={button}>View site</a>}<button className={button} disabled={!canWrite||busy||!dirty} onClick={()=>persist(false)}>Save</button><button className="rounded-md bg-[#303030] px-3 py-2 text-[13px] font-medium text-white disabled:opacity-40" disabled={!canPublish||busy||dirty} onClick={()=>persist(true)}>Publish</button></div></header>
  {(error||notice)&&<div role={error?'alert':'status'} className={'border-b px-4 py-2 text-xs '+(error?'border-[#ffd79d] bg-[#fff5ea] text-[#5c3b00]':'border-[#aee9d1] bg-[#f1f8f5] text-[#005e46]')}>{error||notice}</div>}
  <div className="grid min-h-0 flex-1 grid-cols-[292px_minmax(0,1fr)_312px]">
   <aside className="overflow-auto border-r border-[#d2d5d8] bg-white p-3"><h2 className="px-2 py-2 text-sm font-semibold">{pages.find(page=>page.slug===slug)?.title??slug}</h2><button className={'mt-1 w-full rounded-md px-3 py-2 text-left text-sm '+(section==='content'?'bg-[#eaf3ff] text-[#005bd3]':'hover:bg-[#f6f6f7]')} onClick={()=>setSection('content')}>▣ Content & labels</button><button className={'mt-1 w-full rounded-md px-3 py-2 text-left text-sm '+(section==='appearance'?'bg-[#eaf3ff] text-[#005bd3]':'hover:bg-[#f6f6f7]')} onClick={()=>setSection('appearance')}>● Appearance</button><div className="mt-5 rounded-lg bg-[#f6f6f7] p-3 text-[11px] leading-5 text-[#6d7175]"><strong className="text-[#303030]">Runtime state stays separate.</strong><br/>Camera captures, Vault unlock state and Pieces progress are never overwritten by these presentation settings.</div></aside>
   <section className="min-w-0 overflow-auto bg-[#e8e8e8] p-6"><div className="mx-auto flex min-h-full items-center justify-center"><RuntimePreview slug={slug} document={document}/></div></section>
   <aside className="overflow-auto border-l border-[#d2d5d8] bg-white"><div className="sticky top-0 border-b border-[#e1e3e5] bg-white px-4 py-3"><h2 className="text-sm font-semibold">{section==='content'?'Content & labels':'Appearance'}</h2><p className="mt-1 text-[11px] text-[#6d7175]">Draft preview updates immediately.</p></div><fieldset disabled={!canWrite||busy} className="p-4 disabled:opacity-60">{config[section].map(field=><label key={field.key} className="mb-4 block text-[12px] font-medium">{field.label}{field.kind==='boolean'?<button type="button" role="switch" aria-checked={Boolean(value(field.key))} onClick={()=>patch(field.key,!Boolean(value(field.key)))} className={'ml-3 inline-flex h-6 w-11 rounded-full p-0.5 align-middle '+(value(field.key)?'justify-end bg-[#008060]':'justify-start bg-[#8c9196]')}><span className="h-5 w-5 rounded-full bg-white"/></button>:field.kind==='textarea'?<textarea className={control+' min-h-24 py-2'} value={String(value(field.key)??'')} onChange={event=>patch(field.key,event.target.value)}/>:field.kind==='color'?<div className="mt-1.5 flex gap-2"><input type="color" value={String(value(field.key))} onChange={event=>patch(field.key,event.target.value)} className="h-9 w-11 rounded border"/><input className={control+' mt-0'} value={String(value(field.key))} onChange={event=>patch(field.key,event.target.value)}/></div>:field.kind==='image'?<div className="mt-1.5"><div className="truncate rounded-md border bg-[#f6f6f7] px-2 py-2 text-[10px] text-[#6d7175]">{String(value(field.key))||'No puzzle image selected'}</div><button type="button" className={button+' mt-2 w-full'} onClick={()=>setPicker(true)}>Choose from media library</button></div>:<input className={control} value={String(value(field.key)??'')} onChange={event=>patch(field.key,event.target.value)}/>}</label>)}</fieldset></aside>
  </div>
  {picker&&slug==='pieces'&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/35 p-4" role="dialog" aria-modal="true" aria-label="Choose puzzle image"><div className="max-h-[90vh] w-full max-w-5xl overflow-auto rounded-xl bg-white p-5 shadow-2xl"><MediaLibrary siteId={siteId} canWrite={canWrite} kind="image" onClose={()=>setPicker(false)} onPick={media=>{patch('puzzleImage','/media/'+media.id);setPicker(false)}}/></div></div>}
 </main>;
}
