import test from 'node:test';
import assert from 'node:assert/strict';
import {loadContentModule} from './load-content-module.mjs';
const {BackgroundMusic,musicRouteAllowed,parseMusicPreference}=loadContentModule('packages/audio/src/background-music.ts');
const {PlaybackCoordinator}=loadContentModule('packages/audio/src/controller.ts');
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function setup(){const coordinator=new PlaybackCoordinator();const player={paused:true,ended:false,currentTime:42,plays:0,pause(){this.paused=true},async play(){this.paused=false;this.plays++}};const music=new BackgroundMusic(player,coordinator,()=>{});const context={enabled:true,unlocked:false,visible:true,routeAllowed:true};return {coordinator,player,music,context};}
test('music waits for interaction, pauses in media apps, resumes at same position',async()=>{const {music,player,context}=setup();music.update(context);assert.equal(player.plays,0);music.update({...context,unlocked:true});await tick();assert.equal(player.paused,false);music.update({...context,unlocked:true,routeAllowed:false});assert.equal(player.paused,true);music.update({...context,unlocked:true});await tick();assert.equal(player.paused,false);assert.equal(player.currentTime,42);music.dispose();});
test('off preference survives navigation and foreground release',async()=>{const {music,player,context,coordinator}=setup();music.update({...context,unlocked:true});await tick();music.update({...context,unlocked:true,enabled:false});coordinator.claim({pause(){}});coordinator.pauseActive();music.update({...context,unlocked:true,enabled:false,routeAllowed:false});music.update({...context,unlocked:true,enabled:false});await tick();assert.equal(player.paused,true);assert.equal(music.status(),'off');music.dispose();});
test('foreground audio has priority and background resumes when released',async()=>{const {music,player,context,coordinator}=setup();music.update({...context,unlocked:true});await tick();let pauses=0;const foreground={pause(){pauses++}};coordinator.claim(foreground);assert.equal(player.paused,true);music.update({...context,unlocked:true});await tick();assert.equal(coordinator.current(),foreground);assert.equal(pauses,0);coordinator.release(foreground);await tick();assert.equal(player.paused,false);assert.equal(coordinator.current(),player);music.dispose();});
test('hidden tabs pause and completed tracks stay finished',async()=>{const {music,player,context}=setup();music.update({...context,unlocked:true});await tick();music.update({...context,unlocked:true,visible:false});assert.equal(player.paused,true);music.update({...context,unlocked:true});await tick();player.ended=true;player.paused=true;music.paused();assert.equal(music.status(),'finished');music.dispose();});
test('late play promise cannot restart disabled music',async()=>{const {music,player,context}=setup();let resolve;player.play=()=>new Promise(done=>{resolve=()=>{player.paused=false;done()}});music.update({...context,unlocked:true});music.update({...context,unlocked:true,enabled:false});resolve();await tick();assert.equal(player.paused,true);music.dispose();});
test('blocked routes and stored preferences are explicit',()=>{for(const route of ['/app/movie','/app/hotline','/app/adventure','/app/camera','/app/radio','/hotline/receive']){assert.equal(musicRouteAllowed(route,'continue'),false);assert.equal(musicRouteAllowed(route+'/nested','continue'),false)}assert.equal(musicRouteAllowed('/home','continue'),true);assert.equal(musicRouteAllowed('/app/notes','continue'),true);assert.equal(musicRouteAllowed('/app/notes','home-only'),false);assert.equal(parseMusicPreference('{"version":1,"enabled":false}',true),false);assert.equal(parseMusicPreference('broken',true),true);});
