import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import {createHash} from 'node:crypto';
import {loadContentModule} from './load-content-module.mjs';
function load(path,require=()=>({})){const m={exports:{}};new Function('require','module','exports',ts.transpile(readFileSync(path,'utf8'),{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}))(require,m,m.exports);return m.exports}
const org=loadContentModule('apps/admin/lib/media-organization.ts'),policy=loadContentModule('apps/admin/lib/media-policy.ts'),id='00000000-0000-4000-8000-000000000020';
test('Tags normalize, deduplicate and enforce input limits',()=>{assert.deepEqual(org.normalizeMediaTags('Birthday, memories, birthday,  fit  checks '),['birthday','memories','fit checks']);for(const value of ['a'.repeat(41),['bad\ntag'],Array.from({length:21},(_,i)=>'tag'+i)])assert.throws(()=>org.normalizeMediaTags(value));for(const options of [{collection:'invalid'},{favourites:'yes'},{tag:'bad,tag'},{state:'broken'}])assert.throws(()=>org.validateOrganizationFilters(options));assert.equal(org.collectionName(' Photos '),'Photos');assert.throws(()=>org.collectionName(' '))});
test('Organization filters persist safely and pending stays unavailable in ready-only pickers',()=>{const {readMediaPreferences:read}=loadContentModule('apps/admin/lib/media-preferences.ts');const prefs=read(JSON.stringify({collection:id,tag:'birthday',favourites:true,state:'pending',unused:true,duplicates:true}),'image',true);assert.equal(prefs.collection,id);assert.equal(prefs.tag,'birthday');assert.equal(prefs.favourites,true);assert.equal(prefs.state,'all');assert.equal(prefs.unused,true);assert.equal(prefs.duplicates,true);assert.equal(read('{"collection":"invalid"}').collection,'')});
test('All organization conditions match between list and count before pagination',async()=>{let calls=[];const query={select(){return this},eq(...v){calls.push(['eq',...v]);return this},gt(...v){calls.push(['gt',...v]);return this},contains(...v){calls.push(['contains',...v]);return this},order(){return this},range(){return this},is(...v){calls.push(['is',...v]);return this},not(...v){calls.push(['not',...v]);return this},single:async()=>({data:{id}}),then(resolve){resolve({data:[],count:72,error:null})}};const actions=load('apps/admin/lib/media-actions.ts',name=>name==='./media-organization'?org:name==='./auth'?{requireAdmin:async()=>{}}:name==='./supabase'?{adminDb:async()=>({from:()=>query})}:policy);const options={collection:id,tag:'birthday',favourites:true,state:'ready',unused:true,duplicates:true};await actions.listMediaAssets(id,false,false,options);const listed=[...calls];calls=[];assert.equal(await actions.countMediaAssets(id,false,false,options),72);assert.deepEqual(calls,listed);assert.ok(calls.some(v=>v[1]==='duplicate_count'&&v[2]===1));calls=[];await actions.countMediaAssets(id,false,false,{collection:'unfiled'});assert.ok(calls.some(v=>v[1]==='collection_ids'&&v[2]==='{}'))});
test('Fingerprint streams original bytes and rejects spoofed, oversized and stalled content',async()=>{const {fingerprintMediaObject:fingerprint}=load('apps/admin/lib/media-fingerprint.ts',name=>name==='node:crypto'?{createHash}:policy);const previous=global.fetch,bytes=new Uint8Array([137,80,78,71,13,10,26,10,1,2,3]);try{global.fetch=async()=>new Response(new ReadableStream({start(controller){controller.enqueue(bytes.subarray(0,4));controller.enqueue(bytes.subarray(4));controller.close()}}));assert.equal(await fingerprint('https://example.test',{}, {mime:'image/png',size:bytes.length}),createHash('sha256').update(bytes).digest('hex'));global.fetch=async()=>new Response('<html>spoofed content');await assert.rejects(()=>fingerprint('https://example.test',{}, {mime:'image/png',size:21}),/does not match/);global.fetch=async()=>new Response(bytes);await assert.rejects(()=>fingerprint('https://example.test',{}, {mime:'image/png',size:8}),/exceeds|does not match/);global.fetch=()=>new Promise(()=>{});await assert.rejects(()=>fingerprint('https://example.test',{}, {mime:'image/png',size:10},5),/timed out/)}finally{global.fetch=previous}});
test('Organization and fingerprint writes require writer and site validation',async()=>{let siteMissing=true,writes=0,permissions=[];const query={select(){return this},eq(){return this},single:async()=>siteMissing?{data:null}:{data:{site_id:id,id,status:'ready',kind:'image',storage_path:'site/id/original',mime_type:'image/png',byte_size:100}},update(){writes++;return this},is(){return this},then(resolve){resolve({error:null})}};const db={from:()=>query,rpc:async()=>{writes++;return{error:null}},auth:{getSession:async()=>({data:{session:{access_token:'test'}}})}};const actions=load('apps/admin/lib/media-actions.ts',name=>name==='./media-organization'?org:name==='./auth'?{requireAdmin:async permission=>permissions.push(permission)}:name==='./supabase'?{adminDb:async()=>db}:name==='./media-fingerprint'?{fingerprintMediaObject:async()=> 'a'.repeat(64)}:policy);await assert.rejects(()=>actions.saveMediaOrganization(id,{tags:['birthday'],favourite:true,collections:[]}),/not found/);assert.equal(writes,0);siteMissing=false;await actions.saveMediaOrganization(id,{tags:['Birthday'],favourite:true,collections:[]});await actions.fingerprintMedia(id);assert.equal(writes,2);assert.ok(permissions.every(permission=>permission==='media:write'));await assert.rejects(()=>actions.addMediaToCollection(id,'invalid',[id]),/Select a collection/)});
