import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const id='00000000-0000-4000-8000-000000000020',other='00000000-0000-4000-8000-000000000021';
function load(path,require=()=>({})){const m={exports:{}};new Function('require','module','exports',ts.transpile(readFileSync(path,'utf8'),{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}))(name=>name==='./media-organization'?load('apps/admin/lib/media-organization.ts'):require(name),m,m.exports);return m.exports}
const actions=db=>load('apps/admin/lib/media-actions.ts',name=>name==='./supabase'?{adminDb:async()=>db}:name==='./auth'?{requireAdmin:async permission=>assert.equal(permission==='media:write'||permission===undefined,true)}:{});
test('Preferences survive malformed storage and respect a restricted picker kind',()=>{const {readMediaPreferences:read}=load('apps/admin/lib/media-preferences.ts');assert.equal(read('{bad').view,'list');const result=read(JSON.stringify({filter:'video',search:'a'.repeat(250),sort:'largest',view:'grid',archived:true}),'image');assert.equal(result.filter,'image');assert.equal(result.search.length,200);assert.equal(result.sort,'largest');assert.equal(result.view,'grid');assert.equal(read('{"sort":"invalid","view":"invalid"}').sort,'newest')});
test('Rename preserves object references and rejects paths and empty filenames',async()=>{let patch;const q={select(){return this},eq(){return this},single:async()=>({data:{site_id:id,id}}),update(value){patch=value;return this},then(resolve){resolve({error:null})}};const a=actions({from:()=>q});for(const name of ['', '  ','../file.png','folder\\file.png','bad\n.png'])await assert.rejects(()=>a.renameMedia(id,name),/Invalid filename/);await a.renameMedia(id,' Photo.png ');assert.deepEqual(patch,{filename:'Photo.png'})});
test('Bulk archive validates site membership before mutation and retains partial failures',async()=>{let available=[id],calls=[];const q={select(){return this},eq(){return this},in(){return this},single:async()=>({data:{id}}),then(resolve){resolve({data:available.map(id=>({id})),error:null})}};const a=actions({from:()=>q,rpc:async(name,input)=>{calls.push(input.asset_id);return{error:input.asset_id===other?{}:null}}});await assert.rejects(()=>a.bulkArchiveMedia(id,[id,other],true),/unavailable/);assert.equal(calls.length,0);await assert.rejects(()=>a.bulkArchiveMedia(id,[],true));available=[id,other];assert.deepEqual(await a.bulkArchiveMedia(id,[id,id,other],false),{succeeded:[id],failed:[other]});assert.deepEqual(calls,[id,other])});
test('Matching count uses the same readiness, archive, kind and escaped search filters as results',async()=>{let calls=[];const q={select(...v){calls.push(['select',...v]);return this},eq(...v){calls.push(['eq',...v]);return this},single:async()=>({data:{id}}),order(){return this},range(){return this},or(...v){calls.push(['or',...v]);return this},not(...v){calls.push(['not',...v]);return this},is(...v){calls.push(['is',...v]);return this},then(resolve){resolve({data:[],count:123,error:null})}};const a=actions({from:()=>q}),options={kind:'video',search:'50%_'};await a.listMediaAssets(id,true,true,options);const filters=calls.filter(([name])=>['eq','or','not','is'].includes(name));calls=[];assert.equal(await a.countMediaAssets(id,true,true,options),123);assert.deepEqual(calls.filter(([name])=>['eq','or','not','is'].includes(name)),filters);assert.ok(calls.some(([name,,value])=>name==='select'&&value?.head&&value.count==='exact'))});
test('Download signs the original with its filename and stays behind the admin guard',async()=>{let signed,guard=0;const q={select(){return this},eq(){return this},maybeSingle:async()=>({data:{filename:'Photo.png',storage_path:'site/file/original',kind:'image',metadata:{variants:[480]}}})};const {GET}=load('apps/admin/app/media/[id]/route.ts',name=>name.endsWith('/auth')?{requireAdmin:async()=>{guard++}}:name.endsWith('/supabase')?{adminDb:async()=>({from:()=>q,storage:{from:()=>({createSignedUrl:async(...args)=>{signed=args;return{data:{signedUrl:'https://example.test/private'}}}})}})}:{mediaBucket:()=> 'images'});const response=await GET(new Request('https://example.test/media/'+id+'?download=1&variant=480'),{params:Promise.resolve({id})});assert.equal(guard,1);assert.deepEqual(signed,['site/file/original',60,{download:'Photo.png'}]);assert.equal(response.headers.get('Cache-Control'),'private, no-store');assert.equal(response.status,307)});
