import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
function load(path,require=()=>({})){const m={exports:{}};new Function('require','module','exports',ts.transpile(readFileSync(path,'utf8'),{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}))(require,m,m.exports);return m.exports}
const policy=load('apps/admin/lib/media-policy.ts'),deadline=load('apps/admin/lib/media-deadline.ts');
const id='00000000-0000-4000-8000-000000000020';
test('Loading deadlines release stalled operations and cancellation returns immediately',async()=>{await assert.rejects(()=>deadline.boundedMedia(new Promise(()=>{}),'Timed out',5),/Timed out/);const controller=new AbortController();const result=deadline.boundedMedia(new Promise(()=>{}),'Timeout',1000,controller.signal);controller.abort();await assert.rejects(result,{name:'AbortError'});assert.equal(await deadline.boundedMedia(Promise.resolve(7),'Timeout',5),7)});
test('Preview sources use private variants and posters, with retry and stable navigation boundaries',()=>{const {mediaPreviewUrl:url,adjacentMediaId:adjacent}=load('apps/admin/lib/media-preview.ts'),image={id,kind:'image',metadata:{variants:[480]},previewUrl:'/media/'+id},video={...image,id:'video',kind:'video',poster_ready:true};assert.equal(url(image,true),'/media/'+id+'?variant=480');assert.equal(url(video,true,2),'/media/'+id+'?poster=1&retry=2');assert.equal(url(video,false),'/media/'+id);assert.equal(adjacent([image,video],id,-1),null);assert.equal(adjacent([image,video],id,1),'video');assert.equal(adjacent([image,video],'missing',1),null)});
test('All buckets are checked and diagnostics identify the unavailable type',async()=>{const checked=[];const q={select(){return this},eq(){return this},single:async()=>({data:{id}})};const {checkMediaStorage}=load('apps/admin/lib/media-actions.ts',name=>name==='./auth'?{requireAdmin:async()=>{}}:name==='./supabase'?{adminDb:async()=>({from:()=>q,storage:{from:bucket=>({list:async()=>{checked.push(bucket);return{error:bucket.endsWith('audio')?{}:null}}})}})}:policy);const result=await checkMediaStorage(id);assert.equal(result.available,false);assert.match(result.message,/audio/);assert.deepEqual(checked.sort(),['wiffeyyyy-audio','wiffeyyyy-image','wiffeyyyy-video'])});
test('Stopping an in-flight transfer preserves its reservation for resume',async()=>{
 let xhr,puts=0,reserves=0;const old=global.XMLHttpRequest,controller=new AbortController();
 global.XMLHttpRequest=class{upload={};open(){puts++}setRequestHeader(){}send(){xhr=this}abort(){this.onabort();this.onloadend?.()}};
 const {uploadMedia}=load('apps/admin/lib/media-upload.ts',name=>name==='./media-policy'?policy:name==='./media-deadline'?deadline:name==='./media-actions'?{reserveMedia:async()=>{reserves++;return{ok:true,id,path:'site/id/original',bucket:'audio'}},finalizeMedia:async()=>({ok:true})}:name==='@supabase/ssr'?{createBrowserClient:()=>({auth:{getSession:async()=>({data:{session:{access_token:'test'}}})}})}:{});
 const attempt={metadata:{durationMs:1000,variants:[]},completed:new Set()},file={type:'audio/mpeg',size:100,name:'song.mp3'};
 try{const first=uploadMedia(id,file,()=>{},attempt,controller.signal);while(!xhr)await new Promise(resolve=>setTimeout(resolve,1));controller.abort();await assert.rejects(first,{name:'AbortError'});assert.equal(attempt.reservation.id,id);assert.equal(attempt.completed.size,0);xhr=null;const resume=uploadMedia(id,file,()=>{},attempt);while(!xhr)await new Promise(resolve=>setTimeout(resolve,1));xhr.status=200;xhr.onload();xhr.onloadend?.();assert.equal(await resume,id);assert.equal(reserves,1);assert.equal(puts,2);assert.equal(attempt.completed.size,1)}finally{global.XMLHttpRequest=old}
});
test('Video capture is silent, bounded and releases its object URL on success and timeout',async()=>{
 const old={document:global.document,URL:global.URL};let revoked=0,paused=0,seek=0,draw=0,hang=false;const {createVideoPoster}=load('apps/admin/lib/video-poster.ts');
 global.URL={createObjectURL:()=> 'blob:fixture',revokeObjectURL:()=>revoked++};
 global.document={createElement:kind=>kind==='canvas'?{getContext:()=>({drawImage:()=>draw++}),toBlob:callback=>callback(new Blob(['RIFF0000WEBP'],{type:'image/webp'}))}:(()=>{const video={readyState:2,videoWidth:1920,videoHeight:1080,duration:2,pause(){paused++},removeAttribute(){},load(){if(this.src&&!hang)queueMicrotask(()=>this.onloadedmetadata?.())}};Object.defineProperty(video,'currentTime',{set(){seek++;queueMicrotask(()=>video.onseeked?.())}});return video})()};
 try{const poster=await createVideoPoster(new Blob(['video']),20);assert.equal(poster.type,'image/webp');assert.equal(draw,1);assert.equal(seek,1);assert.equal(revoked,1);hang=true;await assert.rejects(()=>createVideoPoster(new Blob(['video']),5),/Unable to generate/);assert.equal(revoked,2);assert.equal(paused,2)}finally{Object.assign(global,old)}
});
test('Poster saving requires a writer and a verified video, and never upserts the original',async()=>{
 let kind='image',upload=0,patch;const q={select(){return this},eq(){return this},single:async()=>({data:{id,site_id:id,kind,status:'ready',storage_path:'site/id/original'}}),update(value){patch=value;return this},then(resolve){resolve({error:null})}};
 const db={from:()=>q,auth:{getSession:async()=>({data:{session:{access_token:'test'}}})},storage:{from:()=>({upload:async(path,blob,options)=>{upload++;assert.equal(path,'site/id/poster.webp');assert.equal(options.upsert,false);return{error:null}}})}};
 const {saveMediaPoster}=load('apps/admin/lib/media-actions.ts',name=>name==='./auth'?{requireAdmin:async permission=>assert.equal(permission,'media:write')}:name==='./supabase'?{adminDb:async()=>db}:name==='./media-verification'?{verifyMediaObject:async(url,headers,object)=>assert.equal(object.maxSize,524288)}:policy);
 const input=new FormData();input.set('poster',new Blob(['RIFF0000WEBP'],{type:'image/webp'}));await assert.rejects(()=>saveMediaPoster(id,input),/verified video/);assert.equal(upload,0);kind='video';await saveMediaPoster(id,input);assert.equal(upload,1);assert.deepEqual(patch,{poster_ready:true});input.set('poster',new Blob(['<html>'],{type:'image/webp'}));await assert.rejects(()=>saveMediaPoster(id,input),/WebP thumbnail/)
});
test('Poster delivery rejects missing, wrong-kind and unsigned inventory before signing',async()=>{
 let ready=false,kind='video',signed=0;const q={select(){return this},eq(){return this},maybeSingle:async()=>({data:{poster_ready:ready,kind,storage_path:'site/id/original'}})};
 const {GET}=load('apps/admin/app/media/[id]/route.ts',name=>name.endsWith('/auth')?{requireAdmin:async()=>{}}:name.endsWith('/supabase')?{adminDb:async()=>({from:()=>q,storage:{from:()=>({createSignedUrl:async path=>{signed++;assert.equal(path,'site/id/poster.webp');return{data:{signedUrl:'https://example.test/private'}}}})}})}:policy);
 const get=()=>GET(new Request('https://example.test/media/'+id+'?poster=1'),{params:Promise.resolve({id})});assert.equal((await get()).status,404);ready=true;kind='image';assert.equal((await get()).status,404);assert.equal(signed,0);kind='video';assert.equal((await get()).status,307);assert.equal(signed,1)
});
test('remote poster generation decodes a ranged video source without downloading a full Blob',async()=>{
 const old={document:global.document,URL:global.URL};let source='',crossOrigin='',revoked=0;
 const {createVideoPoster}=load('apps/admin/lib/video-poster.ts');
 global.URL={createObjectURL:()=>{throw Error('Remote previews must not allocate a full video Blob')},revokeObjectURL:()=>revoked++};
 global.document={createElement:kind=>kind==='canvas'?{getContext:()=>({drawImage:()=>{}}),toBlob:callback=>callback(new Blob(['RIFF0000WEBP'],{type:'image/webp'}))}:(()=>{const video={readyState:2,videoWidth:720,videoHeight:1280,duration:2,pause(){},removeAttribute(){this.src=''},load(){if(this.src){source=this.src;crossOrigin=this.crossOrigin;queueMicrotask(()=>this.onloadedmetadata?.())}}};Object.defineProperty(video,'currentTime',{set(){queueMicrotask(()=>video.onseeked?.())}});return video})()};
 try{const poster=await createVideoPoster('/media/verified-video',100);assert.equal(poster.type,'image/webp');assert.equal(source,'/media/verified-video');assert.equal(crossOrigin,'anonymous');assert.equal(revoked,0)}finally{Object.assign(global,old)}
});
