import test from 'node:test';
import assert from 'node:assert/strict';
import ts from 'typescript';
import {readFileSync} from 'node:fs';
function route(media){let lookups=0,signs=0;const caches=[];const db={rpc:async()=>{lookups++;return {data:media}},storage:{from:()=>({createSignedUrl:async(path,seconds,options)=>{signs++;assert.equal(seconds,options?60:300);return {data:{signedUrl:'https://storage.example/'+path+(options?'?download=1':'')}}}})}};const m={exports:{}};const cache=(fn)=>{const entries=new Map();caches.push(entries);return (...args)=>{const key=JSON.stringify(args);if(!entries.has(key))entries.set(key,fn(...args));return entries.get(key)}};new Function('require','module','exports',ts.transpile(readFileSync('apps/web/app/media/[id]/route.ts','utf8'),{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}))(name=>name==='next/cache'?{unstable_cache:cache}:{createClient:()=>db},m,m.exports);return {...m.exports,counts:()=>({lookups,signs}),invalidate:()=>caches.forEach(c=>c.clear())};}
const id='00000000-0000-4000-8000-000000000020',context={params:Promise.resolve({id})};
process.env.NEXT_PUBLIC_SUPABASE_URL='https://example.supabase.co';process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY='fixture';process.env.NEXT_PUBLIC_SITE_SLUG='fixture';
const get=(r,query='')=>r.GET(new Request('https://site.example/media/'+id+query),context);
test('warm previews reuse signing while respecting poster and variant publication bounds',async()=>{const r=route({path:'site/id/original',kind:'image',variants:[480]});const first=await get(r,'?thumbnail=1');assert.equal(first.status,307);assert.equal(first.headers.get('Cache-Control'),'private, max-age=10');assert.equal(first.headers.get('Location'),'https://storage.example/site/id/480.webp');await get(r,'?variant=480');assert.deepEqual(r.counts(),{lookups:1,signs:1});assert.equal((await get(r,'?variant=1600')).status,404);assert.equal((await get(r,'?poster=1')).status,404);assert.equal(r.counts().signs,1);r.invalidate();await get(r,'?thumbnail=1');assert.deepEqual(r.counts(),{lookups:2,signs:2});});
test('unpublished media never signs and explicit downloads bypass URL reuse',async()=>{const missing=route(null);assert.equal((await get(missing)).status,404);assert.equal(missing.counts().signs,0);const r=route({path:'site/id/original',kind:'audio',filename:'song.mp3'});for(let i=0;i<2;i++){const response=await get(r,'?download=1');assert.equal(response.headers.get('Cache-Control'),'no-store')}assert.equal(r.counts().signs,2);});
