import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
const cache=new Map();
function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file).exports;const module={exports:{}};cache.set(file,module);const code=ts.transpile(fs.readFileSync(file,'utf8'),{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022});new Function('require','module','exports',code)(name=>{if(!name.startsWith('.'))throw new Error('Unexpected dependency '+name);return load(path.resolve(path.dirname(file),name)+'.ts')},module,module.exports);return module.exports}
const archive=load('packages/content/src/memories-archive.ts');
const capabilities=load('packages/content/src/inspector-capabilities.ts');
let id=0;const make=()=>`id-${++id}`;

test('Memories Archive seeds neutral editable memories without borrowing puzzle images',()=>{id=0;const doc=archive.createMemoriesArchive(make);const images=doc.nodes.filter(n=>n.component==='image'&&doc.nodes.find(p=>p.id===n.parentId)?.props.archivePart==='memory');assert.equal(images.length,5);assert.ok(images.every(n=>n.props.src===''));assert.ok(images.every(n=>n.props.emptyLabel==='A memory belongs here'));});

test('Add memory preserves all existing authored values and only appends a new generic memory',()=>{id=0;const doc=archive.createMemoriesArchive(make);const collection=doc.nodes.find(n=>n.props.archivePart==='collection');const first=doc.nodes.find(n=>n.props.archivePart==='memory');const firstPhoto=doc.nodes.find(n=>n.parentId===first.id&&n.component==='image');const firstTitle=doc.nodes.find(n=>n.parentId===first.id&&n.component==='heading');firstPhoto.props.src='/media/my-photo';firstTitle.props.text='MY REAL MEMORY';const before=JSON.stringify(doc.nodes.find(n=>n.id===first.id));const result=archive.addArchiveMemory(doc,collection.id,make);assert.equal(JSON.stringify(doc.nodes.find(n=>n.id===first.id)),before);assert.equal(doc.nodes.find(n=>n.id===firstPhoto.id).props.src,'/media/my-photo');assert.equal(doc.nodes.find(n=>n.id===firstTitle.id).props.text,'MY REAL MEMORY');const added=result.document.nodes.find(n=>n.id===result.selectedId);assert.equal(added.props.archivePart,'memory');const addedChildren=result.document.nodes.filter(n=>n.parentId===added.id);assert.equal(addedChildren.length,4);assert.equal(addedChildren.find(n=>n.component==='image').props.src,'');assert.match(String(addedChildren.find(n=>n.component==='heading').props.text),/memory/i);});

test('Archive settings are scoped to the relevant section',()=>{id=0;const doc=archive.createMemoriesArchive(make);const keys=part=>new Set(capabilities.getInspectorCapabilities('memories-archive',doc,doc.nodes.find(n=>n.props.archivePart===part)).map(c=>c.field.key));const page=keys('page'),hero=keys('hero'),sound=keys('soundtrack'),collection=keys('collection'),memory=keys('memory');for(const key of ['glowOneColor','decorativeHeartSize','transitionText'])assert.ok(page.has(key),key);for(const key of ['heroMinHeight','titleItalic','mobileHeroTopPadding'])assert.ok(hero.has(key),key);for(const key of ['gradientStart','gradientEnd','gradientAngle'])assert.ok(sound.has(key),key);for(const key of ['alternateLayout','revealAnimation','hoverLift'])assert.ok(collection.has(key),key);for(const key of ['imageSide','mobileImageHeight'])assert.ok(memory.has(key),key);assert.equal(hero.has('glowOneColor'),false);assert.equal(memory.has('gradientStart'),false);});

test('Archive action buttons expose destination and new-tab behavior',()=>{id=0;const doc=archive.createMemoriesArchive(make);const action=doc.nodes.find(n=>n.component==='action');const keys=new Set(capabilities.getInspectorCapabilities('memories-archive',doc,action).map(c=>c.field.key));assert.ok(keys.has('title'));assert.ok(keys.has('href'));assert.ok(keys.has('openInNewTab'));assert.equal(capabilities.normalizeInspectorValue({key:'href',label:'Link',type:'text'},'/pages/in-my-heart'),'/pages/in-my-heart');assert.throws(()=>capabilities.normalizeInspectorValue({key:'href',label:'Link',type:'text'},'javascript:alert(1)'));});

test('Archive editor exposes a dedicated non-destructive add-memory control',()=>{const source=fs.readFileSync('apps/admin/components/editor-inspector-fields.tsx','utf8');assert.match(source,/\+ Add memory/);assert.match(source,/Existing memories are never changed/);});
