import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const module={exports:{}};new Function('module','exports',ts.transpile(readFileSync('packages/content/src/app-content.ts','utf8'),{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}))(module,module.exports);
const {emptyAppProgress,parseAppProgress,reduceAppProgress,getAppItems,sampleAppItems}=module.exports;
test('damaged and unknown-version app state recovers',()=>{for(const raw of [null,'{','[]','null','{"version":2}'])assert.deepEqual(parseAppProgress(raw,['a']),emptyAppProgress())});
test('restore removes deleted content and hostile values',()=>{assert.deepEqual(parseAppProgress(JSON.stringify({version:1,favorites:['a','a','deleted',{}],selection:'deleted',receipts:{a:'2026-10-01T00:00:00.000Z',deleted:'2026-10-01T00:00:00.000Z',b:'invalid'}}),['a','b']),{version:1,favorites:['a'],selection:'',receipts:{a:'2026-10-01T00:00:00.000Z'}})});
test('favourites toggle without mutating previous state',()=>{const first=reduceAppProgress(emptyAppProgress(),{type:'favorite',id:'a'},['a']);assert.deepEqual(first.favorites,['a']);assert.deepEqual(reduceAppProgress(first,{type:'favorite',id:'a'},['a']).favorites,[]);assert.deepEqual(first.favorites,['a'])});
test('adventure choice, movie chapter and radio selection survive reload',()=>{const next=reduceAppProgress(emptyAppProgress(),{type:'select',id:'b'},['a','b']);assert.equal(parseAppProgress(JSON.stringify(next),['a','b']).selection,'b')});
test('receipt redemption is idempotent and survives reload',()=>{const first=reduceAppProgress(emptyAppProgress(),{type:'redeem',id:'a',at:'2026-10-01T00:00:00.000Z'},['a']);assert.equal(reduceAppProgress(first,{type:'redeem',id:'a',at:'2026-10-02T00:00:00.000Z'},['a']),first);assert.deepEqual(parseAppProgress(JSON.stringify(first),['a']),first)});
test('invalid receipt and unknown content cannot alter state',()=>{const s=emptyAppProgress();assert.equal(reduceAppProgress(s,{type:'redeem',id:'a',at:'invalid'},['a']),s);for(const type of ['favorite','select','redeem'])assert.equal(reduceAppProgress(s,{type,id:'outside',at:'2026-10-01T00:00:00.000Z'},['a']),s)});
test('reset only clears this app state',()=>{const s=reduceAppProgress(emptyAppProgress(),{type:'select',id:'a'},['a']);assert.deepEqual(reduceAppProgress(s,{type:'reset'},['a']),emptyAppProgress());assert.equal(s.selection,'a')});
test('published item order follows hierarchy and ancestor visibility',()=>{const d={rootIds:['root'],nodes:[{id:'a',component:'reason',visible:true,props:{title:'A'},children:[]},{id:'b',component:'reason',visible:true,props:{title:'B'},children:[]},{id:'root',component:'section',visible:true,props:{},children:['b','a']}]};assert.deepEqual(getAppItems(d,'reasons').map(x=>x.id),['b','a']);d.nodes[2].visible=false;assert.deepEqual(getAppItems(d,'reasons'),[])});
test('all six sample experiences have stable unique IDs and no fake media source',()=>{assert.equal(Object.keys(sampleAppItems).length,6);for(const items of Object.values(sampleAppItems)){assert.equal(new Set(items.map(x=>x.id)).size,items.length);assert.ok(items.every(x=>x.src===''))}});

test('prototype-like content IDs can redeem and restore safely',()=>{for(const id of ['__proto__','constructor','toString']){const s=reduceAppProgress(emptyAppProgress(),{type:'redeem',id,at:'2026-10-01T00:00:00.000Z'},[id]);assert.ok(Object.hasOwn(s.receipts,id));const restored=parseAppProgress(JSON.stringify(s),[id]);assert.equal(restored.receipts[id],'2026-10-01T00:00:00.000Z');assert.equal(Object.getPrototypeOf(restored.receipts),Object.prototype)}});
