import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const url=js=>'data:text/javascript;base64,'+Buffer.from(js).toString('base64');
const compile=name=>ts.transpile(fs.readFileSync(new URL('../packages/content/src/'+name+'.ts',import.meta.url),'utf8'),{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022});
const registry=url(compile('registry'));
const validate=url(compile('validate').replace("'./registry'",JSON.stringify(registry)));
const ops=await import(url(compile('editor-operations').replace("'./registry'",JSON.stringify(registry)).replace("'./validate'",JSON.stringify(validate))));
const empty=()=>({schemaVersion:2,nodes:[],rootIds:[]});
const nested=()=>{let d=empty();d=ops.insertNode(d,'section','a',null);d=ops.insertNode(d,'section','b','a');d=ops.insertNode(d,'heading','c','b');d=ops.insertNode(d,'text','d','a');return d};
test('insertion builds correct hierarchy without modifying original',()=>{const initial=empty();const doc=ops.insertNode(initial,'section','a',null);assert.equal(initial.nodes.length,0);assert.deepEqual(doc.rootIds,['a']);assert.equal(doc.nodes[0].parentId,null)});
test('cannot insert blocks at root or inside blocks',()=>{assert.throws(()=>ops.insertNode(empty(),'text','a',null));assert.throws(()=>ops.insertNode(nested(),'text','x','c'))});
test('cannot insert duplicate ID or exceed nesting limit',()=>{assert.throws(()=>ops.insertNode(nested(),'section','a',null));let d=empty();for(let i=0;i<21;i++)d=ops.insertNode(d,'section','n'+i,i?'n'+(i-1):null);assert.throws(()=>ops.insertNode(d,'section','deep','n20'))});
test('deep duplicate remaps every child and preserves content and order',()=>{const doc=nested();let i=0;const result=ops.duplicateNode(doc,'a',()=> 'copy'+i++);assert.deepEqual(result.document.rootIds,['a','copy0']);const copy=result.document.nodes.find(n=>n.id==='copy0');assert.deepEqual(copy.children,['copy1','copy3']);assert.equal(result.document.nodes.find(n=>n.id==='copy2').parentId,'copy1');assert.deepEqual(result.document.nodes.find(n=>n.id==='copy2').props,doc.nodes.find(n=>n.id==='c').props);assert.equal(doc.nodes.length,4)});
test('block duplicate is inserted immediately after original sibling',()=>{let i=0;const result=ops.duplicateNode(nested(),'d',()=> 'clone'+i++);assert.deepEqual(result.document.nodes.find(n=>n.id==='a').children,['b','d','clone0'])});
test('delete removes descendants and stale references',()=>{const d=ops.deleteNode(nested(),'b');assert.deepEqual(d.nodes.map(n=>n.id),['a','d']);assert.deepEqual(d.nodes[0].children,['d']);assert.deepEqual(ops.deleteNode(d,'a'),empty())});
test('move only changes sibling ordering and boundaries are no-ops',()=>{const d=nested();assert.deepEqual(ops.moveNode(d,'d',-1).nodes[0].children,['d','b']);assert.equal(ops.moveNode(d,'b',-1),d);assert.deepEqual(d.nodes[0].children,['b','d'])});
test('invalid edit rejected without mutating state',()=>{const d=nested();assert.throws(()=>ops.updateNode(d,'c',{props:{size:500}}));assert.equal(d.nodes.find(n=>n.id==='c').props.size,30)});
test('visibility and labels persist through edits',()=>{const d=ops.updateNode(nested(),'c',{visible:false,label:'My heading'});assert.equal(d.nodes.find(n=>n.id==='c').visible,false);assert.equal(d.nodes.find(n=>n.id==='c').label,'My heading')});
const state=()=>({document:nested(),selectedId:'c',past:[],future:[]});
test('undo and redo restore complete document snapshots',()=>{let s=state();const original=s.document;s=ops.editorReducer(s,{type:'commit',document:ops.deleteNode(s.document,'b'),selectedId:'a'});s=ops.editorReducer(s,{type:'undo'});assert.deepEqual(s.document,original);s=ops.editorReducer(s,{type:'redo'});assert.deepEqual(s.document.nodes.map(n=>n.id),['a','d'])});
test('new edit after undo clears redo and no-op edits create no history',()=>{let s=state();assert.equal(ops.editorReducer(s,{type:'commit',document:s.document}),s);s=ops.editorReducer(s,{type:'commit',document:ops.updateNode(s.document,'c',{label:'Changed'})});s=ops.editorReducer(s,{type:'undo'});s=ops.editorReducer(s,{type:'commit',document:ops.updateNode(s.document,'c',{label:'Other'})});assert.equal(s.future.length,0)});
test('history bounded and stale selection cleared on undo',()=>{let s=state();for(let i=0;i<60;i++)s=ops.editorReducer(s,{type:'commit',document:ops.updateNode(s.document,'c',{label:String(i)})});assert.equal(s.past.length,50);s=ops.editorReducer(s,{type:'commit',document:ops.insertNode(s.document,'text','new','a'),selectedId:'new'});s=ops.editorReducer(s,{type:'undo'});assert.equal(s.selectedId,null)});
