import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
let db;
const owner='00000000-0000-4000-8000-000000000001',editor='00000000-0000-4000-8000-000000000002',viewer='00000000-0000-4000-8000-000000000003';
const site='00000000-0000-4000-8000-000000000010',page='00000000-0000-4000-8000-000000000011',other='00000000-0000-4000-8000-000000000012';
const doc=text=>({schemaVersion:2,nodes:[{id:'s',type:'section',component:'section',parentId:null,props:{padding:20},visible:true,children:['t']},{id:'t',type:'block',component:'text',parentId:'s',props:{text},children:[],visible:true}],rootIds:['s']});
before(async()=>{
 db=new PGlite();await db.exec(`create role anon nologin;create role authenticated nologin;create schema auth;create table auth.users(id uuid primary key);create table auth.sessions(id uuid primary key,user_id uuid references auth.users(id),not_after timestamptz);create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;create function auth.jwt() returns jsonb language sql stable as $$ select jsonb_build_object('session_id',nullif(current_setting('request.jwt.claim.session_id',true),'')) $$;grant usage on schema public,auth to anon,authenticated;`);
 for(const file of readdirSync('supabase/migrations').filter(x=>x.endsWith('.sql')).sort())await db.exec(readFileSync('supabase/migrations/'+file,'utf8').replace('create extension if not exists pgcrypto;',''));
 await db.exec(`insert into auth.users values('${owner}'),('${editor}'),('${viewer}');insert into auth.sessions(id,user_id)select id,id from auth.users;insert into public.admin_users(id,role)values('${owner}','owner'),('${editor}','editor'),('${viewer}','viewer');insert into public.sites(id,name,slug,public_delivery_enabled)values('${site}','Test','phase5-test',true);`);
 for(const [id,slug] of [[page,'home'],[other,'other']])await db.query('insert into public.pages(id,site_id,slug,title,draft_document)values($1,$2,$3,$3,$4)',[id,site,slug,JSON.stringify(doc('Initial'))]);
});after(()=>db.close());
async function role(user){await db.exec('set local role authenticated');await db.query("select set_config('request.jwt.claim.sub',$1,true),set_config('request.jwt.claim.session_id',$1,true)",[user]);}
async function run(user,fn){await db.exec('begin');try{await role(user);await fn()}finally{await db.exec('rollback')}}
const save=async(userDoc,revision=0,id=page)=>(await db.query('select public.save_page_draft($1,$2,$3) result',[id,JSON.stringify(userDoc),revision])).rows[0].result;
const publish=async(revision,id=page)=>(await db.query('select public.publish_page($1,$2) result',[id,revision])).rows[0].result;
const rollback=async(version,revision,id=page)=>(await db.query('select public.rollback_page($1,$2,$3) result',[id,version,revision])).rows[0].result;
async function rejects(fn,pattern){await db.exec('savepoint rejected');try{await assert.rejects(fn,pattern)}finally{await db.exec('rollback to rejected;release savepoint rejected')}}
const live=async()=>(await db.query("select public.get_published_document('phase5-test','home') doc")).rows[0].doc;
test('editor autosave atomically snapshots draft with actor/revision and never publishes',()=>run(editor,async()=>{const result=await save(doc('Edited'));assert.equal(result.revision,1);assert.equal(await live(),null);const v=(await db.query('select status,document,created_by from public.page_versions where id=$1',[result.versionId])).rows[0];assert.equal(v.status,'draft');assert.deepEqual(v.document,doc('Edited'));assert.equal(v.created_by,editor);assert.equal((await db.query('select count(*)::int n from public.audit_logs where actor_id=$1',[editor])).rows[0].n,2)}));
test('unchanged save creates no new version or revision',()=>run(editor,async()=>{assert.equal((await save(doc('Initial'))).changed,false);assert.equal((await db.query('select count(*)::int n from public.page_versions')).rows[0].n,0)}));
test('stale save/publish revisions rejected, retaining newest draft',()=>run(owner,async()=>{await save(doc('New'));await rejects(()=>save(doc('Stale'),0),/DRAFT_CONFLICT/);await rejects(()=>publish(0),/DRAFT_CONFLICT/);assert.deepEqual((await db.query('select draft_document from public.pages where id=$1',[page])).rows[0].draft_document,doc('New'))}));
test('owner publish is atomic and repeated publication idempotent',()=>run(owner,async()=>{await save(doc('Published'));const p=await publish(1);assert.deepEqual(await live(),doc('Published'));assert.equal((await publish(1)).versionId,p.versionId);assert.equal((await db.query('select count(*)::int n from public.page_versions')).rows[0].n,2)}));
test('later draft edits do not alter published snapshot',()=>run(owner,async()=>{await save(doc('Published'));await publish(1);await save(doc('Unpublished'),1);assert.deepEqual(await live(),doc('Published'))}));
test('rollback appends publication and retains draft',()=>run(owner,async()=>{await save(doc('First'));const first=await publish(1);await save(doc('Second'),1);await publish(2);await save(doc('Working'),2);const result=await rollback(first.versionId,3);assert.ok(result.versionNumber>first.versionNumber);assert.deepEqual(await live(),doc('First'));assert.deepEqual((await db.query('select draft_document from public.pages where id=$1',[page])).rows[0].draft_document,doc('Working'))}));
test('cross-page and draft-version rollback rejected',()=>run(owner,async()=>{const draft=await save(doc('Draft'));await rejects(()=>rollback(draft.versionId,1),/Published version not found/);await save(doc('Other'),0,other);const version=await publish(1,other);await rejects(()=>rollback(version.versionId,1),/Published version not found/)}));
test('viewer cannot save; editor cannot publish or rollback',async()=>{await run(viewer,()=>rejects(()=>save(doc('Attack')),/Not authorized/));await run(editor,async()=>{await rejects(()=>publish(0),/Not authorized/);await rejects(()=>rollback(other,0),/Not authorized/)})});
test('version records are immutable to owner and editor',()=>run(owner,async()=>{const v=await save(doc('Immutable'));await rejects(()=>db.query("update public.page_versions set document='{}' where id=$1",[v.versionId]),/permission denied/);await rejects(()=>db.query('delete from public.page_versions where id=$1',[v.versionId]),/permission denied/)}));
test('empty publication rejected',()=>run(owner,async()=>{await save({schemaVersion:2,nodes:[],rootIds:[]});await rejects(()=>publish(1),/empty page/)}));
test('RPC database boundary rejects malformed tree, missing fields, unsafe media and style',()=>run(owner,async()=>{for(const mutate of [d=>delete d.schemaVersion,d=>delete d.nodes[0].type,d=>delete d.nodes[0].parentId,d=>d.nodes[1].children=['s'],d=>d.nodes[0].children=['missing'],d=>d.nodes[1].props.src='javascript:alert(1)',d=>d.nodes[1].props.size=1000]){const d=doc('Bad');mutate(d);await rejects(()=>save(d),/Invalid|Unsafe|Blocks/)}}));
test('forced publication failure rolls back snapshot, pointer and audit',async()=>{
 await db.exec('begin');try{
 await db.exec(`create function public.test_fail_publish()returns trigger language plpgsql as $$begin if new.published_version_id is not null then raise exception 'forced failure';end if;return new;end$$;create trigger test_fail before update on public.pages for each row execute function public.test_fail_publish();`);
 await role(owner);await save(doc('Ready'));await rejects(()=>publish(1),/forced failure/);assert.equal(await live(),null);assert.equal((await db.query('select count(*)::int n from public.page_versions')).rows[0].n,1);assert.equal((await db.query('select count(*)::int n from public.audit_logs where actor_id=$1',[owner])).rows[0].n,2);
 }finally{await db.exec('rollback')}
});
test('anonymous callers cannot execute save/publish/rollback',async()=>{await db.exec('begin;set local role anon');try{await rejects(()=>save(doc('Attack')),/permission denied/);await rejects(()=>publish(0),/permission denied/);await rejects(()=>rollback(other,0),/permission denied/)}finally{await db.exec('rollback')}});
test('signed-out session cannot save',async()=>{await db.exec('begin');try{await db.query('delete from auth.sessions where id=$1',[editor]);await role(editor);await rejects(()=>save(doc('Replay')),/Not authorized/)}finally{await db.exec('rollback')}});
