import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
import {createElement} from 'react';
import {renderToStaticMarkup as render} from 'react-dom/server';
const root=process.cwd(),cache=new Map();
function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file).exports;const module={exports:{}};cache.set(file,module);const ext=path.extname(file),source=fs.readFileSync(file,'utf8'),code=ts.transpile(source,{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ext==='.tsx'?ts.JsxEmit.ReactJSX:undefined,esModuleInterop:true});new Function('require','module','exports','__filename','__dirname',code)(name=>{if(name==='react')return require('react');if(name==='react/jsx-runtime')return require('react/jsx-runtime');if(name==='react-dom/server')return require('react-dom/server');if(name==='next/navigation')return require('next/navigation');if(name.startsWith('@wiffeyyyy/content'))return load(path.join(root,'packages/content/src/index.ts'));if(name.startsWith('@wiffeyyyy/ui/')){const stem=name.replace('@wiffeyyyy/ui/','');return load(path.join(root,'packages/ui/src/'+stem+'.tsx'))}if(name.startsWith('.')){let target=path.resolve(path.dirname(file),name);for(const suffix of ['', '.ts','.tsx','.js','.mjs'])if(fs.existsSync(target+suffix))return load(target+suffix);throw new Error('Missing '+name)}throw new Error('Unexpected '+name)},module,module.exports,file,path.dirname(file));return module.exports}
const {createDefaultPage,componentRegistry,insertNode,updateNode,parsePageDocument}=load(path.join(root,'packages/content/src/index.ts'));
const {CMSRenderer}=load(path.join(root,'packages/ui/src/cms-renderer.tsx'));
const Editor=load(path.join(root,'apps/admin/app/editor/[slug]/editor-client.tsx')).default;
const edit=(doc,id,patch)=>updateNode(doc,id,patch);

test('empty editor renders insertion controls and mobile panels',()=>{const html=render(Editor,{pageId:'test',initialDocument:{version:1,rootIds:[],nodes:[]}});assert.match(html,/Add your first section/);assert.match(html,/Editor panels/);assert.match(html,/Live canvas/);assert.match(html,/Inspector/)});
test('viewer renders read-only controls and owner publication is disabled',()=>{const doc=createDefaultPage('welcome'),html=render(Editor,{pageId:'test',initialDocument:doc,canWrite:false,canPublish:false});assert.match(html,/read-only access/);assert.match(html,/disabled=""/)});
test('selected section exposes all registered insertion choices',()=>{let doc={version:1,rootIds:[],nodes:[]};doc=insertNode(doc,'section','root',null);const html=render(Editor,{pageId:'test',initialDocument:doc});for(const value of Object.values(componentRegistry))assert.match(html,new RegExp(value.label.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')))});
test('public renderer uses theme, hides subtrees, and editor has keyboard selection without navigation',()=>{let doc=createDefaultPage('welcome');const rootNode=doc.nodes.find(n=>n.type==='section');doc=edit(doc,rootNode.id,{props:{background:'#123456'}});const hidden=doc.nodes.find(n=>n.parentId===rootNode.id);doc=edit(doc,hidden.id,{visible:false});const html=render(CMSRenderer,{document:doc});assert.match(html,/#123456/);assert.doesNotMatch(html,new RegExp(String(hidden.props.text??hidden.props.title??'THIS-WILL-NOT-MATCH')));const editor=render(CMSRenderer,{document:doc,onSelect:()=>{},selectedId:rootNode.id});assert.match(editor,/role="button"/);assert.match(editor,/tabindex="0"/)});
test('image renderer preserves intrinsic dimensions, focal crop and responsive variants',()=>{let doc={version:1,rootIds:[],nodes:[]};doc=insertNode(doc,'section','root',null);doc=insertNode(doc,'image','image','root');doc=edit(doc,'image',{props:{src:'https://example.com/image.jpg',alt:'Example',width:1200,height:800,focalX:20,focalY:70,variants:{mobile:'https://example.com/mobile.jpg',desktop:'https://example.com/desktop.jpg'}}});const html=render(CMSRenderer,{document:doc});assert.match(html,/width="1200"/);assert.match(html,/height="800"/);assert.match(html,/object-position:20% 70%/);assert.match(html,/mobile.jpg/);assert.match(html,/desktop.jpg/)});
test('audio and video blocks use native controls without autoplay',()=>{for(const component of ['audio','video']){let doc={version:1,rootIds:[],nodes:[]};doc=insertNode(doc,'section','root',null);doc=insertNode(doc,component,'media','root');doc=edit(doc,'media',{props:{src:'https://example.com/file.mp4'}});const html=render(CMSRenderer,{document:doc});assert.match(html,new RegExp('<'+component));assert.match(html,/controls=""/);assert.doesNotMatch(html,/autoplay/)}});
test('published app blocks render interactive experiences in hierarchy order',()=>{for(const slug of ['hotline','reasons','adventure','movie','kiss-shop']){const html=render(CMSRenderer,{document:createDefaultPage(slug)});assert.ok(html.length>500,slug);assert.doesNotMatch(html,/Select (Adore|Pardanasheen|Saragram|KissShop)/)}});
test('complete default pages render the same real layout in selection and interactive modes',()=>{for(const slug of ['hotline','reasons','adventure','movie','kiss-shop']){const doc=createDefaultPage(slug),selected=doc.nodes.find(n=>n.parentId!==null)??doc.nodes[0],publicHtml=render(CMSRenderer,{document:doc}),editorHtml=render(CMSRenderer,{document:doc,onSelect:()=>{},selectedId:selected.id});assert.ok(publicHtml.length>500);assert.ok(editorHtml.length>500)}});
test('typed app sections retain edited labels and media in the real editor layout',()=>{
 let document=createDefaultPage('hotline');const message=document.nodes.find(n=>n.component==='hotline-message');document=edit(document,message.id,{props:{title:'My real message',body:'My own transcript',src:'https://example.com/greeting.mp3'}});const html=render(CMSRenderer,{document,onSelect:()=>{},selectedId:message.id});assert.match(html,/My real message/);assert.match(html,/My own transcript/);assert.match(html,/data-layout-node-id/);assert.match(html,/greeting.mp3/);
});
test('receipt images escape user copy instead of injecting SVG markup',()=>{const {giftReceiptSvg}=load(path.join(root,'packages/ui/src/page-layout.tsx'));const svg=giftReceiptSvg([{id:'gift',props:{title:'<script>alert(1)</script>'}}],'A & B','No expiry');assert.doesNotMatch(svg,/<script>/);assert.match(svg,/&lt;script&gt;/);assert.match(svg,/A &amp; B/)});

test('providers exported across the RSC boundary are component functions and render their children',()=>{for(const [file,key,value] of [['navigation','SiteNavigationProvider',null],['page-layout','DocumentSettingsProvider',load(path.join(root,'packages/content/src/site-document.ts')).defaultSiteDocument],['media-player','AudioDefaultsProvider',{volume:1,muted:false}]]){const Provider=load(path.join(root,'packages/ui/src/'+file+'.tsx'))[key];assert.equal(typeof Provider,'function');assert.match(render(Provider,{value,children:createElement('p',null,'Provider content')}),/Provider content/)}});

test('Android home renders wallpaper, six full icon links, notification shade and selectable editor layers',()=>{
 const {installPhoneHome}=load(path.join(root,'packages/content/src/index.ts'));
 let document=installPhoneHome(createDefaultPage('home'));
 const wallpaper=document.nodes.find(n=>n.props.phonePart==='wallpaper');
 document=edit(document,wallpaper.id,{props:{src:'https://example.com/wallpaper.jpg',focalX:25,focalY:75,dim:0.3}});
 const html=render(CMSRenderer,{document});
 assert.match(html,/phone-wallpaper-image/);assert.match(html,/object-position:25% 75%/);assert.match(html,/Open notification shade/);assert.match(html,/Phone navigation/);assert.match(html,/Clear all/);
 for(const slug of ['reasons','hotline','adventure','movie','kiss-shop','camera','vault'])assert.match(html,new RegExp('href="/app/'+slug+'"'));
 const selected=document.nodes.find(n=>n.props.phonePart==='app-icon');
 const editor=render(CMSRenderer,{document,onSelect:()=>{},selectedId:selected.id});
 assert.match(editor,/Select Adore/);assert.doesNotMatch(editor,/href="\/app\//);
 const inspector=render(Editor,{pageId:'test',siteId:'site',initialDocument:document});assert.match(inspector,/iPhone home screen/);assert.match(inspector,/>Wallpaper</);assert.match(inspector,/Exact live draft preview/);
});

test('iPhone home presents seven destinations with Hotdial, Pardanasheen and Clicksara in both grid and dock, removes Android navigation and unnecessary copy',()=>{
 const {installPhoneHome}=load(path.join(root,'packages/content/src/index.ts'));const document=installPhoneHome(createDefaultPage('home')),html=render(CMSRenderer,{document});
 assert.match(html,/phone-island/);assert.match(html,/phone-dock/);assert.match(html,/phone-home-indicator/);assert.doesNotMatch(html.split('<dialog')[0],/aria-label="Back"|href="\/home"|Six little places|A little world, just for you|Your birthday edition|phone-folder-link/);
 for(const slug of ['reasons','hotline','adventure','movie','kiss-shop','camera','vault'])assert.equal((html.match(new RegExp('aria-label="Open '+({'reasons':'Adore','hotline':'Hotdial','adventure':'Pardanasheen','movie':'Saragram','kiss-shop':'Kiss Shop','camera':'Clicksara','vault':'Vault'}[slug])+'"','g'))??[]).length,['hotline','camera','adventure'].includes(slug)?2:1);
});

test('live Hotline keeps editable section labels and a disabled editor call preview',()=>{const doc=createDefaultPage('hotline'),publicHtml=render(CMSRenderer,{document:doc}),editorHtml=render(CMSRenderer,{document:doc,onSelect:()=>{},selectedId:doc.nodes[0].id});assert.match(publicHtml,/Priority line|future husband/i);assert.match(editorHtml,/Select|Priority line|future husband/i)});
test('Pardanasheen retains editable photo/video layers and shows only supplied public media',()=>{let doc=createDefaultPage('adventure');const item=doc.nodes.find(n=>n.component==='adventure-choice');doc=edit(doc,item.id,{props:{src:'https://example.com/look.jpg',title:'Look one',body:'Fit check'}});const html=render(CMSRenderer,{document:doc,onSelect:()=>{},selectedId:item.id});assert.match(html,/look.jpg/);assert.match(html,/Look one/);assert.match(html,/data-layout-node-id/)});
test('Adore journal keeps voice notes and selected reason and letter layers editable',()=>{let doc=createDefaultPage('reasons');const reason=doc.nodes.find(n=>n.component==='reason');doc=edit(doc,reason.id,{props:{title:'Reason one',body:'Because you make ordinary days softer.',voiceSrc:'https://example.com/reason.mp3'}});const html=render(CMSRenderer,{document:doc,onSelect:()=>{},selectedId:reason.id});assert.match(html,/Reason one/);assert.match(html,/reason.mp3/);assert.match(html,/data-layout-node-id/)});
test('shared notifications expose an app trigger and reuse home editable messages without duplicate shades',()=>{const document=createDefaultPage('home'),html=render(CMSRenderer,{document});assert.match(html,/notification/i)});
test('Saragram uses supplied media, keeps photo and reel selection editable, and hides removed media',()=>{let doc=createDefaultPage('movie');const scene=doc.nodes.find(n=>n.component==='movie-scene');doc=edit(doc,scene.id,{props:{src:'https://example.com/reel.mp4',poster:'https://example.com/reel.jpg',title:'A reel'}});const html=render(CMSRenderer,{document:doc,onSelect:()=>{},selectedId:scene.id});assert.match(html,/reel.mp4/);assert.match(html,/data-layout-node-id/)});
test('Camera requires an explicit permission action and exposes photo and video controls',()=>{const Camera=load(path.join(root,'packages/ui/src/camera-app.tsx')).default??load(path.join(root,'packages/ui/src/camera-app.tsx')).CameraApp;assert.equal(typeof Camera,'function')});
test('Saved iPhone homes replace Radio with Camera and move Hotdial into the grid',()=>{const {installPhoneHome}=load(path.join(root,'packages/content/src/index.ts'));const doc=installPhoneHome(createDefaultPage('home'));assert.ok(doc.nodes.some(n=>n.props.pageSlug==='camera'));assert.ok(!doc.nodes.some(n=>n.props.pageSlug==='radio'&&n.visible))});
test('Pardanasheen includes every saved camera photo/video in its library',()=>{const source=fs.readFileSync(path.join(root,'packages/ui/src/photo-library.tsx'),'utf8');assert.match(source,/camera|capture/i)});
test('KissShop renders eight boutique gifts and three free treats with editable products',()=>{const html=render(CMSRenderer,{document:createDefaultPage('kiss-shop')});assert.match(html,/kiss|gift/i)});
test('Memories Archive edits flow to both public and editor rendering, with responsive collection and independent memories',()=>{const doc=createDefaultPage('memories-archive'),html=render(CMSRenderer,{document:doc}),editor=render(CMSRenderer,{document:doc,onSelect:()=>{},selectedId:doc.rootIds[0]});assert.ok(html.length>500);assert.ok(editor.length>500);assert.match(html,/Memories/i)});
test('Original heart experience preserves the engine, editor hierarchy and safe three-page journey',()=>{const doc=createDefaultPage('in-my-heart'),html=render(CMSRenderer,{document:doc});assert.ok(html.length>100);assert.match(JSON.stringify(doc),/heart/i)});
