import type {CMSField,CMSNode,PageDocument} from './cms';
import {createNode,type ComponentName} from './registry';
import type {InspectorField} from './inspector-fields';
export const authoredApps=['movie','adventure','camera','reasons','hotline','vault','kiss-shop','pieces'] as const;
export type AuthoredApp=typeof authoredApps[number];
type Setting={value:CMSField;field:InspectorField};
const text=(key:string,label:string,value:string):Setting=>({value,field:{key,label,type:'text'}});
const color=(key:string,label:string,value:string):Setting=>({value,field:{key,label,type:'color'}});
const choice=(key:string,label:string,value:string,options:string[]):Setting=>({value,field:{key,label,type:'select',options}});
const number=(key:string,label:string,value:number,min:number,max:number):Setting=>({value,field:{key,label,type:'number',min,max}});
const titles:Record<AuthoredApp,string>={movie:'saragram',adventure:'Pardanasheen',camera:'Clicksara',reasons:'Adore',hotline:'Hotdial',vault:'VAULT','kiss-shop':'Kiss Shop',pieces:'Pieces of Us'};
const own:Record<AuthoredApp,Setting[]>={
 movie:[text('postsLabel','Posts tab','Posts'),text('reelsLabel','Reels tab','Reels'),text('emptyTitle','Empty feed title','Your moments belong here'),text('emptyMessage','Empty feed message','Photos and videos will appear here when they are added.')],
 adventure:[text('cameraAlbum','Camera album name','Camera'),text('emptyTitle','Empty library title','No Photos or Videos'),text('emptyMessage','Empty library message','Your fit checks will appear in your library once added.'),choice('includeCamera','Show local camera captures','true',['true','false']),choice('defaultPhotoSort','Default date sorting','newest',['newest','oldest'])],
 camera:[text('captureTitle','Camera welcome heading','A little moment, captured.'),text('startLabel','Camera permission button','Enable camera'),text('permissionMessage','Camera permission message','Photos and videos save automatically to the Camera album in Pardanasheen on this device.'),text('emptyTitle','Empty camera roll title','Your moments start here.'),text('emptyMessage','Empty camera roll message','Take a photo and it will appear here and in Pardanasheen’s Camera album.'),text('savedMessage','Capture saved message','Automatically saved to Pardanasheen · Camera'),text('galleryLabel','Gallery destination label','Open in Pardanasheen ↗'),choice('savedDestination','Gallery destination','/app/adventure',['/app/adventure','/home']),choice('defaultCamera','Starting camera','rear',['front','rear']),choice('defaultGrid','Show camera grid initially','true',['true','false']),choice('videoEnabled','Allow video capture','true',['true','false'])],
 reasons:[text('notesLabel','Notes tab','Notes'),text('favoritesLabel','Favorites tab','Treasured'),text('letterLabel','Letter tab','Letter'),text('emptyMessage','Empty notes message','Your notes are waiting to be written.'),text('signature','Card signature','A little reason. A lot of love.'),choice('favoritesEnabled','Allow treasured notes','true',['true','false'])],
 hotline:[text('voicemailTitle','Voicemail heading','Voicemail'),text('voicemailMessage','Voicemail description','Little messages, whenever you need them.'),text('contactDescription','Contact description','Favourite contact · always worth a call'),text('endCallLabel','End call label','End call'),text('contactTab','Contact tab','Contact'),text('callTab','Call tab','Call'),text('voicemailTab','Voicemail tab','Voicemail')],
 vault:[text('lockedTitle','Locked screen title','The most precious things stay close.'),text('lockedMessage','Locked screen message','Our story. Protected by a memory only we share.'),text('question','Unlock question','What’s my favourite memory about us?'),text('answerPlaceholder','Answer placeholder','Write your memory…'),text('answerHint','Answer hint','Say it in your own words.'),text('unlockLabel','Unlock button','Unlock our story'),text('openingLabel','Opening message','Opening our story…'),text('doorLabel','Vault door label','OUR PRECIOUS STORY'),number('unlockDuration','Unlock animation milliseconds',900,100,2000)],
 'kiss-shop':[text('heroTitle','Shop heading','Made for you. Paid in kisses.'),text('heroMessage','Shop introduction','A cozy little shop for my favourite person.'),text('heroSignature','Shop signature','With love, always. ♡'),text('shelfTitle','Product collection heading','Pick a little happiness'),text('freeTitle','Free treats heading','Just because you’re you.'),text('freeMessage','Free treats description','Hugs, reassurance, and a listening ear. These never need to be earned.'),text('shopNote','Shop footer note','The prices are playful. The promises are real. No expiry dates. Just us.'),text('cartTitle','Gift bag title','Your little bag'),text('emptyMessage','Empty gift bag message','Your little bag is waiting.'),text('receiptTitle','Receipt heading','A promise, kept.'),text('receiptMessage','Receipt message','No expiry. Just us.'),text('addGiftLabel','Add gift button','Add to bag'),text('unavailableLabel','Unavailable gift label','Saved for later')],
 pieces:[text('puzzleTitle','Puzzle heading','We fit together.'),text('puzzleMessage','Puzzle introduction','Piece by piece, bring us together. Your surprise waits after every memory.'),text('rewardTitle','Reward heading','Come a little closer.'),text('rewardMessage','Reward message','One warm hug. And an “I love you” — said to you, in person.'),text('rewardNote','Reward note','No expiry date. Just show me this when we meet.'),text('giftLabel','Open reward button','Open my mysterious gift ♡')]
};
export const appSettingDefinitions=Object.fromEntries(authoredApps.map(app=>[app,[text('appTitle','App title',titles[app]),color('appAccent','App accent',app==='camera'?'#ffffff':app==='pieces'?'#c69b65':app==='vault'?'#d6ae77':'#d86f91'),color('appBackground','App background',app==='camera'?'#000000':app==='vault'?'#17110c':app==='pieces'?'#19150f':'#fbf5ef'),...own[app]]])) as Record<AuthoredApp,Setting[]>;
export function appFields(app:string,node:CMSNode):InspectorField[]{
 if(node.props.runtimePart==='level')return [{key:'title',label:'Level title',type:'text'},{key:'src',label:'Puzzle photo',type:'text'},{key:'alt',label:'Photo description',type:'text'},{key:'difficulty',label:'Difficulty',type:'select',options:['Easy','Moderate','Hard']},{key:'cols',label:'Piece columns',type:'number',min:2,max:8},{key:'rows',label:'Piece rows',type:'number',min:2,max:8},{key:'ratio',label:'Photo aspect ratio',type:'number',min:.3,max:3},{key:'note',label:'Level note',type:'textarea'}];
 return node.parentId===null?(appSettingDefinitions[app as AuthoredApp]??[]).map(setting=>setting.field):[];
}
export function getAppSettings(document:PageDocument|undefined|null,app:AuthoredApp):Record<string,CMSField>{const root=document?.nodes.find(node=>node.parentId===null);return Object.fromEntries(appSettingDefinitions[app].map(({field,value})=>[field.key,root?.props[field.key]??value]));}
export const defaultPuzzleLevels=[{title:'The little beginning',difficulty:'Easy',cols:3,rows:3,ratio:1599/899,photo:'/puzzles/level-one.jpg',note:'Nine pieces. One lovely beginning.'},{title:'A little closer',difficulty:'Moderate',cols:4,rows:4,ratio:780/1040,photo:'/puzzles/level-two.jpg',note:'Sixteen pieces, and a little more patience.'},{title:'Together, at last',difficulty:'Hard',cols:5,rows:4,ratio:2048/1152,photo:'/puzzles/our-moment.jpg',note:'Twenty pieces. Our final memory.'}];
export type PuzzleLevel=typeof defaultPuzzleLevels[number]&{id?:string};
export function getPuzzleLevels(document?:PageDocument|null):PuzzleLevel[]{if(!document)return defaultPuzzleLevels;const root=document.nodes.find(n=>n.props.runtimeApp==='pieces');if(!root)return defaultPuzzleLevels;const byId=new Map(document.nodes.map(n=>[n.id,n]));return root.children.map(id=>byId.get(id)!).filter(n=>n.visible&&n.props.runtimePart==='level').map(n=>({id:n.id,title:String(n.props.title),difficulty:String(n.props.difficulty),cols:Number(n.props.cols),rows:Number(n.props.rows),ratio:Number(n.props.ratio),photo:String(n.props.src),note:String(n.props.note??'')}));}
export function createRuntimeAppDocument(app:'camera'|'vault'|'pieces'):PageDocument{const root:CMSNode=createNode('section',app+'-settings');root.label=titles[app]+' · settings';root.props={runtimeApp:app,...Object.fromEntries(appSettingDefinitions[app].map(({field,value})=>[field.key,value]))};const doc:PageDocument={schemaVersion:2,nodes:[root],rootIds:[root.id]};if(app==='pieces')for(const [index,level] of defaultPuzzleLevels.entries()){const node:CMSNode=createNode('image','puzzle-level-'+(index+1),root.id);node.label='Level '+(index+1)+' · '+level.difficulty;node.props={runtimePart:'level',title:level.title,src:level.photo,alt:'Our memory',difficulty:level.difficulty,cols:level.cols,rows:level.rows,ratio:level.ratio,note:level.note};root.children.push(node.id);doc.nodes.push(node)}return doc;}
export function addAppItem(document:PageDocument,app:string,kind:string,id:string):{document:PageDocument;selectedId:string}{
 const kinds:Record<string,{parent:string;component:ComponentName;props?:Record<string,CMSField>}>={post:{parent:'movie-player',component:'movie-scene',props:{mediaKind:'image'}},reel:{parent:'movie-player',component:'movie-scene',props:{mediaKind:'video'}},photo:{parent:'photo-library',component:'image'},video:{parent:'photo-library',component:'video'},reason:{parent:'reason-deck',component:'reason'},gift:{parent:'product-collection',component:'kiss-gift'},voicemail:{parent:'birthday-message',component:'hotline-message'},level:{parent:'pieces',component:'image',props:{runtimePart:'level',title:'Another memory',src:'',difficulty:'Moderate',cols:4,rows:4,ratio:1,note:''}}};
 const allowed:Record<string,string[]>={movie:['post','reel'],adventure:['photo','video'],reasons:['reason'],'kiss-shop':['gift'],hotline:['voicemail'],pieces:['level']};if(!allowed[app]?.includes(kind))throw new Error('Unsupported app item');const definition=kinds[kind],next=structuredClone(document);let parent=next.nodes.find(n=>n.props.sectionKind===definition.parent||n.props.runtimeApp===definition.parent);if(!parent&&(app==='movie'||app==='adventure')){parent=createNode('section',id+'-collection');parent.label=app==='movie'?'Posts and reels':'Fit-check library';parent.props={...parent.props,padding:0,sectionKind:definition.parent,...(app==='adventure'?{title:'Pardanasheen',subtitle:'Every look, beautifully you.'}:{})};next.nodes.push(parent);next.rootIds.push(parent.id)}if(!parent)throw new Error('Choose or restore the app collection first');const node:CMSNode=createNode(definition.component,id,parent.id);node.label=kind.charAt(0).toUpperCase()+kind.slice(1);node.props={...node.props,...definition.props};parent.children.push(id);next.nodes.push(node);return {document:next,selectedId:id};
}
