import type {PageDocument, CMSNode} from './cms';
import type {AppDefinition} from './public-apps';
export const appComponents:Record<AppDefinition['kind'],string>={reasons:'reason',hotline:'hotline-message',adventure:'adventure-choice',movie:'movie-scene',shop:'kiss-gift',radio:'radio-track'};
export const componentMediaKind:Record<string,'image'|'video'|'audio'>={image:'image',video:'video',audio:'audio',reason:'image','hotline-message':'audio','movie-scene':'video','kiss-gift':'image','radio-track':'audio'};
export type AppItem={id:string;title:string;body:string;src:string;alt:string;category:string;price:string;invitation:string};
export function nodeToAppItem(n:CMSNode):AppItem {const p=n.props;const text=(k:string)=>typeof p[k]==='string'?String(p[k]):'';return {id:n.id,title:text('title'),body:text('body'),src:text('src'),alt:text('alt'),category:text('category'),price:text('price'),invitation:text('invitation')};}
// Tree order is the canonical order. Hidden ancestors hide all their descendants.
export function getAppItems(document:PageDocument,kind:AppDefinition['kind']):AppItem[]{const byId=new Map(document.nodes.map(n=>[n.id,n]));const items:AppItem[]=[];const visit=(id:string)=>{const n=byId.get(id);if(!n?.visible)return;if(n.component===appComponents[kind])items.push(nodeToAppItem(n));n.children.forEach(visit)};document.rootIds.forEach(visit);return items;}
const item=(id:string,title:string,body:string,extra:Partial<AppItem>={}):AppItem=>({id,title,body,src:'',alt:'',category:'',price:'1 kiss',invitation:'It’s a date. We’ll choose the details together.',...extra});
export const sampleAppItems:Record<AppDefinition['kind'],AppItem[]>={
 reasons:[item('smile','Your smile','The way you smile when you’re trying not to.',{category:'Little things'}),item('ordinary','Our ordinary days','How you make ordinary days worth remembering.',{category:'Together'}),item('home','You feel like home','Because being around you feels like coming home.',{category:'Together'})],
 hotline:[item('birthday','Birthday message','Happy birthday. I hope you always know how ridiculously loved you are.'),item('smile','For a little smile','This is your reminder that my favourite place is next to you.'),item('hug','A hug in words','Take your time. You are loved on the quiet days too.')],
 adventure:[item('cosy','Cosy evening','A favourite meal and a film together.',{invitation:'You, me, something delicious and nowhere else to be.'}),item('outside','Daytime adventure','A walk, a new café and a little exploring.',{invitation:'Let’s pick a free afternoon and get a little lost together.'}),item('surprise','A little surprise','Leave room for something unexpected.')],
 movie:[item('opening','Our little movie','A short story about us.'),item('ending','For your birthday','Here’s to all the memories still to come.')],
 shop:[item('movie-night','Movie night','You choose the movie.',{price:'1 kiss'}),item('hug','Long hug','Whenever you need one.',{price:'2 kisses'}),item('letter','Handwritten letter','An old-school promise on paper.',{price:'3 kisses'})],
 radio:[item('our-song','Our song','The one that makes me think of you.'),item('late-night','Late-night favourite','For the nights we don’t want to end.'),item('birthday','Birthday dedication','Today gets its own soundtrack.')]
};
export type AppProgress={version:1;favorites:string[];selection:string;receipts:Record<string,string>};
export const emptyAppProgress=():AppProgress=>({version:1,favorites:[],selection:'',receipts:{}});
export function parseAppProgress(raw:string|null,ids:string[]):AppProgress {try{if(raw&&raw.length>200000)return emptyAppProgress();const v=JSON.parse(raw??'null');if(!v||v.version!==1)return emptyAppProgress();const allowed=new Set(ids);const favorites=Array.isArray(v.favorites)?[...new Set(v.favorites.filter((x:unknown)=>typeof x==='string'&&allowed.has(x)))].slice(0,500) as string[]:[];const receiptEntries:[string,string][]=[];if(v.receipts&&typeof v.receipts==='object'&&!Array.isArray(v.receipts))for(const [key,value] of Object.entries(v.receipts))if(allowed.has(key)&&typeof value==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(value)&&Number.isFinite(Date.parse(value)))receiptEntries.push([key,value]);const receipts=Object.fromEntries(receiptEntries);return {version:1,favorites,selection:typeof v.selection==='string'&&allowed.has(v.selection)?v.selection:'',receipts};}catch{return emptyAppProgress();}}
export type AppAction={type:'favorite';id:string}|{type:'select';id:string}|{type:'redeem';id:string;at:string}|{type:'reset'};
export function reduceAppProgress(state:AppProgress,action:AppAction,ids:string[]):AppProgress {if(action.type==='reset')return emptyAppProgress();if(!ids.includes(action.id))return state;if(action.type==='favorite')return {...state,favorites:state.favorites.includes(action.id)?state.favorites.filter(x=>x!==action.id):[...state.favorites,action.id]};if(action.type==='select')return {...state,selection:action.id};if(Object.hasOwn(state.receipts,action.id)||!Number.isFinite(Date.parse(action.at)))return state;return {...state,receipts:{...state.receipts,[action.id]:action.at}};}
