import type {CMSField,CMSNode,PageDocument} from './cms';
import {archiveFields,componentFields,designFields,heartFields,sectionContentFields,type InspectorField} from './inspector-fields';
import {phoneFields} from './phone-home';
import {componentRegistry,type ComponentName} from './registry';
import {nodeMediaKind} from './app-content';
import {parsePageDocument,safeMediaUrl} from './validate';
export type InspectorGroup='content'|'appearance'|'behavior';
export type MediaKind='image'|'video'|'audio';
export type MediaTargetContract={key:string;label:string;kind:MediaKind};
export type InspectorCapability={field:InspectorField;group:InspectorGroup;storagePath:string;rendererBinding:string;responsive:boolean;resetPolicy:'component-default'|'delete-override';hasDefault:boolean;defaultValue?:CMSField;media?:MediaTargetContract;dependency?:string;};
type FieldOrigin='phone'|'heart'|'archive'|'section'|'component'|'design';
type Candidate={field:InspectorField;origin:FieldOrigin};
const responsiveKeys=new Set(['background','color','padding','margin','radius','opacity','size','weight','align','columns','gap','objectFit','focalX','focalY','displayHeight']);
const genericAppearanceKeys=new Set([...responsiveKeys,'fontFamily','lineHeight','letterSpacing','paddingTop','paddingRight','paddingBottom','paddingLeft','marginTop','marginRight','marginBottom','marginLeft','borderWidth','borderColor','shadow','maxWidth']);
const behaviorKeys=new Set(['loop','initialVolume','mediaKind','available','dateMode','digit','stationId','sceneId','pageSlug','placement','clockFormat','showWidget','showIntro','defaultPov','drifting','heartbeat','showMesh','showOutline','showCenter','showParticles','showFloatingHearts','showGrain','showVignette','driftSpeed','zoomSpeed','heartbeatDuration','visualEffects','transitionEnabled','transitionDuration','openInNewTab','alternateLayout','revealAnimation','hoverLift']);
const appearanceKeys=new Set(['dim','battery','iconBackground','transitionColor','customCss','offsetX','offsetY','offsetZ','cardScale','heartScale','mobileHeartScale','heartDepth','mobileHeartDepth','shells','initialZoom','openSpread','closeSpread','perspective','bg','bg2','bg3','mutedAlpha','softAlpha','lineAlpha','glassAlpha','borderAlpha','grainOpacity','vignetteStrength','outlineOpacity','centerOpacity','nodeWidth','mobileNodeWidth','nodeRadius','mobileNodeRadius','popupWidth','mobilePopupWidth','popupRadius','popupPadding','controlRadius','controlPadding','controlHeight','controlTextSize','povTop','mobilePovTop','hudInset','pink','rose','blush','violet','line','glass','border','glowOneColor','glowTwoColor','decorativeHeartColor','decorationOpacity','decorativeHeartSize','heroMinHeight','heroSideSpace','heroGap','titleItalic','titleTracking','mobileHeroMinHeight','mobileHeroTopPadding','gradientStart','gradientEnd','gradientAngle','imageSide','mobileImageHeight']);
const specializedPages=new Set(['reasons','adventure','movie','kiss-shop']);
const specializedBlocks=new Set(['reason','hotline-message','adventure-choice','movie-scene','kiss-gift','radio-track']);
const phoneDesignKeys:Record<string,Set<string>>={home:new Set(['color']),wallpaper:new Set(['background','opacity']),status:new Set(['background','color','padding','margin','opacity']),notifications:new Set(['background','color','padding','margin','opacity','radius']),notification:new Set(['background','color','padding','margin','opacity','radius']),widget:new Set(['background','color','padding','margin','opacity','radius']),launcher:new Set(['background','color','padding','margin','opacity']),'app-icon':new Set(['margin','opacity','radius']),navigation:new Set(['background','color','padding','margin','opacity'])};
const phoneComponentKeys:Record<string,Set<string>>={wallpaper:new Set(['src','alt','objectFit','focalX','focalY'])};
const phoneDefaults:Record<string,CMSField>={showWidget:'true',dim:.15,battery:100,clockFormat:'12'};
const archiveDefaults:Record<string,CMSField>={visualEffects:true,decorNote:'for you, always',glowOneColor:'#9d285e',glowTwoColor:'#6244a2',decorativeHeartColor:'#ff78b4',decorationOpacity:.5,decorativeHeartSize:360,transitionEnabled:true,transitionDuration:800,transitionColor:'#ff78b4',transitionText:'A little world, just for you',archiveBackLabel:'‹ In My Heart',heroMinHeight:620,heroSideSpace:35,heroGap:24,titleItalic:true,titleTracking:-4,mobileHeroMinHeight:740,mobileHeroTopPadding:280,gradientStart:'#3b1b34',gradientEnd:'#241530',gradientAngle:110,alternateLayout:true,revealAnimation:true,hoverLift:true,imageSide:'auto',mobileImageHeight:330};
function experience(document:PageDocument,pageSlug:string){return String(document.layout?.page??pageSlug)}
function groupFor(candidate:Candidate,node:CMSNode):InspectorGroup{const key=candidate.field.key;if(candidate.origin==='design'||genericAppearanceKeys.has(key)||appearanceKeys.has(key)||candidate.origin==='heart'&&String(node.props.heartPart)==='appearance')return 'appearance';if(behaviorKeys.has(key)||candidate.origin==='heart'&&String(node.props.heartPart)==='scene'&&['drifting','driftSpeed','zoomSpeed','heartbeat','heartbeatDuration','showMesh','showOutline','showCenter','showParticles','showFloatingHearts','showGrain','showVignette','defaultPov'].includes(key))return 'behavior';return 'content'}
function mediaTarget(node:CMSNode,key:string):MediaTargetContract|undefined{if(key==='poster')return {key,label:'Reel / video cover',kind:'image'};if(key==='avatar')return {key,label:'Profile photo',kind:'image'};if(key==='callerPhoto')return {key,label:'Caller photo',kind:'image'};if(key==='voiceSrc')return {key,label:'Voice note',kind:'audio'};if(key==='introSrc')return {key,label:'Recorded introduction',kind:'audio'};if(key!=='src')return undefined;const phone=String(node.props.phonePart??'');if(phone==='wallpaper')return {key,label:'Wallpaper',kind:'image'};if(phone==='app-icon')return {key,label:'Custom app icon',kind:'image'};const kind=nodeMediaKind(node);return kind?{key,label:kind==='image'?'Primary image':kind==='video'?'Primary video':'Primary audio',kind}:undefined}
function defaultFor(node:CMSNode,field:InspectorField,origin:FieldOrigin):{hasDefault:boolean;value?:CMSField}{if(origin==='phone'&&Object.hasOwn(phoneDefaults,field.key))return {hasDefault:true,value:phoneDefaults[field.key]};if(origin==='archive'&&Object.hasOwn(archiveDefaults,field.key))return {hasDefault:true,value:archiveDefaults[field.key]};const definition=Object.hasOwn(componentRegistry,node.component)?componentRegistry[node.component as ComponentName]:undefined;if((origin==='component'||origin==='design')&&definition&&Object.hasOwn(definition.defaults,field.key))return {hasDefault:true,value:(definition.defaults as Record<string,CMSField>)[field.key]};return {hasDefault:false}}
function rendererBinding(pageSlug:string,document:PageDocument,node:CMSNode,origin:FieldOrigin,field:InspectorField){const heart=String(node.props.heartPart??''),phone=String(node.props.phonePart??''),archive=String(node.props.archivePart??''),section=String(node.props.sectionKind??''),page=experience(document,pageSlug);if(origin==='heart'||heart)return `HeartPage.${heart||'node'}.${field.key}`;if(origin==='phone'||phone)return `PhoneHome.${phone||'node'}.${field.key}`;if(origin==='archive')return `MemoriesArchive.${archive||'node'}.${field.key}`;if(section)return `LayoutSection.${section}.${field.key}`;if(page==='reasons')return `AdoreJournal.${field.key}`;if(page==='adventure')return `PhotoLibrary.${field.key}`;if(page==='movie')return `Saragram.${field.key}`;if(page==='kiss-shop')return `KissShop.${field.key}`;if(origin==='design'||genericAppearanceKeys.has(field.key))return `CMSRenderer.style.${field.key}`;return `CMSRenderer.${node.component}.${field.key}`}
function componentFieldApplies(pageSlug:string,document:PageDocument,node:CMSNode,key:string){const phone=String(node.props.phonePart??''),heart=String(node.props.heartPart??''),page=experience(document,pageSlug);if(phone)return phoneComponentKeys[phone]?.has(key)??false;if(['image','video'].includes(node.component)&&['title','body','album','date'].includes(key)){if(page==='adventure')return true;if(heart==='memory')return ['title','body'].includes(key);return false}return true}
function candidateSupported(pageSlug:string,document:PageDocument,node:CMSNode,candidate:Candidate,group:InspectorGroup){const key=candidate.field.key,phone=String(node.props.phonePart??''),heart=String(node.props.heartPart??''),page=experience(document,pageSlug);if(candidate.origin==='component'&&!componentFieldApplies(pageSlug,document,node,key))return false;if(key==='digit'){const parent=node.parentId?document.nodes.find(n=>n.id===node.parentId):undefined;if(parent?.props.sectionKind!=='affection-keypad')return false}if(node.component==='movie-scene'&&node.props.mediaKind==='image'&&['poster','captions'].includes(key))return false;if(group!=='appearance')return true;if(candidate.origin==='heart'||candidate.origin==='archive')return true;if(candidate.origin==='phone')return true;if(phone){if(candidate.origin==='component')return phoneComponentKeys[phone]?.has(key)??false;return phoneDesignKeys[phone]?.has(key)??false}if(heart)return false;if(specializedPages.has(page))return false;if(specializedBlocks.has(node.component))return false;return true}
function collectCandidates(node:CMSNode):Candidate[]{const list:Candidate[]=[];const seen=new Set<string>();const add=(origin:FieldOrigin,fields:InspectorField[]|undefined)=>{for(const field of fields??[])if(!seen.has(field.key)){seen.add(field.key);list.push({field,origin})}};const phone=String(node.props.phonePart??''),heart=String(node.props.heartPart??''),archive=String(node.props.archivePart??''),section=String(node.props.sectionKind??'');if(phone)add('phone',phoneFields[phone]);if(heart)add('heart',heartFields[heart]);if(archive)add('archive',archiveFields[archive]);if(section)add('section',sectionContentFields[section]);add('component',componentFields[node.component]);add('design',designFields);return list}
export function getInspectorCapabilities(pageSlug:string,document:PageDocument,node:CMSNode):InspectorCapability[]{return collectCandidates(node).map(candidate=>({candidate,group:groupFor(candidate,node)})).filter(({candidate,group})=>candidateSupported(pageSlug,document,node,candidate,group)).map(({candidate,group})=>{const defaults=defaultFor(node,candidate.field,candidate.origin),media=mediaTarget(node,candidate.field.key);const dependency=candidate.field.key==='poster'?'Shown only for video / reel media.':candidate.field.key==='digit'?'Shown only inside the affection keypad.':undefined;return {field:candidate.field,group,storagePath:`pages.draft_document.nodes[${node.id}].props.${candidate.field.key}`,rendererBinding:rendererBinding(pageSlug,document,node,candidate.origin,candidate.field),responsive:group==='appearance'&&responsiveKeys.has(candidate.field.key),resetPolicy:defaults.hasDefault?'component-default':'delete-override',hasDefault:defaults.hasDefault,defaultValue:defaults.value,media,dependency}})}
export function supportsPageTheme(pageSlug:string,document:PageDocument){const page=experience(document,pageSlug);if(['memories-archive','reasons','adventure','movie','kiss-shop'].includes(page))return false;if(document.nodes.some(n=>n.parentId===null&&(n.props.phonePart==='home'||n.props.heartPart==='page')))return false;return true}
export function normalizeInspectorValue(field:InspectorField,raw:string):CMSField{if(field.type==='number'){let value=Number(raw);if(!Number.isFinite(value))throw new Error('Enter a valid number.');if(field.min!==undefined)value=Math.max(field.min,value);if(field.max!==undefined)value=Math.min(field.max,value);if(field.key==='columns')value=Math.round(value);return value}if(field.type==='select'&&field.options&&!field.options.includes(raw))throw new Error('Choose one of the available options.');if(field.type==='color'&&!/^(#[0-9a-fA-F]{3,8}|transparent)$/.test(raw))throw new Error('Use a hex colour such as #ff78b4 or transparent.');if(['pageSlug'].includes(field.key)&&raw&&!/^[a-z0-9][a-z0-9-]{0,99}$/.test(raw))throw new Error('Use a valid page slug.');if(field.key==='href'&&raw&&!(raw.startsWith('/')||raw.startsWith('#')||/^https:\/\//i.test(raw)))throw new Error('Use a site path such as /home, an anchor, or an HTTPS URL.');if(['src','poster','avatar','voiceSrc','callerPhoto','introSrc'].includes(field.key)&&!safeMediaUrl(raw))throw new Error('Use an HTTPS URL, a site path, or choose media from the library.');if(raw.length>20000)throw new Error('This value is too long.');return raw}
export function resetNodeProperty(document:PageDocument,nodeId:string,key:string,hasDefault=false,defaultValue?:CMSField):PageDocument{const next=structuredClone(document),node=next.nodes.find(n=>n.id===nodeId);if(!node)throw new Error('Layer not found');if(hasDefault)node.props[key]=defaultValue??null;else delete node.props[key];const baseKey=key.includes(':')?key.split(':')[1]:key;if(baseKey==='src'&&!key.includes(':')){node.props.mediaAssetId=null;node.props.mediaWidth=null;node.props.mediaHeight=null;node.props.variantWidths=''}return parsePageDocument(next)}
export function mediaDirectPatch(target:MediaTargetContract,value:string):Record<string,CMSField>{if(target.key==='src')return {src:value,mediaAssetId:null,mediaWidth:null,mediaHeight:null,variantWidths:''};return {[target.key]:value}}
export function mediaSelectionPatch(target:MediaTargetContract,media:{id:string;alt_text?:string|null;width?:number|null;height?:number|null;metadata?:{variants?:Array<string|number>}|null}):Record<string,CMSField>{const src='/media/'+media.id;if(target.key!=='src')return {[target.key]:src};return {src,mediaAssetId:media.id,alt:media.alt_text??'',mediaWidth:media.width??null,mediaHeight:media.height??null,variantWidths:(media.metadata?.variants??[]).join(',')}}

/** Reset one inspector group as a single undoable document change. */
export function resetInspectorGroup(document:PageDocument,nodeId:string,capabilities:InspectorCapability[],scope:'base'|'mobile'|'tablet'|'desktop'='base'):PageDocument {
 return capabilities.reduce((next,cap)=>{
  const responsive=cap.group==='appearance'&&scope!=='base';
  if(responsive&&!cap.responsive)return next;
  return resetNodeProperty(next,nodeId,(responsive?scope+':':'')+cap.field.key,!responsive&&cap.hasDefault,cap.defaultValue);
 },document);
}
