"use client";
import {useState} from "react";
const initialNodes=["Header","Birthday Message","App Grid","Notifications"];
export default function Editor(){
 const [selected,setSelected]=useState("App Grid"); const [nodes,setNodes]=useState(initialNodes); const [saved,setSaved]=useState(true);
 return <main className="flex h-screen flex-col overflow-hidden bg-[#f4f2f0]"><header className="flex h-14 items-center justify-between border-b bg-white px-4"><div className="flex items-center gap-3"><a href="/" className="text-sm">←</a><strong>Home</strong><span className="text-xs text-[#81736d]">{saved?"Saved":"Unsaved changes"}</span></div><div className="flex gap-2"><button onClick={()=>setSaved(true)} className="rounded-lg border px-3 py-1.5 text-sm">Save</button><button className="rounded-lg bg-[#d86f91] px-3 py-1.5 text-sm font-semibold text-white">Publish</button></div></header>
 <div className="grid min-h-0 flex-1 grid-cols-[240px_1fr_280px]"><aside className="overflow-auto border-r bg-white p-4"><h2 className="text-xs font-semibold uppercase tracking-wide text-[#81736d]">Navigator</h2><div className="mt-3 space-y-1">{nodes.map(n=><button key={n} onClick={()=>{setSelected(n);setSaved(false)}} className={`w-full rounded-lg px-3 py-2 text-left text-sm ${selected===n?"bg-[#f7e5eb]":""}`}>{n}</button>)}</div><button onClick={()=>setNodes([...nodes,"New Section"])} className="mt-4 w-full rounded-lg border px-3 py-2 text-sm">+ Add section</button></aside>
 <section className="overflow-auto p-6"><div className="mx-auto min-h-[700px] max-w-[430px] rounded-[32px] border-8 border-[#2f2b2a] bg-[var(--w-bg)] p-5 shadow-xl"><p className="text-xs text-[var(--w-muted)]">Live canvas · mobile</p><h1 className="mt-4 text-2xl font-semibold">Happy birthday, favourite person. 💗</h1><div className="mt-5 grid grid-cols-2 gap-3">{["💗 Reasons","☎️ Hotline","🧭 Adventure","🎬 Movie","💋 Kiss Shop","📻 Radio"].map(x=><div key={x} className="rounded-2xl border bg-white p-4 text-sm">{x}</div>)}</div></div></section>
 <aside className="overflow-auto border-l bg-white p-4"><h2 className="text-xs font-semibold uppercase tracking-wide text-[#81736d]">Inspector</h2><p className="mt-4 text-sm font-medium">{selected}</p><label className="mt-5 block text-xs text-[#81736d]">Background</label><input type="color" defaultValue="#fbf5ef" className="mt-2 h-10 w-full"/><label className="mt-5 block text-xs text-[#81736d]">Corner radius</label><input type="range" min="0" max="40" defaultValue="22" className="mt-2 w-full"/><label className="mt-5 block text-xs text-[#81736d]">Visibility</label><select className="mt-2 w-full rounded-lg border p-2 text-sm"><option>Visible</option><option>Hidden</option></select></aside>
 </div></main>;
}