package com.wiffeyyyy.hotline;
import android.Manifest;
import android.app.*;
import android.os.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.net.Uri;
import android.provider.Settings;
import android.webkit.*;
import android.widget.*;
import android.view.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.media.AudioManager;
import org.json.JSONObject;
import java.util.ArrayList;

/** Native receiver UI. A restricted, hidden WebView supplies the existing WebRTC transport. */
public class MainActivity extends Activity {
 WebView web; LinearLayout page,content,tabs; TextView status,callStatus; Button muteButton,speakerButton,holdButton;
 String expectedCall="",currentCall="",screen="contact"; boolean pendingAnswer=false,speaker=false,destroyed=false;
 final int BG=0xff10141d,FG=0xfff6f7fb,SECONDARY=0xffa5afc1,GREEN=0xff34c759;
 @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);setup();requestPermissions();if(getIntent().getBooleanExtra("answer",false))checkAndAnswer(getIntent().getStringExtra("callId"));else if(checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)==PackageManager.PERMISSION_GRANTED||Build.VERSION.SDK_INT<33)arm();}
 int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);}
 TextView text(String value,int size,int color){TextView view=new TextView(this);view.setText(value);view.setTextSize(size);view.setTextColor(color);view.setGravity(Gravity.CENTER);view.setPadding(0,dp(10),0,dp(10));return view;}
 Button action(String label,int color,Runnable run){Button button=new Button(this);button.setText(label);button.setTextColor(Color.WHITE);button.setAllCaps(false);button.setTextSize(17);GradientDrawable bg=new GradientDrawable();bg.setColor(color);bg.setCornerRadius(dp(24));button.setBackground(bg);LinearLayout.LayoutParams params=new LinearLayout.LayoutParams(-1,dp(52));params.setMargins(dp(8),dp(8),dp(8),dp(8));button.setLayoutParams(params);button.setOnClickListener(v->run.run());return button;}
 void setup(){page=new LinearLayout(this);page.setOrientation(1);page.setBackgroundColor(BG);page.setPadding(dp(20),dp(8),dp(20),dp(12));content=new LinearLayout(this);content.setOrientation(1);content.setGravity(Gravity.CENTER);page.addView(content,new LinearLayout.LayoutParams(-1,0,1));tabs=new LinearLayout(this);for(String tab:new String[]{"Recents","Contact","Settings"}){Button button=new Button(this);button.setAllCaps(false);button.setText(tab);button.setTextColor(FG);button.setBackgroundColor(BG);button.setOnClickListener(v->{screen=tab.toLowerCase();render();});tabs.addView(button,new LinearLayout.LayoutParams(0,dp(55),1));}page.addView(tabs);if(web==null)createTransport();else if(web.getParent()!=null)((android.view.ViewGroup)web.getParent()).removeView(web);page.addView(web,new LinearLayout.LayoutParams(1,1));setContentView(page);render();}
 void avatar(){TextView avatar=text("S",64,FG);GradientDrawable bg=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{0xff425478,0xff232d45});bg.setShape(GradientDrawable.OVAL);avatar.setBackground(bg);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(130),dp(130));p.gravity=Gravity.CENTER;p.setMargins(0,dp(32),0,dp(24));content.addView(avatar,p);}
 void render(){content.removeAllViews();status=null;callStatus=null;tabs.setVisibility(screen.equals("call")?View.GONE:View.VISIBLE);
 if(screen.equals("call")){avatar();TextView name=text("Sara",34,FG);name.setTypeface(null,Typeface.BOLD);content.addView(name);callStatus=text("Connecting…",17,SECONDARY);content.addView(callStatus);LinearLayout controls=new LinearLayout(this);muteButton=action("♩\nMute",0xff2c3548,()->sendAction("mute"));controls.addView(muteButton,new LinearLayout.LayoutParams(0,dp(100),1));holdButton=action("Hold",0xff2c3548,()->sendAction("hold"));controls.addView(holdButton,new LinearLayout.LayoutParams(0,dp(100),1));speakerButton=action(speaker?"Speaker on":"Speaker",0xff2c3548,()->{speaker=!speaker;AudioManager manager=(AudioManager)getSystemService(AUDIO_SERVICE);manager.setMode(AudioManager.MODE_IN_COMMUNICATION);routeSpeaker(manager,speaker);speakerButton.setText(speaker?"Speaker on":"Speaker");});controls.addView(speakerButton,new LinearLayout.LayoutParams(0,dp(100),1));content.addView(controls);content.addView(action("End call",0xffe74b54,()->{sendAction("end");screen="contact";resetAudio();render();}));return;}
 if(screen.equals("settings")){content.addView(text("Settings",30,FG));status=text("Your private receiver is configured",15,SECONDARY);content.addView(status);content.addView(action("Enable incoming calls",GREEN,this::arm));content.addView(action("Battery settings",0xff2c3548,()->startActivity(new Intent(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS,Uri.parse("package:"+getPackageName())))));content.addView(action("Incoming call notifications",0xff2c3548,()->{if(Build.VERSION.SDK_INT>=34)startActivity(new Intent(Settings.ACTION_MANAGE_APP_USE_FULL_SCREEN_INTENT,Uri.parse("package:"+getPackageName())));else startActivity(new Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(Settings.EXTRA_APP_PACKAGE,getPackageName()));}));content.addView(action("Stop receiving",0xff763c47,()->{Config.prefs(this).edit().putBoolean("armed",false).apply();stopService(new Intent(this,HotlineService.class));status.setText("Incoming calls disabled");}));content.addView(text("Allow notifications and set battery use to Unrestricted for background reception.",14,SECONDARY));return;}
 if(screen.equals("recents")){content.addView(text("Recents",32,FG));content.addView(text(Config.prefs(this).getString("lastCall","").isEmpty()?"No calls yet":"Sara · Incoming call",21,FG));content.addView(text(Config.prefs(this).getString("lastCall","Your calls will appear here"),15,SECONDARY));return;}
 content.addView(text("Hotline",22,SECONDARY));avatar();TextView name=text("Sara",36,FG);name.setTypeface(null,Typeface.BOLD);content.addView(name);content.addView(text("♡ Your favourite contact",17,SECONDARY));status=text(Config.prefs(this).getBoolean("armed",false)?"Ready for incoming calls":"Incoming calls are disabled",15,SECONDARY);content.addView(status);content.addView(action("Receive calls",GREEN,this::arm));content.addView(text("This is your private receiver. She calls from Wiffeyyyy OS.",14,SECONDARY));}
 void requestPermissions(){ArrayList<String> permissions=new ArrayList<>();if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)permissions.add(Manifest.permission.RECORD_AUDIO);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)permissions.add(Manifest.permission.POST_NOTIFICATIONS);if(!permissions.isEmpty())requestPermissions(permissions.toArray(new String[0]),7);}
 @Override public void onRequestPermissionsResult(int request,String[] permissions,int[] results){super.onRequestPermissionsResult(request,permissions,results);if(request==7){arm();if(pendingAnswer&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED)openCall(true);}}
 void arm(){if(Config.key(this).isEmpty()){if(status!=null)status.setText("Install your personal configured APK");return;}if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED){if(status!=null)status.setText("Allow notifications to receive calls");return;}Config.prefs(this).edit().putBoolean("armed",true).apply();startForegroundService(new Intent(this,HotlineService.class));if(status!=null)status.setText("Ready for incoming calls");}
 @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);if(intent.getBooleanExtra("answer",false))checkAndAnswer(intent.getStringExtra("callId"));}
 void checkAndAnswer(String id){new Thread(()->{try{JSONObject call=Config.exchange(this,"status",new JSONObject());boolean matches=id!=null&&id.equals(call.optString("callId"))&&"ringing".equals(call.optString("state"));runOnUiThread(()->{if(destroyed)return;getSystemService(NotificationManager.class).cancel(HotlineService.INCOMING);if(matches){expectedCall=id;currentCall=id;pendingAnswer=true;openCall(true);}else if(status!=null)status.setText("That call has ended");});}catch(Exception e){runOnUiThread(()->{if(status!=null)status.setText(e.getMessage());});}}).start();}
 void openCall(boolean autoAnswer){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){pendingAnswer=autoAnswer;requestPermissions();return;}arm();startForegroundService(new Intent(this,HotlineService.class).setAction(HotlineService.MIC));getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);if(Build.VERSION.SDK_INT>=27){setShowWhenLocked(true);setTurnScreenOn(true);}screen="call";render();if(autoAnswer)pendingAnswer=true;sendAction("answer");}
 void sendAction(String type){if(web==null)return;try{JSONObject action=new JSONObject().put("type",type).put("callId",currentCall);web.evaluateJavascript("window.dispatchEvent(new CustomEvent('wiffey:call-action',{detail:"+action.toString()+"}))",null);}catch(Exception ignored){}}
 void createTransport(){web=new WebView(this);web.setBackgroundColor(BG);web.getSettings().setJavaScriptEnabled(true);web.getSettings().setDomStorageEnabled(true);web.getSettings().setMediaPlaybackRequiresUserGesture(false);web.getSettings().setAllowFileAccess(false);web.getSettings().setAllowContentAccess(false);web.getSettings().setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);web.addJavascriptInterface(new Object(){@JavascriptInterface public void update(String raw){try{JSONObject call=new JSONObject(raw);runOnUiThread(()->applyCallState(call));}catch(Exception ignored){}}},"HotlineNative");
 web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView view,WebResourceRequest request){return !Config.ORIGIN.equals(request.getUrl().getScheme()+"://"+request.getUrl().getHost())||!"/hotline/receive".equals(request.getUrl().getPath());}@Override public void onPageFinished(WebView view,String url){if(!url.startsWith(Config.ORIGIN+"/hotline/receive"))return;view.evaluateJavascript("if(!window.hotlineNativeInstalled){window.hotlineNativeInstalled=true;window.addEventListener('wiffey:call-state',e=>HotlineNative.update(JSON.stringify(e.detail)));setInterval(()=>window.dispatchEvent(new CustomEvent('wiffey:call-action',{detail:{type:'status'}})),1000)}",null);}});
 web.setWebChromeClient(new WebChromeClient(){@Override public void onPermissionRequest(PermissionRequest request){runOnUiThread(()->{if(Config.ORIGIN.equals(request.getOrigin().toString().replaceAll("/$",""))&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED){ArrayList<String> granted=new ArrayList<>();for(String resource:request.getResources())if(PermissionRequest.RESOURCE_AUDIO_CAPTURE.equals(resource))granted.add(resource);if(!granted.isEmpty())request.grant(granted.toArray(new String[0]));else request.deny();}else request.deny();});}});web.loadUrl(Config.ORIGIN+"/hotline/receive#key="+Config.key(this));}
 void applyCallState(JSONObject state){if(destroyed)return;String id=state.optString("callId"),phase=state.optString("state");if(pendingAnswer&&expectedCall.equals(id)&&phase.equals("ringing")){pendingAnswer=false;sendAction("answer");}if(screen.equals("call")){if(state.optBoolean("connected")){int seconds=state.optInt("seconds");if(callStatus!=null)callStatus.setText(String.format(java.util.Locale.US,"%d:%02d",seconds/60,seconds%60));}else if(callStatus!=null)callStatus.setText(state.optString("error").isEmpty()?"Connecting…":state.optString("error"));if(muteButton!=null){muteButton.setText(state.optBoolean("muted")?"Unmute":"Mute");muteButton.setEnabled(state.optBoolean("connected"));}if(holdButton!=null){holdButton.setText(state.optBoolean("held")?"Resume":"Hold");holdButton.setEnabled(state.optBoolean("connected"));}if(state.optBoolean("held")&&callStatus!=null)callStatus.setText("On hold · "+String.format(java.util.Locale.US,"%d:%02d",state.optInt("seconds")/60,state.optInt("seconds")%60));if(state.optBoolean("playRequired"))sendAction("audio");if((phase.equals("ended")&&id.equals(currentCall))||(phase.equals("idle")&&!pendingAnswer)){pendingAnswer=false;screen="contact";resetAudio();render();}}}
 void routeSpeaker(AudioManager manager,boolean enabled){if(Build.VERSION.SDK_INT>=31){if(!enabled){manager.clearCommunicationDevice();return;}for(android.media.AudioDeviceInfo device:manager.getAvailableCommunicationDevices())if(device.getType()==android.media.AudioDeviceInfo.TYPE_BUILTIN_SPEAKER){if(!manager.setCommunicationDevice(device)){speaker=false;if(speakerButton!=null)speakerButton.setText("Speaker unavailable");}return;}}else manager.setSpeakerphoneOn(enabled);}
 void resetAudio(){speaker=false;AudioManager manager=(AudioManager)getSystemService(AUDIO_SERVICE);routeSpeaker(manager,false);manager.setMode(AudioManager.MODE_NORMAL);getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);if(Build.VERSION.SDK_INT>=27)setShowWhenLocked(false);}
 @Override public void onBackPressed(){if(screen.equals("call")||screen.equals("contact")){moveTaskToBack(true);return;}screen="contact";render();}
 @Override protected void onDestroy(){destroyed=true;resetAudio();if(web!=null){web.removeJavascriptInterface("HotlineNative");web.destroy();}super.onDestroy();}
}
