package com.wiffeyyyy.hotline;
import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.net.Uri;import android.provider.Settings;import android.webkit.*;import android.widget.*;import java.util.ArrayList;
public class MainActivity extends Activity {
 String expectedCall="";
 WebView web;TextView status;boolean answer=false;
 @Override public void onCreate(Bundle state){super.onCreate(state);requestPermissions();if(getIntent().getBooleanExtra("answer",false)&&!Config.key(this).isEmpty())checkAndAnswer(getIntent().getStringExtra("callId"));else setup();}
 void requestPermissions(){ArrayList<String> permissions=new ArrayList<>();if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)permissions.add(Manifest.permission.RECORD_AUDIO);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)permissions.add(Manifest.permission.POST_NOTIFICATIONS);if(!permissions.isEmpty())requestPermissions(permissions.toArray(new String[0]),7);}
 void setup(){LinearLayout layout=new LinearLayout(this);layout.setOrientation(1);layout.setPadding(28,48,28,20);layout.setBackgroundColor(0xfffff5f7);TextView heading=new TextView(this);heading.setText("Hotline Receiver ♡");heading.setTextSize(28);layout.addView(heading);TextView intro=new TextView(this);intro.setText("Paste your private receiver link from Admin → Hotline. Enable reception before leaving the app. Calls ring through the ongoing receiver service; keep notifications enabled.");intro.setPadding(0,20,0,18);layout.addView(intro);EditText link=new EditText(this);link.setHint("Private receiver link");link.setSingleLine(true);link.setInputType(129);layout.addView(link);status=new TextView(this);status.setPadding(0,16,0,16);status.setText(Config.key(this).isEmpty()?"Not paired":"Paired. Enable receiver to stay available.");layout.addView(status);
 button(layout,"Pair & enable receiver",()->{String key=Config.parseKey(link.getText().toString());if(key.isEmpty()){status.setText("Paste a valid private receiver link.");return;}status.setText("Checking receiver link…");new Thread(()->{String previous=Config.key(this);Config.prefs(this).edit().putString("key",key).apply();try{Config.exchange(this,"status",new org.json.JSONObject());runOnUiThread(()->{link.setText("");arm();});}catch(Exception e){Config.prefs(this).edit().putString("key",previous).apply();runOnUiThread(()->status.setText(e.getMessage()));}}).start();});
 button(layout,"Enable receiver",this::arm);button(layout,"Open call screen",()->openCall(false));button(layout,"Battery settings",()->startActivity(new Intent(Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS)));button(layout,"Incoming-call display settings",()->{if(Build.VERSION.SDK_INT>=34)startActivity(new Intent(Settings.ACTION_MANAGE_APP_USE_FULL_SCREEN_INTENT,Uri.parse("package:"+getPackageName())));else startActivity(new Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(Settings.EXTRA_APP_PACKAGE,getPackageName()));});button(layout,"Stop receiving",()->{Config.prefs(this).edit().putBoolean("armed",false).apply();stopService(new Intent(this,HotlineService.class));status.setText("Receiver stopped.");});TextView note=new TextView(this);note.setText("For faster alerts with the screen off, set this app’s battery use to Unrestricted. Continuous reception uses battery and internet. Android force-stop or restricted battery use can interrupt alerts. Reopen and enable reception after restarting your phone.");note.setPadding(0,20,0,0);layout.addView(note);ScrollView scroll=new ScrollView(this);scroll.addView(layout);setContentView(scroll);}
 void button(LinearLayout layout,String text,Runnable action){Button button=new Button(this);button.setText(text);button.setOnClickListener(v->action.run());layout.addView(button);}
 void arm(){if(Config.key(this).isEmpty()){status.setText("Pair your private receiver link first.");return;}if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED){status.setText("Allow notifications to receive incoming-call alerts.");requestPermissions();return;}Config.prefs(this).edit().putBoolean("armed",true).apply();startForegroundService(new Intent(this,HotlineService.class));status.setText("Receiver enabled. Ongoing notification shows connection status.");}
 @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);if(intent.getBooleanExtra("answer",false))checkAndAnswer(intent.getStringExtra("callId"));}
 void checkAndAnswer(String id){setup();new Thread(()->{try{org.json.JSONObject call=Config.exchange(this,"status",new org.json.JSONObject());boolean matches=id!=null&&id.equals(call.optString("callId"))&&"ringing".equals(call.optString("state"));runOnUiThread(()->{getSystemService(NotificationManager.class).cancel(HotlineService.INCOMING);if(matches){expectedCall=id;openCall(true);}else status.setText("That call has ended. Receiver stays available.");});}catch(Exception e){runOnUiThread(()->status.setText(e.getMessage()));}}).start();}
 void openCall(boolean autoAnswer){if(Config.key(this).isEmpty()){setup();return;}if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions();if(status!=null)status.setText("Allow microphone access, then open the call screen.");return;}answer=autoAnswer;if(Config.prefs(this).getBoolean("armed",false))startForegroundService(new Intent(this,HotlineService.class).setAction(HotlineService.MIC));getWindow().addFlags(android.view.WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);if(web!=null)web.destroy();LinearLayout shell=new LinearLayout(this);shell.setOrientation(1);button(shell,"Receiver settings",()->{if(web!=null){web.destroy();web=null;}setup();});web=new WebView(this);web.getSettings().setJavaScriptEnabled(true);web.getSettings().setDomStorageEnabled(true);web.getSettings().setMediaPlaybackRequiresUserGesture(false);web.getSettings().setAllowFileAccess(false);web.getSettings().setAllowContentAccess(false);web.getSettings().setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);
 web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView view,WebResourceRequest request){return !Config.ORIGIN.equals(request.getUrl().getScheme()+"://"+request.getUrl().getHost())||!"/hotline/receive".equals(request.getUrl().getPath());}@Override public void onPageFinished(WebView view,String url){if(answer&&url.startsWith(Config.ORIGIN+"/hotline/receive")){answer=false;view.evaluateJavascript("(()=>{const expected="+org.json.JSONObject.quote(expectedCall)+";let n=0;const t=setInterval(()=>{const b=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='Answer'&&b.dataset.callId===expected&&!b.disabled);if(b){clearInterval(t);b.click()}else if(++n>40)clearInterval(t)},150)})()",null);}}});
 web.setWebChromeClient(new WebChromeClient(){@Override public void onPermissionRequest(PermissionRequest request){runOnUiThread(()->{if(Config.ORIGIN.equals(request.getOrigin().toString().replaceAll("/$",""))&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED){ArrayList<String> granted=new ArrayList<>();for(String resource:request.getResources())if(PermissionRequest.RESOURCE_AUDIO_CAPTURE.equals(resource))granted.add(resource);if(!granted.isEmpty())request.grant(granted.toArray(new String[0]));else request.deny();}else request.deny();});}});shell.addView(web,new LinearLayout.LayoutParams(-1,0,1));setContentView(shell);web.loadUrl(Config.ORIGIN+"/hotline/receive#key="+Config.key(this));}
 @Override protected void onDestroy(){if(web!=null)web.destroy();super.onDestroy();}
}
