"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {emptyAppProgress,parseAppProgress,reduceAppProgress,sampleAppItems,type AppAction,type AppDefinition,type AppItem} from '@wiffeyyyy/content';
import {MediaPlayer} from './media-player';
function itemStyle(item:AppItem):React.CSSProperties {const p=item.design??{};return {background:p.background as string|undefined,color:p.color as string|undefined,padding:p.padding as number|undefined,margin:p.margin as number|undefined,borderRadius:p.radius as number|undefined,opacity:p.opacity as number|undefined}}
const card='rounded-3xl border border-[var(--w-border)] bg-[var(--w-surface)] p-6';
const button='min-h-11 rounded-2xl border border-[var(--w-border)] px-4 py-3 text-sm font-semibold disabled:opacity-50';
const primary=button+' bg-[#a9476b] text-white';
const muted='text-sm leading-7 text-[var(--w-muted)]';
function Media({item,kind}:{item:AppItem;kind:'audio'|'video'}){
 if(!item.src)return <p className={muted}>The {kind==='audio'?'recording':'video'} hasn’t been added yet. You can read the message below.</p>;
 return <MediaPlayer identity={kind+':'+item.id} src={item.src} kind={kind} title={item.alt||item.title} captions={item.captions} className={kind==='audio'?'w-full':'aspect-video w-full rounded-2xl bg-black'}/>;
}
function Photo({item}:{item:AppItem}){const [failed,setFailed]=useState(false);return item.src&&!failed?<img src={item.src} alt={item.alt} loading="lazy" decoding="async" onError={()=>setFailed(true)} className="mb-4 max-h-80 w-full rounded-2xl object-contain"/>:null;}
export function AppExperience({app,items:provided,embedded=false}:{app:AppDefinition;items?:AppItem[];embedded?:boolean}){
 const items=provided??sampleAppItems[app.kind];
 const ids=items.map(x=>x.id),signature=JSON.stringify(ids),storageKey='wiffeyyyy:app:v1:'+app.slug;
 const [progress,setProgress]=useState(emptyAppProgress),[ready,setReady]=useState(false),[storageWarning,setStorageWarning]=useState(false);
 const progressRef=useRef(progress);
 const [category,setCategory]=useState('All'),[onlyFavorites,setOnlyFavorites]=useState(false),[answered,setAnswered]=useState(false),[pendingGift,setPendingGift]=useState<AppItem|null>(null);
 const giftDialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{let restored=emptyAppProgress();try{restored=parseAppProgress(localStorage.getItem(storageKey),JSON.parse(signature))}catch{setStorageWarning(true)}progressRef.current=restored;setProgress(restored);setReady(true);const sync=(e:StorageEvent)=>{if(e.key===storageKey||e.key===null){const next=parseAppProgress(e.newValue,JSON.parse(signature));progressRef.current=next;setProgress(next)}};window.addEventListener('storage',sync);return()=>window.removeEventListener('storage',sync)},[storageKey,signature]);
 const dispatch=useCallback((action:AppAction)=>{const next=reduceAppProgress(progressRef.current,action,JSON.parse(signature));progressRef.current=next;setProgress(next);try{localStorage.setItem(storageKey,JSON.stringify(next))}catch{setStorageWarning(true)}},[storageKey,signature]);
 useEffect(()=>{if(pendingGift)giftDialog.current?.showModal();else giftDialog.current?.close()},[pendingGift]);
 const receipt=(id:string)=>Object.hasOwn(progress.receipts,id)?progress.receipts[id]:undefined;
 const selected=items.find(x=>x.id===progress.selection)??items[0];
 const select=(id:string)=>dispatch({type:'select',id});
 let content:React.ReactNode;
 if(!items.length)content=<div className={card}><h2 className="text-xl">Something lovely is on its way</h2><p className={muted}>There’s no content in this app yet. Come back soon.</p><a href="/home" className={button+' mt-4 inline-flex'}>Back to Home</a></div>;
 else if(app.kind==='reasons'){
  const categories=['All',...new Set(items.map(x=>x.category).filter(Boolean))];
  const filtered=items.filter(x=>(category==='All'||x.category===category)&&(!onlyFavorites||progress.favorites.includes(x.id)));
  content=<div className="space-y-5"><p className={muted}>Little things, big feelings. Keep your favourites close.</p><div className="flex flex-wrap gap-2" aria-label="Reason filters">{categories.map(x=><button className={button} key={x} aria-pressed={category===x} onClick={()=>setCategory(x)}>{x}</button>)}<button className={button} aria-pressed={onlyFavorites} onClick={()=>setOnlyFavorites(x=>!x)}>Favourites ({progress.favorites.length})</button></div><p role="status" className={muted}>{filtered.length} reasons</p>{filtered.map(x=><article className={card} key={x.id} style={itemStyle(x)}><Photo item={x}/><p className="text-xs uppercase tracking-widest text-[#9c4966]">{x.category||'A little reason'}</p><h2 className="my-3 font-serif text-2xl">{x.title}</h2><p className="whitespace-pre-line leading-8">{x.body}</p><button className={button+' mt-5'} disabled={!ready} aria-pressed={progress.favorites.includes(x.id)} onClick={()=>dispatch({type:'favorite',id:x.id})}>{progress.favorites.includes(x.id)?'♥ Saved':'♡ Save favourite'}<span className="sr-only">: {x.title}</span></button></article>)}{!filtered.length&&<p className={card}>No reasons in this view yet. Try another filter or save a favourite.</p>}</div>;
 }else if(app.kind==='hotline')content=<div className="space-y-5"><section className={card+' text-center'}><p className="text-5xl" aria-hidden="true">☎️</p><h2 className="mt-4 font-serif text-3xl">{answered?'Your birthday line':'Incoming birthday call'}</h2><p className={muted}>{answered?'Pick a message below. Stay as long as you like.':'A little message, just for you.'}</p><button className={primary+' mt-5'} disabled={!ready} onClick={()=>{setAnswered(x=>!x);if(!answered)select(selected.id)}}>{answered?'End call':'Answer'}</button></section>{answered&&<><div className="grid grid-cols-3 gap-3" aria-label="Hotline keypad">{items.map((x,i)=><button key={x.id} className={button+' bg-[var(--w-surface)]'} aria-pressed={selected.id===x.id} onClick={()=>select(x.id)}><span className="block text-2xl">{i+1}</span><span className="block text-xs">{x.title}</span></button>)}</div><article className={card} style={itemStyle(selected)}><h2 className="mb-4 text-xl font-semibold">{selected.title}</h2><Media key={selected.id+selected.src} item={selected} kind="audio"/><h3 className="mt-5 text-sm font-semibold">Text version</h3><p className={muted+' whitespace-pre-line'}>{selected.body}</p></article></>}{!answered&&<details className={card}><summary className="cursor-pointer">Read the birthday message</summary><p className={muted+' mt-4 whitespace-pre-line'}>{items[0].body}</p></details>}</div>;
 else if(app.kind==='adventure')content=<div className="space-y-4"><p className={muted}>Choose the kind of day you’d love. Your invitation is waiting.</p>{items.map(x=><button key={x.id} style={itemStyle(x)} disabled={!ready} onClick={()=>select(x.id)} aria-pressed={progress.selection===x.id} className={card+' w-full text-left '+(progress.selection===x.id?'ring-2 ring-[#a9476b]':'')}><h2 className="font-serif text-2xl">{x.title}</h2><p className={muted}>{x.body}</p><span className="mt-3 block text-sm text-[#9c4966]">{progress.selection===x.id?'Chosen ♥':'Choose this adventure →'}</span></button>)}{progress.selection&&<section aria-live="polite" className={card+' bg-[#f4dce4]'}><p className="text-xs uppercase tracking-widest">Your invitation</p><h2 className="mt-3 font-serif text-2xl">{selected.title}</h2><p className="mt-3 whitespace-pre-line leading-7">{selected.invitation||selected.body}</p><p className={muted+' mt-4'}>Saved on this device. You can change your choice any time.</p></section>}</div>;
 else if(app.kind==='movie')content=<div className="space-y-5"><article className={card} style={itemStyle(selected)}><p className="mb-3 text-xs uppercase tracking-widest">Scene {items.indexOf(selected)+1} of {items.length}</p><h2 className="mb-4 font-serif text-3xl">{selected.title}</h2><Media key={selected.id+selected.src} item={selected} kind="video"/><p className={muted+' mt-5 whitespace-pre-line'}>{selected.body}</p><div className="mt-5 flex justify-between gap-3"><button className={button} disabled={!ready||items.indexOf(selected)===0} onClick={()=>select(items[items.indexOf(selected)-1].id)}>Previous scene</button><button className={button} disabled={!ready||items.indexOf(selected)===items.length-1} onClick={()=>select(items[items.indexOf(selected)+1].id)}>Next scene</button></div></article><nav aria-label="Movie chapters" className="grid gap-2">{items.map((x,i)=><button className={button+' text-left'} key={x.id} disabled={!ready} aria-current={selected.id===x.id?'step':undefined} onClick={()=>select(x.id)}>{i+1}. {x.title}</button>)}</nav></div>;
 else if(app.kind==='shop')content=<div className="space-y-5"><p className={muted}>Everything costs a kiss. These are little promises, saved just for you.</p>{items.map(x=><article className={card} key={x.id} style={itemStyle(x)}><Photo item={x}/><span className="text-xs font-semibold text-[#9c4966]">{x.price||'1 kiss'}</span><h2 className="mt-3 font-serif text-2xl">{x.title}</h2><p className={muted}>{x.body}</p><button className={primary+' mt-4'} disabled={!ready} onClick={()=>setPendingGift(x)}>{receipt(x.id)?'View receipt':'Redeem gift'}</button></article>)}<dialog style={{margin:'auto',width:'calc(100% - 32px)',maxWidth:440,maxHeight:'85dvh',overflow:'auto'}} ref={giftDialog} onCancel={()=>setPendingGift(null)} onClose={()=>setPendingGift(null)} aria-labelledby="gift-dialog-title" className="os-dialog rounded-3xl border bg-[#fffaf7] p-6 backdrop:bg-black/40">{pendingGift&&<><h2 id="gift-dialog-title" className="font-serif text-3xl">{receipt(pendingGift.id)?'Your gift receipt':'A little promise?'}</h2><p className="mt-4 text-xl">{pendingGift.title}</p><p className={muted}>{pendingGift.body}</p><p className="mt-3 font-semibold">Price: {pendingGift.price||'1 kiss'}</p>{receipt(pendingGift.id)?<p role="status" className={muted+' mt-4'}>Redeemed on {receipt(pendingGift.id)!.slice(0,10)}. No expiry date.</p>:<button className={primary+' mt-5'} onClick={()=>dispatch({type:'redeem',id:pendingGift.id,at:new Date().toISOString()})}>Confirm redemption</button>}<p className={muted+' mt-4'}>This receipt stays on this device. Show it to me to claim your gift.</p><button className={button+' mt-4 w-full'} onClick={()=>setPendingGift(null)}>Close</button></>}</dialog></div>;
 else content=<div className="space-y-5"><p className={muted}>A soundtrack for your birthday, with a little dedication for every track.</p><div className="grid gap-3" aria-label="Radio tracks">{items.map((x,i)=><button key={x.id} className={card+' text-left '+(selected.id===x.id?'ring-2 ring-[#a9476b]':'')} disabled={!ready} aria-pressed={selected.id===x.id} onClick={()=>select(x.id)}><p className="text-xs text-[#9c4966]">Track {i+1}</p><h2 className="mt-2 text-xl font-semibold">{x.title}</h2></button>)}</div><section className={card} style={itemStyle(selected)}><p className="text-xs uppercase tracking-widest">Selected track</p><h2 className="my-4 font-serif text-2xl">{selected.title}</h2><Media key={selected.id+selected.src} item={selected} kind="audio"/><p className={muted+' mt-4 whitespace-pre-line'}>{selected.body}</p><div className="mt-4 flex gap-3"><button className={button} disabled={!ready||items.indexOf(selected)===0} onClick={()=>select(items[items.indexOf(selected)-1].id)}>Previous track</button><button className={button} disabled={!ready||items.indexOf(selected)===items.length-1} onClick={()=>select(items[items.indexOf(selected)+1].id)}>Next track</button></div></section></div>;
 return <div className={embedded?'px-5 py-7 sm:px-8':'min-h-screen px-5 py-7 sm:px-8'}><div className="mx-auto max-w-2xl">{!embedded&&<header className="mb-7"><a href="/home" className={button}>← Home</a><h1 className="mt-5 text-xl font-semibold">{app.icon} {app.title}</h1></header>}{provided===undefined&&<p className="mb-5 rounded-2xl border border-[#e5bfcd] p-4 text-sm text-[#806f69]">Sample content — your personal messages and media haven’t been published yet.</p>}{content}{storageWarning&&<p role="status" className={muted+' mt-6'}>Your browser is blocking storage. Choices work here but may not survive closing this page.</p>}{items.length>0&&<details className="mt-8 text-xs text-[var(--w-muted)]"><summary className="cursor-pointer py-3">Saved on this device</summary><p className="my-3">Favourites, choices and gift receipts stay in this browser. Clearing browser data removes them.</p><button className={button} disabled={!ready} onClick={()=>{if(window.confirm('Clear this app’s saved choices and receipts on this device?'))dispatch({type:'reset'})}}>Reset this app</button></details>}</div></div>;
}
