'use client';
import {createContext,useContext,useEffect,useRef,useState,type CSSProperties} from 'react';
import {safeMediaUrl,type CMSNode} from '@wiffeyyyy/content';
import {playbackCoordinator} from '../../audio/src/controller';
import {SocialIcon} from './saragram-icon';
export const AppVideoAudioContext=createContext<{muted:boolean;setMuted:(muted:boolean)=>void}|null>(null);
const cache=new Map<string,string>();
export const mediaSrc=(node:CMSNode,key='src')=>safeMediaUrl(node.props[key])||key==='src'&&node.id.startsWith('camera-')&&String(node.props[key]).startsWith('blob:')?String(node.props[key]??''):'';
export const videoNode=(node:CMSNode)=>node.component==='video'||node.component==='movie-scene'&&node.props.mediaKind!=='image';
export function imagePreview(node:CMSNode,width=480){const src=mediaSrc(node),variants=String(node.props.variantWidths??'').split(',').map(Number).filter(n=>[480,960,1600].includes(n)).sort((a,b)=>a-b);const variant=variants.find(n=>n>=width)||variants.at(-1);return /^\/media\/[a-f\d-]{36}$/i.test(src)?(variant?src+'?variant='+variant:src+'?thumbnail=1'):src;}
export function posterSrc(node:CMSNode){return mediaSrc(node,'poster')||(/^\/media\/[a-f\d-]{36}$/i.test(mediaSrc(node))?mediaSrc(node)+'?poster=1':'');}
function useVisibility(){const ref=useRef<HTMLDivElement>(null),[near,setNear]=useState(false),[active,setActive]=useState(false);useEffect(()=>{const el=ref.current;if(!el)return;const loading=new IntersectionObserver(([entry])=>{if(entry.isIntersecting)setNear(true)},{rootMargin:'180px'}),playback=new IntersectionObserver(([entry])=>setActive(entry.isIntersecting&&entry.intersectionRatio>.6),{threshold:[0,.6,1]});loading.observe(el);playback.observe(el);return()=>{loading.disconnect();playback.disconnect()}},[]);return{ref,near,active};}
/** A grid uses a small image, never an autoplaying/full-download video. */
export function AppMediaThumbnail({node,className='',eager=false}:{node:CMSNode;className?:string;eager?:boolean}){
 const {ref,near}=useVisibility(),src=mediaSrc(node),video=videoNode(node),poster=posterSrc(node),[posterFailed,setPosterFailed]=useState(false),[failed,setFailed]=useState(false),[original,setOriginal]=useState(false),[frame,setFrame]=useState(cache.get(src)||'');
 const element=useRef<HTMLVideoElement>(null);
 useEffect(()=>{setPosterFailed(false);setFailed(false);setOriginal(false);setFrame(cache.get(src)||'')},[src,poster]);
 const capture=()=>{const el=element.current;if(!el||el.readyState<2||!el.videoWidth)return;try{const canvas=document.createElement('canvas');const scale=Math.min(1,360/Math.max(el.videoWidth,el.videoHeight));canvas.width=Math.max(1,Math.round(el.videoWidth*scale));canvas.height=Math.max(1,Math.round(el.videoHeight*scale));canvas.getContext('2d')!.drawImage(el,0,0,canvas.width,canvas.height);const image=canvas.toDataURL('image/webp',.75);if(cache.size>=80)cache.delete(cache.keys().next().value!);cache.set(src,image);setFrame(image)}catch{/* Cross-origin media can still display its decoded video frame. */}};
 return <div ref={ref} className={'app-media-thumbnail '+className} data-media-src={src} aria-label={String(node.props.alt||'Media thumbnail')} data-media-kind={video?'video':'image'}>{src&&(near||eager)?!video?<img src={original?src:imagePreview(node)} alt={String(node.props.alt??'Photo')} loading={eager?'eager':'lazy'} decoding="async" onError={()=>{if(!original&&imagePreview(node)!==src)setOriginal(true);else setFailed(true)}}/>:frame?<img src={frame} alt={String('Video preview')}/>:poster&&!posterFailed?<img src={poster} alt={String('Video preview')} loading="lazy" onError={()=>setPosterFailed(true)}/>:!failed?<video ref={element} src={src} crossOrigin="anonymous" muted playsInline preload="metadata" onLoadedMetadata={e=>{const el=e.currentTarget;if(el.videoWidth&&Number.isFinite(el.duration))el.currentTime=Math.min(.1,el.duration/2)}} onSeeked={capture} onLoadedData={capture} onError={()=>setFailed(true)} aria-label={String('Video preview')}/>:null:null}{(!src||failed)&&<span className="app-media-unavailable">{video?'▶':'▧'}<small>{failed?'Preview unavailable':'No media yet'}</small></span>}</div>;
}
export function AppVideo({node,mode='feed',editing=false,onEnded}:{node:CMSNode;mode?:'feed'|'reel'|'viewer'|'story';editing?:boolean;onEnded?:()=>void}){
 const audioPreference=useContext(AppVideoAudioContext);
 const {ref,near,active}=useVisibility(),element=useRef<HTMLVideoElement>(null),manualPause=useRef(false),src=mediaSrc(node),[localMuted,setLocalMuted]=useState(mode!=='viewer'),[paused,setPaused]=useState(true),[failed,setFailed]=useState(false),[loading,setLoading]=useState(true),[attempt,setAttempt]=useState(0),[time,setTime]=useState(0),[duration,setDuration]=useState(0);
 const muted=audioPreference?.muted??localMuted,setMuted=audioPreference?.setMuted??setLocalMuted;
 const [posterFailed,setPosterFailed]=useState(false),poster=posterSrc(node);
 useEffect(()=>{setFailed(false);setLoading(true);setPosterFailed(false);manualPause.current=false;setTime(0)},[src,attempt]);
 useEffect(()=>{const el=element.current;if(!el||!near||editing)return;const play=()=>{if(active&&!document.hidden&&!manualPause.current)void el.play().catch(()=>{setPaused(true);setLoading(false)});else el.pause()};play();document.addEventListener('visibilitychange',play);return()=>{document.removeEventListener('visibilitychange',play);el.pause();playbackCoordinator.release(el)}},[src,near,active,editing,attempt]);
 const toggle=()=>{const el=element.current;if(!el||!active||document.hidden)return;if(el.paused){manualPause.current=false;setLoading(true);void el.play().catch(()=>{setPaused(true);setLoading(false)})}else{manualPause.current=true;el.pause()}};
 const clock=(seconds:number)=>Math.floor(seconds/60)+':'+String(Math.floor(seconds%60)).padStart(2,'0');
 const ratio=Number(node.props.mediaWidth)>0&&Number(node.props.mediaHeight)>0?Number(node.props.mediaWidth)/Number(node.props.mediaHeight):.8;
 return <div ref={ref} data-media-src={src} className={'app-video app-video-'+mode+(failed?' app-video-failed':'')} style={mode==='feed'?{aspectRatio:ratio,maxHeight:520} as CSSProperties:undefined}>
 {failed?<div className="app-video-error" role="status"><p>This video couldn’t play.</p><button onClick={()=>setAttempt(value=>value+1)}>Retry video</button><a href={src} target="_blank" rel="noreferrer">Open original</a></div>:<><video key={src+attempt} ref={element} src={near?src:undefined} poster={!posterFailed?poster||undefined:undefined} playsInline muted={muted} loop={mode!=='story'&&mode!=='viewer'} preload={near?'metadata':'none'} onLoadedMetadata={e=>setDuration(Number.isFinite(e.currentTarget.duration)?e.currentTarget.duration:0)} onLoadedData={()=>setLoading(false)} onWaiting={()=>setLoading(true)} onPlaying={()=>setLoading(false)} onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onPlay={e=>{playbackCoordinator.claim(e.currentTarget);setPaused(false)}} onPause={e=>{playbackCoordinator.release(e.currentTarget);setPaused(true)}} onEnded={onEnded} onError={()=>{setFailed(true);setLoading(false)}} aria-label={String(node.props.alt||'Video')}/>
 {!near&&!posterFailed&&poster&&<img className="app-video-cover" src={poster} alt="" loading="lazy" onError={()=>setPosterFailed(true)}/>}
 <button className="app-video-tap" aria-label={paused?'Play video':'Pause video'} disabled={editing} onClick={toggle}>{paused&&!loading&&<span aria-hidden="true">▶</span>}</button>{loading&&near&&<span className="app-video-loading" role="status" aria-label="Loading video"/>}
 <button className="app-video-sound" disabled={editing} aria-label={muted?'Unmute video':'Mute video'} onClick={()=>setMuted(!muted)}><SocialIcon name={muted?'mute':'sound'}/></button>
 {mode==='viewer'&&<div className="app-video-controls"><button aria-label={paused?'Play video':'Pause video'} onClick={toggle}>{paused?'▶':'Ⅱ'}</button><span>{clock(time)}</span><input type="range" aria-label="Seek video" min="0" max={duration||1} step=".1" value={Math.min(time,duration||1)} onChange={e=>{if(element.current)element.current.currentTime=Number(e.target.value)}}/><span>{clock(duration)}</span></div>}</>}
 </div>;
}
