"use client";
import {useState} from "react";
import type {AppDefinition} from "@wiffeyyyy/content";
const reasons=["The way you smile when you’re trying not to.","Your tiny expressions that somehow say everything.","How you make ordinary days feel like something worth remembering.","The little habits I notice even when you think I don’t.","Because being around you feels like coming home."];
const gifts=[["Movie night","One movie, zero arguments about what to watch."],["Long hug","Redeemable whenever you need one."],["Breakfast","I make it. You choose the order."],["Handwritten letter","One very old-school promise on paper."]];
const songs=[["Our song","The one that instantly makes me think of you."],["Late-night favourite","For the nights we don’t want to end."],["Birthday dedication","Because today gets its own soundtrack."]];
export function AppExperience({app,embedded=false}:{app:AppDefinition;embedded?:boolean}){
 const [playing,setPlaying]=useState(false),[choice,setChoice]=useState(""),[redeemed,setRedeemed]=useState("");
 let content:React.ReactNode;
 if(app.kind==="reasons") content=<div className="space-y-4">{reasons.map((r,i)=><article key={r} className="rounded-3xl border border-[var(--w-border)] bg-white p-6 shadow-sm"><p className="text-xs text-[var(--w-muted)]">Reason {i+1}</p><p className="mt-3 text-xl leading-8">{r}</p></article>)}</div>;
 else if(app.kind==="hotline") content=<div className="rounded-3xl bg-white p-7 text-center shadow-sm"><div className="mx-auto grid size-20 place-items-center rounded-full bg-[var(--w-accent-soft)] text-4xl">☎️</div><h2 className="mt-5 text-2xl font-semibold">Incoming birthday call</h2><p className="mt-2 text-[var(--w-muted)]">Tap answer when you’re ready.</p><button onClick={()=>setPlaying(!playing)} className="mt-6 rounded-full bg-[var(--w-accent)] px-7 py-3 font-semibold text-white">{playing?"Playing…":"Answer"}</button><p className="mt-6 text-sm text-[var(--w-muted)]">Text version: Happy birthday. I hope you always know how ridiculously loved you are.</p></div>;
 else if(app.kind==="adventure") content=<div className="grid gap-4">{["Cosy evening","Daytime adventure","A little surprise"].map(x=><button key={x} onClick={()=>setChoice(x)} className={"rounded-3xl border bg-white p-6 text-left "+(choice===x?"ring-2 ring-[var(--w-accent)]":"")}><b>{x}</b><p className="mt-1 text-sm text-[var(--w-muted)]">Choose this kind of birthday day together.</p></button>)}{choice&&<div className="rounded-3xl bg-[var(--w-accent-soft)] p-6"><b>Your invitation</b><p className="mt-2">It’s a date. I’ll take care of the details. 💗</p></div>}</div>;
 else if(app.kind==="movie") content=<div className="rounded-3xl bg-black p-4 text-white"><div className="grid aspect-video place-items-center rounded-2xl bg-zinc-800"><button onClick={()=>setPlaying(!playing)} className="grid size-16 place-items-center rounded-full bg-white text-black text-xl">{playing?"Ⅱ":"▶"}</button></div><h2 className="mt-5 text-xl">Our little movie</h2><p className="mt-1 text-sm text-zinc-300">A short story about us, ending with one birthday message.</p></div>;
 else if(app.kind==="shop") content=<div className="grid gap-4">{gifts.map(([name,desc])=><article key={name} className="rounded-3xl border bg-white p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">{name}</h2><p className="mt-1 text-sm text-[var(--w-muted)]">{desc}</p></div><button onClick={()=>setRedeemed(name)} className="rounded-xl bg-[var(--w-accent)] px-3 py-2 text-sm font-semibold text-white">Redeem</button></div></article>)}{redeemed&&<div className="rounded-3xl bg-[var(--w-accent-soft)] p-6"><b>Gift receipt 💗</b><p className="mt-2">One “{redeemed}” is officially yours. No expiry date.</p></div>}</div>;
 else content=<div className="space-y-3">{songs.map(s=><button key={s[0]} onClick={()=>setPlaying(true)} className={"w-full rounded-3xl border bg-white p-5 text-left "+(playing?"ring-2 ring-[var(--w-accent)]":"")}><b>{s[0]}</b><p className="mt-1 text-sm text-[var(--w-muted)]">{s[1]}</p></button>)}<div className="sticky bottom-4 rounded-2xl bg-white p-4 shadow-lg border flex items-center justify-between"><span className="text-sm">Birthday Radio</span><button onClick={()=>setPlaying(!playing)} className="rounded-full bg-[var(--w-accent)] px-4 py-2 text-white">{playing?"Pause":"Play"}</button></div></div>;
 return <main className="min-h-screen px-5 py-7 sm:px-8"><div className="mx-auto max-w-2xl">{!embedded&&<header className="mb-7 flex items-center gap-4"><a href="/home" aria-label="Back to home" className="grid size-10 place-items-center rounded-full bg-white border">←</a><div><p className="text-xs text-[var(--w-muted)]">Wiffeyyyy OS</p><h1 className="text-xl font-semibold">{app.icon} {app.title}</h1></div></header>}{content}</div></main>;
}
