"use client";
import {useEffect,useRef,type ReactNode,type CSSProperties} from 'react';
import type {CMSField,PageDocument} from '@wiffeyyyy/content';
export function ArchiveFrame({enabled,editing,effects=true,note='for you, always',settings={},theme,children}:{enabled:boolean;editing:boolean;effects?:boolean;note?:string;settings?:Record<string,CMSField>;theme?:PageDocument['theme'];children:ReactNode}){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!enabled||!effects||editing||!ref.current||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const nodes=ref.current.querySelectorAll('[data-archive-part="memory"]');const o=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('archive-seen');o.unobserve(e.target)}}),{threshold:.08});nodes.forEach(n=>{n.classList.add('archive-await');o.observe(n)});return()=>{o.disconnect();nodes.forEach(n=>n.classList.remove('archive-await'))}},[enabled,editing,effects]);
 if(!enabled)return <>{children}</>;
 const vars={
  '--archive-bg':String(settings.background??theme?.background??'#160c20'),'--archive-text':String(theme?.text??'#fff0f7'),'--archive-muted':String(theme?.muted??'#d4b9ce'),'--archive-accent':String(theme?.primary??'#ff78b4'),'--archive-surface':String(theme?.surface??'#281532'),
  '--archive-glow-one':String(settings.glowOneColor??'#9d285e'),'--archive-glow-two':String(settings.glowTwoColor??'#6244a2'),'--archive-heart-color':String(settings.decorativeHeartColor??'#ff78b4'),'--archive-decoration-opacity':String(settings.decorationOpacity??.5),'--archive-heart-size':Number(settings.decorativeHeartSize??360)+'px',
  '--archive-hero-min-height':Number(settings.heroMinHeight??620)+'px','--archive-hero-side-space':Number(settings.heroSideSpace??35)+'%','--archive-hero-gap':Number(settings.heroGap??24)+'px','--archive-title-font-style':settings.titleItalic===false||settings.titleItalic==='false'?'normal':'italic','--archive-title-tracking':Number(settings.titleTracking??-4)+'px',
  '--archive-mobile-hero-min-height':Number(settings.mobileHeroMinHeight??740)+'px','--archive-mobile-hero-top-padding':Number(settings.mobileHeroTopPadding??280)+'px','--archive-soundtrack-angle':Number(settings.gradientAngle??110)+'deg','--archive-soundtrack-start':String(settings.gradientStart??'#3b1b34'),'--archive-soundtrack-end':String(settings.gradientEnd??'#241530')
 } as CSSProperties;
 return <div ref={ref} className="archive-experience" style={vars} data-editing={editing||undefined} data-effects={effects}><div className="archive-atmosphere" hidden={!effects} aria-hidden="true"><div className="archive-orbit"/><div className="archive-glow archive-glow-one"/><div className="archive-glow archive-glow-two"/>{Array.from({length:12},(_,i)=><span key={i} style={{'--i':i,left:(i*37%100)+'%',top:(i*23%100)+'%'} as CSSProperties}>{i%3===0?'♡':'✦'}</span>)}<div className="archive-heart">♡</div><div className="archive-orbit-note">{note}</div></div>{children}</div>
}
