'use client';
import {useEffect,useRef,useState} from 'react';
export function PhoneAppIcon(){return <svg viewBox="0 0 60 60" width="60" height="60" aria-hidden="true"><rect width="60" height="60" rx="14" fill="#34c759"/><path d="M18 12c-3 0-7 5-6 10 3 13 13 23 26 26 5 1 10-3 10-6l-1-5-10-5-5 5c-6-3-10-7-13-13l5-5-5-7z" fill="white"/></svg>}
export function CameraAppIcon(){return <svg viewBox="0 0 60 60" width="60" height="60" aria-hidden="true"><defs><linearGradient id="camera-gray" x2="0" y2="1"><stop stopColor="#f2f2f2"/><stop offset="1" stopColor="#b7b7bc"/></linearGradient></defs><rect width="60" height="60" rx="14" fill="url(#camera-gray)"/><path d="M10 22h10l4-6h12l4 6h10v26H10z" fill="#29292b"/><circle cx="30" cy="34" r="10" fill="#b7b7bc"/><circle cx="30" cy="34" r="7" fill="#29292b"/><circle cx="44" cy="27" r="2" fill="#f5f5f5"/></svg>}
export function CameraApp(){
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),recorder=useRef<MediaRecorder|null>(null),session=useRef(0),alive=useRef(true),urlRef=useRef('');
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[front,setFront]=useState(false),[mode,setMode]=useState<'PHOTO'|'VIDEO'>('PHOTO'),[recording,setRecording]=useState(false),[seconds,setSeconds]=useState(0),[capture,setCapture]=useState<{url:string;video:boolean}|null>(null),[preview,setPreview]=useState(false);
 const stop=()=>{stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;};
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;session.current++;if(recorder.current?.state==='recording')recorder.current.stop();stop();if(urlRef.current)URL.revokeObjectURL(urlRef.current)}},[]);
 useEffect(()=>{if(!recording)return;setSeconds(0);const timer=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(timer)},[recording]);
 const start=async(facing=front)=>{const request=++session.current;stop();setReady(false);setBusy(true);setError('');try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera access requires a supported browser and a secure connection.');const next=await navigator.mediaDevices.getUserMedia({video:{facingMode:facing?'user':'environment'},audio:false});if(!alive.current||request!==session.current){next.getTracks().forEach(t=>t.stop());return}stream.current=next;if(video.current){video.current.srcObject=next;await video.current.play()}setReady(true);setFront(facing)}catch(e){if(alive.current&&request===session.current)setError(e instanceof DOMException&&e.name==='NotAllowedError'?'Camera permission was denied. Allow camera access in your browser settings, then try again.':e instanceof DOMException&&e.name==='NotFoundError'?'No camera was found on this device.':e instanceof Error?e.message:'Could not open the camera.')}finally{if(alive.current&&request===session.current)setBusy(false)}};
 const saveCapture=(blob:Blob,isVideo:boolean)=>{if(!alive.current)return;if(urlRef.current)URL.revokeObjectURL(urlRef.current);const url=URL.createObjectURL(blob);urlRef.current=url;setCapture({url,video:isVideo})};
 const shutter=()=>{if(!ready||!stream.current)return;if(mode==='VIDEO'){if(recording){recorder.current?.stop();return}if(typeof MediaRecorder==='undefined'){setError('Video recording is unavailable in this browser.');return}try{const rec=new MediaRecorder(stream.current),chunks:Blob[]=[];recorder.current=rec;rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=()=>{if(alive.current){setRecording(false);saveCapture(new Blob(chunks,{type:rec.mimeType}),true)}};rec.onerror=()=>{if(alive.current){setRecording(false);setError('Recording failed. Please try again.')}};rec.start();setRecording(true)}catch{setError('Video recording is unavailable in this browser.')}return}const v=video.current;if(!v?.videoWidth)return;const canvas=document.createElement('canvas');canvas.width=v.videoWidth;canvas.height=v.videoHeight;const context=canvas.getContext('2d');if(!context)return;context.drawImage(v,0,0);canvas.toBlob(blob=>{if(blob)saveCapture(blob,false)},'image/jpeg',.95)};
 return <main className="camera-app"><header className="camera-top"><a href="/home" aria-label="Return to home screen">‹</a><span>{recording?<span className="camera-timer">● {Math.floor(seconds/60).toString().padStart(2,'0')}:{(seconds%60).toString().padStart(2,'0')}</span>:'Camera'}</span><span className="camera-hd">{mode==='VIDEO'?'VIDEO':'HEIF / JPEG'}</span></header><div className="camera-view"><video ref={video} autoPlay muted playsInline style={{transform:front?'scaleX(-1)':undefined}}/><div className="camera-grid" aria-hidden="true"/>{!ready&&<div className="camera-permission"><CameraAppIcon/><h1>Your camera, ready when you are.</h1><p>{error||'Allow camera access to take photos and record videos. Captures stay on this device.'}</p><button disabled={busy} onClick={()=>start()}>{busy?'Opening camera…':error?'Try again':'Enable camera'}</button></div>}{ready&&error&&<p className="camera-error" role="alert">{error}</p>}<span className="camera-zoom">1×</span></div><div className="camera-controls"><div className="camera-modes">{(['VIDEO','PHOTO'] as const).map(m=><button key={m} disabled={recording} aria-pressed={mode===m} onClick={()=>setMode(m)}>{m}</button>)}</div><div className="camera-actions"><button className="camera-thumb" disabled={!capture||recording} aria-label="View last capture" onClick={()=>setPreview(true)}>{capture?(capture.video?<video src={capture.url} muted/>:<img src={capture.url} alt="Last capture"/>):<span>▧</span>}</button><button className={'camera-shutter '+(mode==='VIDEO'?'is-video ':'')+(recording?'is-recording':'')} disabled={!ready||busy} aria-label={recording?'Stop recording':mode==='VIDEO'?'Record video':'Take photo'} onClick={shutter}><span/></button><button className="camera-flip" disabled={busy||recording||!ready} aria-label="Switch camera" onClick={()=>start(!front)}><svg viewBox="0 0 24 24" width="28" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M4 9a8 8 0 0 1 14-3l2 3M20 15a8 8 0 0 1-14 3l-2-3M20 3v6h-6M4 21v-6h6"/></svg></button></div><p className="camera-local">{recording?'Recording video without audio':'Saved locally · private to your device'}</p><a className="camera-home" href="/home" aria-label="Return to home screen"><span/></a></div>{preview&&capture&&<div className="camera-preview" role="dialog" aria-modal="true" aria-label="Captured media"><button autoFocus onClick={()=>setPreview(false)}>Done</button>{capture.video?<video src={capture.url} controls autoPlay playsInline/>:<img src={capture.url} alt="Captured photo"/>}<a href={capture.url} download={'saragram-'+Date.now()+(capture.video?(capture.url&&recorder.current?.mimeType.includes('mp4')?'.mp4':'.webm'):'.jpg')}>Save to device</a></div>}</main>
}
