"use client";
import {CameraApp} from './camera-app';
import {PuzzleApp} from './puzzle-app';
import {VaultApp} from './vault-app';
import {HeartPage} from './heart-page';
import {ArchiveFrame} from './archive-frame';
import {KissShop} from './kiss-shop';
import {Saragram} from './saragram';
import {PhotoLibrary} from './photo-library';
import {AdoreJournal} from './adore-journal';
import {AdoreFrame} from './adore-frame';
import {PhoneHome} from './phone-home';
import {DocumentSettingsContext,PageLayoutProvider,LayoutSection} from './page-layout';
import {HomeNavigation,useSiteNavigation} from './navigation';
import {resolveResponsive,parsePageDocument,appComponents,getAppItems,getPublicApp,type CMSField,type CMSNode,type PageDocument} from '@wiffeyyyy/content';
import {MediaPlayer} from './media-player';
import {AppExperience} from './app-experience';
import {createContext,useContext,useEffect,useRef,useState,useMemo,type ReactNode} from 'react';
import type {CSSProperties} from 'react';

const LiveEditorPreviewContext=createContext(false);
export function LiveEditorPreviewProvider({children}:{children:ReactNode}){return <LiveEditorPreviewContext.Provider value>{children}</LiveEditorPreviewContext.Provider>}

const apps=[['💗','Adore','reasons'],['☎️','Hotdial','hotline'],['🌸','Pardanasheen','adventure'],['📷','Saragram','movie'],['💋','The Kiss Shop','kiss-shop'],['📷','Clicksara','camera']];
function style(node:CMSNode):CSSProperties{const p=node.props;return {display:node.type==='section'?'grid':undefined,gap:node.type==='section'?Number(p.gap??16):undefined,gridTemplateColumns:node.type==='section'?`repeat(${p.columns??1},minmax(0,1fr))`:undefined,maxWidth:p.maxWidth?Number(p.maxWidth):undefined,border:p.borderWidth?`${p.borderWidth}px solid ${p.borderColor??'#e2d2c2'}`:undefined,boxShadow:p.shadow==='soft'?'0 10px 35px #493b3510':p.shadow==='deep'?'0 18px 45px #493b3528':undefined,fontFamily:p.fontFamily as string|undefined,lineHeight:p.lineHeight as number|undefined,letterSpacing:p.letterSpacing as number|undefined,background:p.background as string|undefined,color:p.color as string|undefined,padding:p.padding as number|undefined,margin:p.margin as number|undefined,borderRadius:p.radius as number|undefined,opacity:p.opacity as number|undefined,fontSize:p.size as number|undefined,fontWeight:p.weight as number|undefined,textAlign:p.align as CSSProperties['textAlign'],paddingTop:p.paddingTop as number|undefined,paddingRight:p.paddingRight as number|undefined,paddingBottom:p.paddingBottom as number|undefined,paddingLeft:p.paddingLeft as number|undefined,marginTop:p.marginTop as number|undefined,marginRight:p.marginRight as number|undefined,marginBottom:p.marginBottom as number|undefined,marginLeft:p.marginLeft as number|undefined,'--section-radius':String(p.radius??24)+'px'} as CSSProperties}
function Block({node,editing=false}:{node:CMSNode;editing?:boolean}){const p=node.props;const navigation=useSiteNavigation();switch(node.component){
 case 'action':{const newTab=p.openInNewTab===true||p.openInNewTab==='true';return <a style={style(node)} href={editing?undefined:String(p.href??'/home')} target={!editing&&newTab?'_blank':undefined} rel={!editing&&newTab?'noopener noreferrer':undefined} className="inline-flex min-h-11 rounded-2xl border p-3">{String(p.title??'Continue')}</a>}
 case 'station':case 'chapter':case 'invitation':return <article style={style(node)} className="rounded-3xl border p-5"><h2 className="text-xl">{String(p.title??'')}</h2><p>{String(p.body??'')}</p></article>;
 case 'heading':return <h1 style={style(node)} className="text-3xl font-semibold">{p.text??''}</h1>;
 case 'text':return <p style={style(node)} className="leading-7 text-[var(--w-muted)]">{p.text??''}</p>;
 case 'app-grid':if(navigation)return <HomeNavigation items={navigation} editing={editing} style={{...style(node),display:'grid',gridTemplateColumns:`repeat(${p.columns??2},minmax(0,1fr))`,gap:Number(p.gap??12)}}/>;return <div style={{...style(node),display:'grid',gridTemplateColumns:`repeat(${p.columns??2},minmax(0,1fr))`,gap:Number(p.gap??12)}}>{apps.map(([icon,title,slug])=><a key={slug} href={editing?undefined:'/app/'+slug} tabIndex={editing?-1:undefined} style={{background:'var(--w-surface)',borderColor:'var(--w-accent)',borderRadius:'var(--w-radius)'}} className="border p-5"><span className="text-2xl">{icon}</span><h2 className="mt-3 font-semibold">{title}</h2></a>)}</div>;
 case 'video':case 'audio':return p.src?<MediaPlayer identity={'block:'+node.id} src={String(p.src)} kind={node.component as 'audio'|'video'} loop={p.loop===true||p.loop==='true'} initialVolume={typeof p.initialVolume==='number'?p.initialVolume:undefined} title={String(p.alt??node.component)} captions={String(p.captions??'')} disabled={editing} style={style(node)} className="w-full rounded-3xl"/>:null;
 case 'image':return !p.src&&p.emptyLabel?<div className="archive-photo-placeholder" style={{...style(node),height:Number(p.displayHeight??320)}}><span aria-hidden="true">♡</span><p>{String(p.emptyLabel)}</p></div>:p.src?<img src={String(p.src)} srcSet={p.mediaAssetId&&p.variantWidths?String(p.variantWidths).split(',').map(w=>String(p.src)+'?variant='+w+' '+w+'w').concat(p.mediaWidth?[String(p.src)+' '+p.mediaWidth+'w']:[]).join(', '):undefined} sizes={p.mediaAssetId?'(max-width: 768px) 100vw, 672px':undefined} width={typeof p.mediaWidth==='number'?p.mediaWidth:undefined} height={typeof p.mediaHeight==='number'?p.mediaHeight:undefined} alt={String(p.alt??'')} loading="lazy" decoding="async" style={{...style(node),objectFit:(p.objectFit??'cover') as CSSProperties['objectFit'],objectPosition:`${p.focalX??50}% ${p.focalY??50}%`,height:p.displayHeight?Number(p.displayHeight):'auto'}} className="w-full rounded-3xl object-cover"/>:null;
 default:{if(Object.values(appComponents).includes(node.component))return <article style={style(node)} className="rounded-3xl border bg-white p-6"><p className="text-xs text-[var(--w-muted)]">{node.label}</p><h2 className="mt-2 text-xl font-semibold">{p.title??''}</h2><p className="mt-3 whitespace-pre-line leading-7">{p.body??''}</p>{p.category&&<p className="mt-3 text-sm">Category: {p.category}</p>}{p.price&&<p className="mt-3 text-sm">Price: {p.price}</p>}{p.invitation&&<p className="mt-3 text-sm">Invitation: {p.invitation}</p>}</article>;return null}
 }}
export function CMSRenderer({document,onSelect,selectedId,embedded=false,previewDevice,persistProgress=false,externalShell=false}:{document:PageDocument;onSelect?:(id:string)=>void;selectedId?:string;embedded?:boolean;previewDevice?:'mobile'|'tablet'|'desktop';persistProgress?:boolean;externalShell?:boolean}){
 const exactLivePreview=useContext(LiveEditorPreviewContext),legacyEditing=!!onSelect&&!exactLivePreview,siteSettings=useContext(DocumentSettingsContext);
 const container=useRef<HTMLDivElement>(null),[device,setDevice]=useState<'mobile'|'tablet'|'desktop'>('desktop');
 useEffect(()=>{if(previewDevice||!container.current)return;const observe=new ResizeObserver(([entry])=>setDevice(entry.contentRect.width<600?'mobile':entry.contentRect.width<960?'tablet':'desktop'));observe.observe(container.current);return()=>observe.disconnect()},[previewDevice]);
 const original=useMemo(()=>parsePageDocument(document),[document]),responsiveDevice=previewDevice??device,originalById=new Map(original.nodes.map(n=>[n.id,n]));
 const prepared=original.nodes.map(n=>{if(responsiveDevice==='mobile'&&n.component==='image'&&n.parentId){const parent=originalById.get(n.parentId);if(parent?.props.archivePart==='memory'&&n.props['mobile:displayHeight']===undefined)return {...n,props:{...n.props,'mobile:displayHeight':Number(parent.props.mobileImageHeight??330)}}}return n});
 const valid={...original,nodes:prepared.map(n=>resolveResponsive(n,responsiveDevice))};const byId=new Map(valid.nodes.map(n=>[n.id,n]));
 const legacy={...valid,nodes:valid.nodes.map(n=>n.props.sectionKind?{...n,visible:false}:n)};const groups=Object.entries(appComponents).map(([kind,component])=>({component,app:getPublicApp(kind==='shop'?'kiss-shop':kind)!,items:getAppItems(legacy,kind as keyof typeof appComponents)}));
 const archiveRoot=valid.nodes.find(n=>n.props.archivePart==='page'),archiveHero=valid.nodes.find(n=>n.props.archivePart==='hero'),archiveSoundtrack=valid.nodes.find(n=>n.props.archivePart==='soundtrack');
 const archiveSettings:Record<string,CMSField>={...(archiveRoot?.props??{})};for(const key of ['heroMinHeight','heroSideSpace','heroGap','titleItalic','titleTracking','mobileHeroMinHeight','mobileHeroTopPadding'])if(archiveHero?.props[key]!==undefined)archiveSettings[key]=archiveHero.props[key];for(const key of ['gradientStart','gradientEnd','gradientAngle'])if(archiveSoundtrack?.props[key]!==undefined)archiveSettings[key]=archiveSoundtrack.props[key];
 const chooseFromSurface=(fallbackId:string)=>(event:React.MouseEvent|React.KeyboardEvent)=>{if(!onSelect)return;if('key' in event&&!['Enter',' '].includes(event.key))return;event.preventDefault();event.stopPropagation();const target=(event.target as HTMLElement).closest<HTMLElement>('[data-layout-node-id],[data-phone-node],[data-node-id]');onSelect(target?.getAttribute('data-layout-node-id')??target?.getAttribute('data-phone-node')??target?.getAttribute('data-node-id')??fallbackId)};
 const liveSurface=(content:ReactNode,fallbackId:string)=>onSelect?<div key={fallbackId} data-node-id={fallbackId} onClickCapture={chooseFromSurface(fallbackId)} onKeyDownCapture={chooseFromSurface(fallbackId)}>{content}</div>:content;
 const liveShell=(content:ReactNode,mainClass:string,phone=false)=>{if(!exactLivePreview||externalShell)return content;return <div className={'birthday-os'+(phone?' birthday-os-phone':'')} data-editor-live-shell="true" style={{'--phone-scale':1,'--phone-fit-top':'23px',background:siteSettings.background,color:siteSettings.text,'--w-accent':siteSettings.accent,'--w-surface':siteSettings.surface,'--w-text':siteSettings.text,'--w-radius':siteSettings.radius+'px'} as CSSProperties}><div id="birthday-content"><main className={mainClass}>{content}</main></div></div>};
 const render=(id:string):ReactNode=>{const n=byId.get(id)!;if(!n.visible)return null;if(n.type==='section'&&n.props.sectionKind){const choose=chooseFromSurface(id);return <div key={id} data-node-id={id} role={onSelect?'button':undefined} tabIndex={onSelect?0:undefined} aria-label={onSelect?'Select '+(n.label??'section'):undefined} onClickCapture={onSelect?choose:undefined} onKeyDownCapture={onSelect?choose:undefined} style={{...style(n),outline:legacyEditing&&selectedId===id?'2px solid #d86f91':undefined}}><LayoutSection node={n}>{n.children.map(child=>byId.get(child)!).filter(child=>child.visible)}</LayoutSection></div>}
 const group=(!onSelect||exactLivePreview)?groups.find(g=>g.component===n.component):undefined;if(group)return group.items[0]?.id===id?liveSurface(<AppExperience key={id} app={group.app} items={group.items} embedded/>,id):null;
 const archivePart=String(n.props.archivePart??'');return <div key={id} data-node-id={id} role={onSelect?'button':undefined} tabIndex={onSelect?0:undefined} aria-label={onSelect?'Select '+(n.label??n.component):undefined} onKeyDown={onSelect?chooseFromSurface(id):undefined} onClick={onSelect?chooseFromSurface(id):undefined} style={{...(n.type==='section'?style(n):{}),outline:legacyEditing&&selectedId===id?'2px solid #d86f91':undefined}} data-archive-part={archivePart||undefined} data-archive-alternate={archivePart==='collection'?String(n.props.alternateLayout??true):undefined} data-archive-reveal={archivePart==='collection'?String(n.props.revealAnimation??true):undefined} data-archive-hover={archivePart==='collection'?String(n.props.hoverLift??true):undefined} data-archive-image-side={archivePart==='memory'?String(n.props.imageSide??'auto'):undefined}>{n.type==='block'&&<Block node={n} editing={legacyEditing}/>} {n.children.map(render)}</div>};
 const rootId=valid.rootIds[0]??'';
 const runtime=valid.nodes.find(n=>n.parentId===null&&n.props.runtimeApp);
 if(runtime){if(!runtime.visible)return null;const app=runtime.props.runtimeApp;return liveSurface(app==='camera'?<CameraApp document={valid} editing={!!onSelect||exactLivePreview}/>:app==='pieces'?<PuzzleApp key={JSON.stringify(runtime.children.map(id=>{const n=byId.get(id);return [id,n?.visible,n?.props.src,n?.props.cols,n?.props.rows]}))} document={valid} persist={persistProgress}/>:<VaultApp document={valid} editing={!!onSelect||exactLivePreview}/>,runtime.id)}
 if(valid.nodes.some(n=>n.props.heartPart==='page'&&n.parentId===null)){const heart=<HeartPage document={valid} onSelect={onSelect} selectedId={selectedId} contained={legacyEditing&&!!previewDevice} liveVisual={exactLivePreview}/>;return exactLivePreview?liveShell(heart,'os-heart-page'):heart}
 if(valid.layout?.page==='kiss-shop'){const page=exactLivePreview?liveSurface(<KissShop document={valid} persist={persistProgress}/>,rootId):<KissShop document={valid} onSelect={onSelect} selectedId={selectedId} persist={persistProgress}/>;return exactLivePreview?liveShell(page,'os-home os-adore-page',true):page}
 if(valid.layout?.page==='movie'){const page=exactLivePreview?liveSurface(<Saragram document={valid} persist={persistProgress}/>,rootId):<Saragram document={valid} onSelect={onSelect} selectedId={selectedId} persist={persistProgress}/>;return exactLivePreview?liveShell(page,'os-home os-adore-page',true):page}
 if(valid.layout?.page==='reasons'){const page=exactLivePreview?liveSurface(<AdoreJournal document={valid} persist={persistProgress}/>,rootId):<AdoreJournal document={valid} onSelect={onSelect} selectedId={selectedId} persist={persistProgress}/>;return exactLivePreview?liveShell(page,'os-home os-adore-page',true):page}
 if(valid.layout?.page==='adventure'){const page=exactLivePreview?liveSurface(<PhotoLibrary document={valid} persist={persistProgress}/>,rootId):<PhotoLibrary document={valid} onSelect={onSelect} selectedId={selectedId} persist={persistProgress}/>;return exactLivePreview?liveShell(page,'os-home os-adore-page',true):page}
 if(valid.nodes.some(n=>n.parentId===null&&n.props.phonePart==='home')){const page=exactLivePreview?<PageLayoutProvider persist={persistProgress} document={valid} editing={false}>{liveSurface(<PhoneHome document={valid} persist={persistProgress} contained={false} renderNode={render}/>,rootId)}</PageLayoutProvider>:<PageLayoutProvider persist={persistProgress} document={valid} editing={!!onSelect} selectedId={selectedId}><PhoneHome document={valid} onSelect={onSelect} selectedId={selectedId} persist={persistProgress} contained={!!previewDevice} renderNode={render}/></PageLayoutProvider>;return exactLivePreview?liveShell(page,'os-phone-home',true):page}
 const page=<PageLayoutProvider persist={persistProgress} document={valid} editing={legacyEditing} selectedId={legacyEditing?selectedId:undefined}><ArchiveFrame enabled={!!archiveRoot} editing={legacyEditing} effects={![false,'false'].includes(archiveRoot?.props.visualEffects as boolean|string)} note={String(archiveRoot?.props.decorNote??'for you, always')} settings={archiveSettings} theme={valid.theme}><AdoreFrame enabled={valid.layout?.page==='reasons'}><div ref={container} className={archiveRoot?'memories-archive':embedded?'space-y-8':'min-h-screen px-5 py-8'} style={{background:String(valid.theme?.background??'#fbf5ef'),color:String(valid.theme?.text??'#302927'),'--w-accent':String(valid.theme?.primary??'#d86f91'),'--w-surface':String(valid.theme?.surface??'#ffffff'),'--w-muted':String(valid.theme?.muted??'#81736d'),'--w-radius':String(valid.theme?.radius??24)+'px'} as CSSProperties}><div className={archiveRoot?'archive-canvas':'mx-auto max-w-2xl space-y-8'}>{valid.rootIds.map(render)}</div></div></AdoreFrame></ArchiveFrame></PageLayoutProvider>;
 if(!exactLivePreview)return page;const phone=valid.layout?.page==='hotline';return liveShell(page,archiveRoot?'os-archive-page':phone?'os-home os-hotline-page':'os-home',phone);
}
