'use client';
import {useContext,useEffect,useRef,useState} from 'react';
import {getAppItems,type AppItem,type PageDocument} from '@wiffeyyyy/content';
import {DocumentSettingsContext} from './page-layout';
import {emptyKissShopState,parseKissShopState,kissPrice,kissReceiptSvg,type KissShopState,type KissReceipt} from './kiss-shop-state';
const STORE='wiffeyyyy:kiss-shop:v1';
function GiftArt({item}:{item:AppItem}){
 const t=item.title.toLowerCase();const kind=/letter|listening/.test(t)?'letter':/hand|walk/.test(t)?'hand':/shawl/.test(t)?'shawl':/ride|passenger/.test(t)?'ride':/evening|film/.test(t)?'cup':/hug|minutes|reassurance/.test(t)?'heart':'gift';
 return <div className={'kiss-art kiss-art-'+kind}>{item.src?<img src={item.src} alt={item.alt||item.title} loading="lazy"/>:<svg viewBox="0 0 160 120" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path className="kiss-art-sparkle" d="m29 29 2 6 6 2-6 2-2 6-2-6-6-2 6-2zM126 69v9M122 73h8"/>{kind==='letter'?<><path d="m45 39 64-6 6 49-64 6z"/><path d="m45 40 36 22 28-28M51 86l22-29M115 81 90 54"/><path d="M82 58c-10-10-20 2 0 14 20-12 10-24 0-14z"/></>:kind==='hand'?<><path d="m39 85 29-15 24-3c9-1 13 9 2 13l-17 4M49 99l34-4 28-15c9-4 14 3 5 9L89 107H56"/><path d="M84 25c-14-15-28 3 0 21 28-18 14-36 0-21z"/></>:kind==='shawl'?<><path d="m58 21 39 6 20 68-44-8zM58 21 43 89l30-2M73 87v12M81 89v13M89 91v13M97 93v13M105 94v13M63 43l39 6M60 57l46 7M58 71l51 8"/><path d="M82 54c-6-7-13 2 0 10 13-8 6-17 0-10z"/></>:kind==='ride'?<><path d="M47 74h66l-8-31H59zM40 74v17h80V74M60 42l7-12h27l7 12M54 80h10M97 80h10"/><circle cx="58" cy="94" r="7"/><circle cx="105" cy="94" r="7"/><path d="M81 46c-9-10-18 2 0 13 18-11 9-23 0-13z"/></>:kind==='cup'?<><path d="M50 48h48v33c0 25-48 25-48 0zM98 55h8c20 0 15 24-8 24M44 102h67M62 33c-8-9 8-11 0-20M78 33c-8-9 8-11 0-20M76 63c-9-10-18 2 0 13 18-11 9-23 0-13z"/></>:kind==='heart'?<><path d="M80 49c-28-31-58 7 0 43 58-36 28-74 0-43z"/><path d="M49 94c17 10 45 10 62 0M77 26l3-9 3 9M38 53l-8-3M122 53l8-3"/></>:<><rect x="47" y="57" width="66" height="44" rx="3"/><path d="M43 47h74v12H43zM80 47v54M80 47c-36 0-31-33-13-23 8 4 13 23 13 23zM80 47c36 0 31-33 13-23-8 4-13 23-13 23z"/></>}</svg>}<span className="kiss-art-floor"/></div>;
}
function choices(item:AppItem){return /passenger|ride/i.test(item.title)?['Favourite snacks','Something sweet','Something savoury']: /date curator/i.test(item.title)?['A cozy café date','A sunset walk','Surprise me']: /evening|movie night/i.test(item.title)?['A comfort film','A romantic film','You choose the film']:[]}
export function KissShop({document,onSelect,selectedId,persist=false}:{document:PageDocument;onSelect?:(id:string)=>void;selectedId?:string;persist?:boolean}){
 const settings=useContext(DocumentSettingsContext),items=getAppItems(document,'shop'),ids=items.map(x=>x.id),signature=JSON.stringify(ids);
 const [state,setState]=useState<KissShopState>(emptyKissShopState),[ready,setReady]=useState(!persist),[warning,setWarning]=useState(false),[filter,setFilter]=useState('All'),[tab,setTab]=useState('Boutique'),[added,setAdded]=useState('');
 const [modal,setModal]=useState<'bag'|'detail'|'sealing'|'receipt'|null>(null),[product,setProduct]=useState<AppItem|null>(null),[choice,setChoice]=useState(''),[receipt,setReceipt]=useState<KissReceipt|null>(null),[closing,setClosing]=useState(false);
 const stateRef=useRef(state),dialog=useRef<HTMLDialogElement>(null),sealPending=useRef(false);
 useEffect(()=>{if(!persist)return;try{const saved=parseKissShopState(localStorage.getItem(STORE),JSON.parse(signature));stateRef.current=saved;setState(saved)}catch{setWarning(true)}setReady(true);const sync=(e:StorageEvent)=>{if(e.key===STORE||e.key===null){const saved=parseKissShopState(e.newValue,JSON.parse(signature));stateRef.current=saved;setState(saved)}};window.addEventListener('storage',sync);return()=>window.removeEventListener('storage',sync)},[persist,signature]);
 useEffect(()=>{if(modal&&!dialog.current?.open)dialog.current?.showModal();if(!modal)dialog.current?.close()},[modal]);
 useEffect(()=>{if(!closing)return;const timer=setTimeout(()=>{setModal(null);setClosing(false)},180);return()=>clearTimeout(timer)},[closing]);
 useEffect(()=>{if(modal!=='sealing')return;const timer=setTimeout(()=>{sealPending.current=false;setModal('receipt')},950);return()=>clearTimeout(timer)},[modal]);
 useEffect(()=>{if(!added)return;const timer=setTimeout(()=>setAdded(''),1800);return()=>clearTimeout(timer)},[added]);
 function commit(next:KissShopState){if(!ready||onSelect)return;stateRef.current=next;setState(next);if(persist)try{localStorage.setItem(STORE,JSON.stringify(next));setWarning(false)}catch{setWarning(true)}}
 const enabled=(item:AppItem)=>item.design?.available!==false&&item.design?.available!=='false'&&kissPrice(item.price)!==null;
 const bag=state.bag.flatMap(line=>{const item=items.find(x=>x.id===line.id);return item&&enabled(item)?[{...line,item}]:[]}),total=bag.reduce((n,l)=>n+(kissPrice(l.item.price)??0),0);
 function add(item:AppItem,selected=''){if(onSelect){onSelect(item.id);return}if(!ready||!enabled(item))return;const old=stateRef.current;const line={id:item.id,choice:selected||choices(item)[0]||''};commit({...old,bag:[...old.bag.filter(x=>x.id!==item.id),line]});setAdded(item.title);if(modal==='detail')setClosing(true)}
 function close(){if(modal==='sealing')return;setClosing(true)}
 function seal(){if(!bag.length||sealPending.current||!ready)return;sealPending.current=true;const order:KissReceipt={id:'KS-'+crypto.randomUUID().slice(0,8).toUpperCase(),createdAt:new Date().toISOString(),lines:bag.map(l=>({id:l.id,title:l.item.title,price:l.item.price,kisses:kissPrice(l.item.price)??0,choice:l.choice}))};commit({version:1,bag:[],receipts:[order,...stateRef.current.receipts].slice(0,50)});setReceipt(order);setModal('sealing')}
 function download(r:KissReceipt){const url=URL.createObjectURL(new Blob([kissReceiptSvg(r)],{type:'image/svg+xml'}));const a=window.document.createElement('a');a.href=url;a.download=r.id+'-kissshop.svg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const shown=items.filter(x=>x.category!=='Just because'&&(filter==='All'||x.category===filter)),free=items.filter(x=>x.category==='Just because');
 const categories=['All',...new Set(items.filter(x=>x.category!=='Just because').map(x=>x.category).filter(Boolean))];
 const details=(item:AppItem)=>{if(onSelect){onSelect(item.id);return}setProduct(item);setChoice(state.bag.find(x=>x.id===item.id)?.choice||choices(item)[0]||'');setModal('detail')};
 const card=(item:AppItem)=><article key={item.id} className="kiss-product" data-layout-node-id={item.id} style={selectedId===item.id?{outline:'3px solid #0a84ff'}:undefined}><button className="kiss-product-art" aria-label={onSelect?'Select '+item.title:'Details for '+item.title} onClick={()=>details(item)}><GiftArt item={item}/></button><div className="kiss-product-copy"><span className="kiss-price">{item.price}</span><h2>{item.title}</h2><p>{item.body}</p><button className={'kiss-add'+(state.bag.some(x=>x.id===item.id)?' is-added':'')} disabled={!onSelect&&(!ready||!enabled(item))} onClick={()=>add(item)} aria-label={(state.bag.some(x=>x.id===item.id)?'In bag: ':'Add to bag: ')+item.title}>{!enabled(item)?'Coming soon':state.bag.some(x=>x.id===item.id)?'In your bag ♡':'Add to bag +'} </button></div></article>;
 return <div className="kiss-shop"><header className="kiss-header"><a href="/home" aria-label="Return to home screen">‹ Home</a><span>KissShop<span className="kiss-logo-heart">♡</span></span><button disabled={!!onSelect||!ready} onClick={()=>setModal('bag')} aria-label={`Open shopping bag, ${bag.length} items`} className={added?'kiss-bag-bounce':''}><svg width="22" height="24" viewBox="0 0 24 26" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><path d="M4 8h16l2 16H2zM8 9V6a4 4 0 0 1 8 0v3"/></svg>{bag.length>0&&<b>{bag.length}</b>}</button></header>
 <nav className="kiss-main-tabs" aria-label="KissShop"><button aria-current={tab==='Boutique'?'page':undefined} onClick={()=>setTab('Boutique')}>The boutique</button><button aria-current={tab==='Plans'?'page':undefined} onClick={()=>setTab('Plans')}>Our little plans <span>{state.receipts.length||''}</span></button></nav>
 <div className="kiss-scroll">{tab==='Boutique'?<><section className="kiss-hero"><span className="kiss-hero-eyebrow">LITTLE TREATS. BIG FEELINGS.</span><h1>Made for you.<br/>Paid in kisses.</h1><p>A cozy little shop for my {settings.nickname==='favourite person'?'favourite person':settings.nickname}.</p><span className="kiss-hero-signature">With love, always. ♡</span><div className="kiss-hero-decoration" aria-hidden="true">♡<i>✧</i></div></section><div className="kiss-shelf-heading"><h2>Pick a little happiness</h2><span>{items.filter(x=>x.category!=='Just because').length} treats</span></div><div className="kiss-categories" aria-label="Gift categories">{categories.map(c=><button key={c} aria-pressed={filter===c} onClick={()=>setFilter(c)}>{c}</button>)}</div><div className="kiss-products">{shown.map(card)}</div>{!shown.length&&<p className="kiss-empty">A little something is on its way.</p>}{free.length>0&&<section className="kiss-just-because"><span>ON THE HOUSE, ALWAYS</span><h2>Just because you’re you.</h2><p>Hugs, reassurance, and a listening ear.<br/>These never need to be earned.</p><div>{free.map(item=><button key={item.id} disabled={!onSelect&&!ready} data-layout-node-id={item.id} onClick={()=>add(item)} aria-label={'Add to bag: '+item.title}><span aria-hidden="true">♡</span><div><strong>{item.title}</strong><small>{item.body}</small></div><span>{state.bag.some(x=>x.id===item.id)?'✓':'+'}</span></button>)}</div></section>}<p className="kiss-footnote">The prices are playful. The promises are real.<br/>No expiry dates. Just us.</p></>:<section className="kiss-plans"><span className="kiss-hero-eyebrow">SOMETHING TO LOOK FORWARD TO</span><h1>Our little plans.</h1><p>Little promises, ready for when we meet.</p>{state.receipts.length?state.receipts.map(r=><button key={r.id} className="kiss-order-card" onClick={()=>{setReceipt(r);setModal('receipt')}}><span className="kiss-order-heart" aria-hidden="true">♡</span><div><strong>{r.lines.length} little {r.lines.length===1?'promise':'promises'}</strong><small>{new Date(r.createdAt).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})} · {r.id}</small><p>{r.lines.map(l=>l.title).join(' · ')}</p></div><span aria-hidden="true">↗</span></button>):<div className="kiss-plans-empty"><span aria-hidden="true">♡</span><h2>Good things are waiting.</h2><p>Your receipts will stay here after checkout.</p><button onClick={()=>setTab('Boutique')}>Explore the boutique →</button></div>}<p className="kiss-footnote">Saved in this browser. Show me your receipt<br/>and we’ll make it happen together.</p></section>}{warning&&<p role="alert" className="kiss-warning">Your browser couldn’t save this. Use “Save receipt” to keep a copy.</p>}</div>
 {tab==='Boutique'&&<div className="kiss-bag-dock"><div><small>YOUR LITTLE BAG</small><strong>{bag.length?`${bag.length} ${bag.length===1?'treat':'treats'} · ${total} ${total===1?'kiss':'kisses'}`:'A little room for happiness'}</strong></div><button disabled={!ready||!!onSelect} onClick={()=>setModal('bag')}>View bag <span aria-hidden="true">→</span></button></div>}<a className="kiss-home-indicator" href="/home" aria-label="Return to home screen"/>
 <div className={'kiss-added-toast'+(added?' is-visible':'')} role="status">{added&&<>♡ {added} added to your bag</>}</div>
 <dialog ref={dialog} className="kiss-dialog" data-closing={closing||undefined} aria-label={modal==='detail'?'Gift details':modal==='bag'?'Your shopping bag':'Your gift receipt'} onCancel={e=>{e.preventDefault();close()}} onClick={e=>{if(e.target===e.currentTarget)close()}} onClose={()=>{setModal(null);setClosing(false)}}><header><span>{modal==='detail'?'A LITTLE SOMETHING':modal==='bag'?'YOUR LITTLE BAG':'SEALED WITH LOVE'}</span><button aria-label="Close shop window" disabled={modal==='sealing'} onClick={close}>×</button></header>
 {modal==='detail'&&product&&<div className="kiss-detail"><GiftArt item={product}/><span className="kiss-price">{product.price}</span><h2>{product.title}</h2><p>{product.body}</p>{choices(product).length>0&&<label>A little detail, just for you<select value={choice} onChange={e=>setChoice(e.target.value)}>{choices(product).map(c=><option key={c}>{c}</option>)}</select></label>}<button className="kiss-primary" disabled={!ready||!enabled(product)} onClick={()=>add(product,choice)}>{state.bag.some(x=>x.id===product.id)?'Update your bag':'Add to your bag'} <span>♡</span></button></div>}
 {modal==='bag'&&<div className="kiss-bag"><h2>A bag full of<br/>little promises.</h2>{bag.length?<><div className="kiss-bag-lines">{bag.map(l=><div key={l.id} className="kiss-bag-line"><GiftArt item={l.item}/><div><h3>{l.item.title}</h3><span className="kiss-price">{l.item.price}</span>{choices(l.item).length>0&&<label><span className="kiss-sr">Choose details for {l.item.title}</span><select value={l.choice} onChange={e=>commit({...stateRef.current,bag:stateRef.current.bag.map(x=>x.id===l.id?{...x,choice:e.target.value}:x)})}>{choices(l.item).map(c=><option key={c}>{c}</option>)}</select></label>}<button className="kiss-remove" aria-label={'Remove '+l.item.title+' from bag'} onClick={()=>commit({...stateRef.current,bag:stateRef.current.bag.filter(x=>x.id!==l.id)})}>Remove</button></div></div>)}</div><div className="kiss-total"><span>Total, in affection</span><strong>{total} {total===1?'kiss':'kisses'} ♡</strong></div><p className="kiss-bag-note">No payment needed. Just a little promise<br/>for the next time we’re together.</p><button className="kiss-primary" onClick={seal}>Seal with a kiss <span>♡</span></button></>:<div className="kiss-empty-bag"><span aria-hidden="true">♡</span><p>Your bag is waiting for something lovely.</p><button className="kiss-primary" onClick={close}>Keep browsing →</button></div>}</div>}
 {modal==='sealing'&&<div className="kiss-wrap-scene" role="status" onAnimationEnd={e=>{if(e.target===e.currentTarget){sealPending.current=false;setModal('receipt')}}}><div className="kiss-wrapped-gift"><div className="kiss-gift-lid"/><div className="kiss-gift-ribbon"/><span>♡</span></div><div className="kiss-flying-hearts" aria-hidden="true"><i>♡</i><i>♡</i><i>✧</i></div><h2>Wrapped with love.</h2><p>Your little promises are being sealed…</p></div>}
 {modal==='receipt'&&receipt&&<div className="kiss-receipt"><div className="kiss-receipt-brand">KissShop ♡</div><p className="kiss-receipt-eyebrow">A LITTLE PROMISE, JUST FOR YOU</p><span className="kiss-receipt-number">{receipt.id} · {new Date(receipt.createdAt).toLocaleDateString()}</span><div className="kiss-receipt-lines">{receipt.lines.map((l,i)=><div key={l.id+i}><span><strong>{l.title}</strong>{l.choice&&<small>{l.choice}</small>}</span><span>{l.price}</span></div>)}</div><div className="kiss-total"><span>Total</span><strong>{receipt.lines.reduce((n,l)=>n+l.kisses,0)} kisses ♡</strong></div><div className="kiss-receipt-stamp">SEALED<br/><span>♡</span><br/>WITH A KISS</div><p className="kiss-receipt-message">Your order includes one boyfriend<br/>who’s very excited to see you.</p><p className="kiss-bag-note">{warning?'Save a copy to keep this receipt.':'Saved on this device. Show me when we meet.'}<br/>No expiry date. Just us.</p><button className="kiss-primary" onClick={()=>download(receipt)}>Save receipt <span>↓</span></button><button className="kiss-secondary" onClick={()=>{setTab('Plans');close()}}>See our little plans →</button></div>}
 </dialog></div>;
}
