'use client';
import {useEffect,useRef,useState} from 'react';
type Call={role:'caller'|'receiver';callId:string|null;state:'idle'|'ringing'|'connected'|'ended';offer?:RTCSessionDescriptionInit;answer?:RTCSessionDescriptionInit;receiverOnline:boolean;iceServers:RTCIceServer[];relayReady:boolean};
export function LiveHotline({receiver=false,title='Priority line to your future husband',name='Your future husband',callLabel='Call your future husband',preview=false}:{receiver?:boolean;title?:string;name?:string;callLabel?:string;preview?:boolean}){
 const [token,setToken]=useState(''),[call,setCall]=useState<Call|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[muted,setMuted]=useState(false),[connected,setConnected]=useState(false),[seconds,setSeconds]=useState(0),[listening,setListening]=useState(false),[playRequired,setPlayRequired]=useState(false);
 const audio=useRef<HTMLAudioElement>(null),peer=useRef<RTCPeerConnection|null>(null),stream=useRef<MediaStream|null>(null),current=useRef<Call|null>(null),session=useRef(0),alive=useRef(true),ctx=useRef<AudioContext|null>(null),negotiating=useRef(false);
 const cleanup=()=>{session.current++;peer.current?.close();peer.current=null;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(audio.current)audio.current.srcObject=null;setConnected(false);setMuted(false);setSeconds(0);setPlayRequired(false)};
 const rpc=async(action:string,payload:Record<string,unknown>={})=>{const r=await fetch('/api/hotline',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,action,payload}),cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);return d as Call};
 const apply=async(d:Call)=>{if(!alive.current)return;const old=current.current;current.current=d;setCall(d);if(old?.callId&&old.callId!==d.callId&&peer.current)cleanup();if(d.state==='ended'||d.state==='idle'){if(peer.current)cleanup();return;}if(d.role==='caller'&&d.answer&&peer.current&&!peer.current.remoteDescription){try{await peer.current.setRemoteDescription(d.answer)}catch{setError('Could not connect the audio. End the call and try again.')}}};
 useEffect(()=>{alive.current=true;if(preview)return()=>{alive.current=false};const key=new URLSearchParams(location.hash.slice(1)).get('key');const slot=receiver?'hotline-receiver':'hotline-caller';if(key&&/^[a-f0-9]{64}$/.test(key)){setToken(key);try{sessionStorage.setItem(slot,key)}catch{}history.replaceState(null,'',location.pathname+location.search);}else{try{setToken(sessionStorage.getItem(slot)||'')}catch{}}return()=>{alive.current=false;session.current++;peer.current?.close();stream.current?.getTracks().forEach(t=>t.stop());ctx.current?.close()};},[receiver,preview]);
 useEffect(()=>{if(!token)return;let disposed=false,polling=false;const poll=async()=>{if(polling||disposed||negotiating.current)return;polling=true;try{const d=await rpc(connected?'connected':'status',connected?{callId:current.current?.callId}:{});if(!disposed)await apply(d)}catch(e){if(!disposed){setError((e as Error).message);if((e as Error).message.includes('revoked'))cleanup()}}finally{polling=false}};void poll();const timer=setInterval(poll,2000);return()=>{disposed=true;clearInterval(timer)};},[token,connected]);
 useEffect(()=>{if(!token)return;const leave=()=>{const c=current.current;if(peer.current&&c?.callId){void fetch('/api/hotline',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,action:'end',payload:{callId:c.callId}}),keepalive:true}).catch(()=>{});stream.current?.getTracks().forEach(t=>t.stop());peer.current?.close();}};window.addEventListener('pagehide',leave);return()=>{window.removeEventListener('pagehide',leave);leave()}},[token]);
 useEffect(()=>{if(!connected)return;const started=Date.now();const timer=setInterval(()=>setSeconds(Math.floor((Date.now()-started)/1000)),1000);return()=>clearInterval(timer)},[connected]);
 useEffect(()=>{if(!listening||call?.state!=='ringing'||call.role!=='receiver')return;const ring=()=>{const c=ctx.current;if(!c||c.state!=='running')return;const o=c.createOscillator(),g=c.createGain();o.frequency.value=660;g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.6);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.6)};ring();const id=setInterval(ring,1800);return()=>clearInterval(id)},[listening,call?.state,call?.role]);
 async function prepare(){cleanup();const version=session.current;const media=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});if(version!==session.current||!alive.current){media.getTracks().forEach(t=>t.stop());throw Error('Call cancelled')}stream.current=media;const pc=new RTCPeerConnection({iceServers:current.current?.iceServers??[]});peer.current=pc;media.getTracks().forEach(t=>pc.addTrack(t,media));pc.ontrack=e=>{if(audio.current){audio.current.srcObject=e.streams[0]??new MediaStream([e.track]);audio.current.play().catch(()=>setPlayRequired(true))}};pc.onconnectionstatechange=()=>{if(peer.current!==pc)return;if(pc.connectionState==='connected'){setConnected(true);setError('')}else if(pc.connectionState==='failed'){setError('Audio connection failed. A relay server may be needed for this network.');void finish()}else if(pc.connectionState==='disconnected'){setError('Connection interrupted. Trying to reconnect…')}};return pc}
 async function gather(pc:RTCPeerConnection){if(pc.iceGatheringState==='complete')return;await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>{pc.removeEventListener('icegatheringstatechange',check);reject(Error('Network setup timed out. Try again.'))},15000);const check=()=>{if(pc.iceGatheringState==='complete'){clearTimeout(timer);pc.removeEventListener('icegatheringstatechange',check);resolve()}};pc.addEventListener('icegatheringstatechange',check);check()});}
 async function start(){negotiating.current=true;setBusy(true);setError('');try{const pc=await prepare();await pc.setLocalDescription(await pc.createOffer());await gather(pc);if(peer.current!==pc||!alive.current)throw Error('Call cancelled');await apply(await rpc('start',{offer:pc.localDescription?.toJSON()}));}catch(e){cleanup();setError((e as Error).message==='Permission denied'?'Allow microphone access to make a call.':(e as Error).message)}finally{negotiating.current=false;setBusy(false)}}
 async function answer(){const ringing=current.current;if(!ringing?.offer)return;negotiating.current=true;setBusy(true);setError('');try{const pc=await prepare();await pc.setRemoteDescription(ringing.offer);await pc.setLocalDescription(await pc.createAnswer());await gather(pc);if(peer.current!==pc||!alive.current)throw Error('Call cancelled');await apply(await rpc('answer',{callId:ringing.callId,answer:pc.localDescription?.toJSON()}));}catch(e){cleanup();setError((e as Error).message)}finally{negotiating.current=false;setBusy(false)}}
 async function finish(){const id=current.current?.callId;cleanup();if(id)try{await apply(await rpc('end',{callId:id}))}catch(e){setError((e as Error).message)}}
 const role=call?.role,wrongRole=!!role&&receiver!==(role==='receiver'),active=call?.state==='ringing'||call?.state==='connected';
 return <section className="live-hotline" aria-label="Private live Hotline"><p className="live-hotline-eyebrow">{receiver?'Your private receiver':'Wiffeyyyy priority line'}</p><div className="live-hotline-avatar" aria-hidden="true">{receiver?'💗':'☎️'}</div><h1>{receiver?'A direct line from her':title}</h1><p className="live-hotline-name">{receiver?'Only her private link can call you':name}</p><audio ref={audio} autoPlay playsInline/><p className="live-hotline-status" role="status">{preview?'Private audio-call screen':!token?'Open your private link to use this line.':wrongRole?'This link belongs to the other screen.':!call?'Checking your private line…':connected?`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')} · Connected`:call.state==='ringing'?(role==='receiver'?'Incoming call from her…':'Calling your future husband…'):call.state==='connected'?'Connecting your audio…':call.state==='ended'?'Call ended':role==='receiver'?'Ready to receive her call':call.receiverOnline?'He is online · your line is ready':'Your private line is ready'}</p>{preview&&<div className="live-hotline-controls"><button className="live-call-answer" disabled>{callLabel}</button></div>}{error&&<p role="alert" className="live-hotline-error">{error}</p>}{token&&call&&!wrongRole&&<div className="live-hotline-controls">{role==='receiver'&&!listening&&<button onClick={async()=>{ctx.current??=new AudioContext();await ctx.current.resume();setListening(true)}}>Enable incoming ringtone</button>}{!active&&role==='caller'&&<button className="live-call-answer" disabled={busy} onClick={start}>{busy?'Preparing microphone…':callLabel}</button>}{call.state==='ringing'&&role==='receiver'&&<button className="live-call-answer" disabled={busy} onClick={answer}>{busy?'Connecting…':'Answer'}</button>}{active&&<button className="live-call-end" onClick={finish}>{role==='receiver'&&call.state==='ringing'?'Decline':'End call'}</button>}{connected&&<button aria-pressed={muted} onClick={()=>{stream.current?.getAudioTracks().forEach(t=>t.enabled=muted);setMuted(!muted)}}>{muted?'Unmute':'Mute'}</button>}{playRequired&&<button onClick={()=>audio.current?.play().then(()=>setPlayRequired(false)).catch(()=>setError('Tap again to allow call audio.'))}>Play call audio</button>}</div>}{role==='receiver'&&<p className="live-hotline-note">Keep this page open to receive browser calls. Background ringing requires the Android receiver APK and push setup.</p>}</section>;
}
