'use client';
import {createContext,useContext,useEffect,useRef,useState,type ReactNode,type PointerEvent} from 'react';
export type PhoneNotification={id:string;title:string;body:string;href:string;icon:string};
const Access=createContext<{show:()=>void;count:number;isOpen:boolean}|null>(null);
export const useNotificationShade=()=>useContext(Access)?.show??null;
export const useNotificationExpanded=()=>useContext(Access)?.isOpen;
export const useNotificationCount=()=>useContext(Access)?.count;
export function NotificationShade({children,notifications,app=false,reducedMotion=false,title='Notifications',emptyMessage='All caught up. ♡',background,enabled=true,duration=320,swipeThreshold=70,siteTitle='Wiffeyyyy OS',persist=true,editorNodeId}:{children:ReactNode;notifications:PhoneNotification[];app?:boolean;reducedMotion?:boolean;title?:string;emptyMessage?:string;background?:string;enabled?:boolean;duration?:number;swipeThreshold?:number;siteTitle?:string;persist?:boolean;editorNodeId?:string}){
 const [open,setOpen]=useState(false),[dismissed,setDismissed]=useState<string[]>([]),[ready,setReady]=useState(false),[shadeMotion,setShadeMotion]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null),animation=useRef<Animation|null>(null),trigger=useRef<HTMLButtonElement>(null),gesture=useRef<{x:number;y:number;t:number;scroll:number;scroller:HTMLElement|null}|null>(null),dragged=useRef(false),opening=useRef<{x:number;y:number}|null>(null);
 useEffect(()=>{if(!persist){setReady(true);return}try{const saved=JSON.parse(localStorage.getItem('wiffeyyyy:phone-home')??'{}');setShadeMotion(saved.reduceMotion===true);if(Array.isArray(saved.dismissed))setDismissed(saved.dismissed.filter((id:unknown)=>typeof id==='string'))}catch{}setReady(true)},[persist]);
 useEffect(()=>{if(!enabled)setOpen(false)},[enabled]);
 useEffect(()=>{if(!ready||!persist)return;try{const saved=JSON.parse(localStorage.getItem('wiffeyyyy:phone-home')??'{}');localStorage.setItem('wiffeyyyy:phone-home',JSON.stringify({...saved,version:1,dismissed:dismissed.slice(-500),reduceMotion:shadeMotion}))}catch{}},[dismissed,ready,shadeMotion,persist]);
 useEffect(()=>{const el=dialog.current;if(!el)return;animation.current?.cancel();const motion=reducedMotion||shadeMotion||window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  if(open){const start=el.open?getComputedStyle(el).transform:'translateY(-110%)';if(!el.open)el.showModal();el.style.removeProperty('--shade-drag');animation.current=el.animate([{transform:start==='none'?'translateY(-110%)':start,opacity:.7},{transform:'translateY(0)',opacity:1}],{duration:motion?0:duration,easing:'cubic-bezier(.22,1,.36,1)',fill:'forwards'});}
  else if(el.open){const start=getComputedStyle(el).transform;el.style.removeProperty('--shade-drag');const anim=el.animate([{transform:start,opacity:1},{transform:'translateY(-110%)',opacity:.7}],{duration:motion?0:duration*.8125,easing:'cubic-bezier(.4,0,.2,1)',fill:'forwards'});animation.current=anim;anim.finished.then(()=>{if(animation.current===anim){el.close();anim.cancel();trigger.current?.focus({preventScroll:true})}}).catch(()=>{});}
  return()=>animation.current?.cancel();
 },[open,reducedMotion,shadeMotion,duration]);
 const start=(e:PointerEvent<HTMLDialogElement>)=>{if(e.button!==0)return;const scroller=(e.target as HTMLElement).closest<HTMLElement>('.phone-notifications');gesture.current={x:e.clientX,y:e.clientY,t:performance.now(),scroll:scroller?.scrollTop??0,scroller};dragged.current=false};
 const move=(e:PointerEvent<HTMLDialogElement>)=>{const g=gesture.current;if(!g)return;const dx=e.clientX-g.x,dy=e.clientY-g.y;if(Math.abs(dy)<8||Math.abs(dy)<Math.abs(dx)*1.2)return;
  if(g.scroller&&g.scroller.scrollHeight>g.scroller.clientHeight+1&&!(dy<0&&g.scroll>=g.scroller.scrollHeight-g.scroller.clientHeight-1)){g.scroller.scrollTop=g.scroll-dy;dragged.current=true;return;}
  if(dy>=0)return;animation.current?.cancel();dragged.current=true;e.currentTarget.setPointerCapture(e.pointerId);e.currentTarget.style.setProperty('--shade-drag',dy+'px');e.currentTarget.dataset.dragging='true';};
 const end=(e:PointerEvent<HTMLDialogElement>)=>{const g=gesture.current;gesture.current=null;e.currentTarget.removeAttribute('data-dragging');if(!g)return;const dy=e.clientY-g.y,dx=e.clientX-g.x,elapsed=performance.now()-g.t;const wasDrag=!!e.currentTarget.style.getPropertyValue('--shade-drag');if(wasDrag&&Math.abs(dx)<Math.abs(dy)&&(-dy>swipeThreshold||(-dy>swipeThreshold*.36&&-dy/Math.max(1,elapsed)>.35)))setOpen(false);else{e.currentTarget.style.removeProperty('--shade-drag');if(wasDrag){const anim=e.currentTarget.animate([{transform:`translateY(${Math.min(0,dy)}px)`},{transform:'translateY(0)'}],{duration:reducedMotion||shadeMotion?0:220,easing:'ease-out'});animation.current=anim;}}};
 const active=notifications.filter(n=>!dismissed.includes(n.id));
 return <Access.Provider value={enabled?{show:()=>setOpen(true),count:active.length,isOpen:open}:null}>{children}{enabled&&app&&<button ref={trigger} className="os-shade-trigger" aria-label={`Open notification shade, ${active.length} notifications`} aria-expanded={open} onClick={()=>setOpen(true)} onPointerDown={e=>{opening.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerUp={e=>{const g=opening.current;opening.current=null;if(g&&e.clientY-g.y>25&&Math.abs(e.clientX-g.x)<100)setOpen(true)}} onPointerCancel={()=>{opening.current=null}}/>}{enabled&&<dialog data-phone-node={editorNodeId} ref={dialog} className="phone-shade os-universal-shade" style={background&&background!=='transparent'?{background}:undefined} aria-labelledby="universal-notifications-title" onCancel={e=>{e.preventDefault();setOpen(false)}} onPointerDown={start} onPointerMove={move} onPointerUp={end} onPointerCancel={()=>{gesture.current=null;dialog.current?.style.removeProperty('--shade-drag');dialog.current?.removeAttribute('data-dragging')}} onClickCapture={e=>{if(dragged.current){e.preventDefault();e.stopPropagation();dragged.current=false}}}><div className="phone-shade-handle"><span/></div><header className="phone-shade-heading"><div><p>{siteTitle}</p><h2 id="universal-notifications-title">{title}</h2></div><button className="phone-round-button" aria-label="Close notification shade" onClick={()=>setOpen(false)}>×</button></header><div className="phone-quick-settings"><button aria-pressed={shadeMotion||reducedMotion} onClick={()=>setShadeMotion(old=>!old)}>Reduce motion</button></div><div className="phone-notifications">{active.map(n=><article data-phone-node={editorNodeId?n.id:undefined} className="phone-notification" key={n.id}><span className="phone-notification-icon" aria-hidden="true">{n.icon}</span><a href={n.href}><span className="phone-notification-source">Birthday inbox</span><h3>{n.title}</h3><p>{n.body}</p></a><button aria-label={'Dismiss '+n.title} onClick={()=>setDismissed(old=>[...old,n.id])}>×</button></article>)}{!active.length&&<p className="phone-inbox-empty">{emptyMessage}</p>}</div>{active.length>0&&<button className="phone-clear" onClick={()=>setDismissed(notifications.map(n=>n.id))}>Clear all</button>}<button className="phone-shade-close" aria-label="Close notification shade" onClick={()=>setOpen(false)}><span className="phone-shade-home-indicator"/><span className="phone-close-hint">Swipe up to close</span></button></dialog>}</Access.Provider>;
}
