'use client';
import {useEffect,useRef,useState,type CSSProperties,type ReactNode} from 'react';
import {resolveOsSettings,fitPhone,type SiteDocument} from '@wiffeyyyy/content';
export function OsSettingsSurface({settings,children,preview=false,reducedMotion=false}:{settings:SiteDocument;children:ReactNode;preview?:boolean;reducedMotion?:boolean}){
 const os=resolveOsSettings(settings),host=useRef<HTMLDivElement>(null),[viewport,setViewport]=useState({width:430,height:900});
 useEffect(()=>{const element=host.current;if(!element)return;const resize=()=>setViewport({width:element.clientWidth,height:element.clientHeight});resize();const observer=new ResizeObserver(resize);observer.observe(element);return()=>observer.disconnect()},[]);
 const fit=fitPhone(os,viewport.width,viewport.height),motion=reducedMotion||os.reducedMotion||!os.motionEnabled;
 const style={'--phone-width':os.width-os.frameWidth*2+'px','--os-height':os.height+'px','--phone-height':os.height+'px','--phone-corner':Math.max(0,os.frameRadius-os.frameWidth)+'px','--phone-fit-top':fit.top/fit.scale+os.frameWidth+'px','--phone-scale':fit.scale,'--os-width':os.width+'px','--os-frame':os.frameWidth+'px','--os-frame-radius':os.frameRadius+'px','--os-frame-color':os.frameColor,'--os-shadow':os.shadow,'--os-brightness':os.brightness,'--os-opacity':os.surfaceOpacity,'--os-blur':os.blur+'px','--os-icon-size':os.iconSize+'px','--os-icon-radius':os.iconRadius+'px','--os-icon-gap':os.iconGap+'px','--os-font-scale':os.fontScale,'--os-dock-opacity':os.dockOpacity,'--os-dock-blur':os.dockBlur+'px','--os-dock-radius':os.dockRadius+'px','--os-dock-gap':os.dockSpacing+'px','--w-accent':settings.accent,'--w-surface':settings.surface,'--w-text':settings.text,'--w-radius':settings.radius+'px',color:settings.text} as CSSProperties;
 return <div ref={host} className={'os-settings-viewport'+(preview?' os-settings-preview':'')} style={{background:settings.background,alignItems:os.position==='top'?'flex-start':'center',padding:os.viewportPadding}}><div className="birthday-os birthday-os-phone os-settings-screen os-configured" style={style} data-color-mode={os.colorMode} data-reduced-motion={motion?'true':undefined} data-status-visible={os.statusVisible} data-dock-visible={os.dockVisible} data-icon-labels={os.showIconLabels}>{children}</div></div>;
}
