'use client';
import {LiveHotline} from './live-hotline';
import {createContext,useContext,useState,useEffect,type ReactNode,type CSSProperties} from 'react';
import {defaultSiteDocument,parseLayoutProgress,getPublicApp,type SiteDocument,type PageDocument,type CMSNode} from '@wiffeyyyy/content';
import {MediaPlayer} from './media-player';
import {HomeNavigation,useSiteNavigation} from './navigation';
export const DocumentSettingsContext=createContext(defaultSiteDocument);
export function DocumentSettingsProvider({value,children}:{value:SiteDocument;children:ReactNode}){return <DocumentSettingsContext.Provider value={value}>{children}</DocumentSettingsContext.Provider>;}
const card='rounded-[var(--section-radius,24px)] border border-[var(--w-accent)]/20 bg-[var(--w-surface)] p-5';
const button='min-h-11 rounded-2xl border px-4 py-3 text-sm font-semibold disabled:opacity-40';
const primary=button+' bg-[var(--w-accent)] text-white';
const muted='text-sm leading-7 opacity-70';
export const nodeStyle=(node:CMSNode):CSSProperties=>{const p=node.props;return {background:p.background as string|undefined,color:p.color as string|undefined,padding:p.padding as number|undefined,margin:p.margin as number|undefined,borderRadius:p.radius as number|undefined,opacity:p.opacity as number|undefined,fontSize:p.size as number|undefined,fontWeight:p.weight as number|undefined,textAlign:p.align as CSSProperties['textAlign']}};
const str=(node:CMSNode|undefined,key:string,fallback='')=>String(node?.props[key]??fallback);
const xml=(value:string)=>value.replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[x]!));
export function giftReceiptSvg(gifts:CMSNode[],title:string,note:string){const lines=[title,...gifts.map(n=>str(n,'title')),note].flatMap(line=>line.match(/.{1,44}(?:\s|$)|.{1,44}/g)??[]);return `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="${140+lines.length*36}" viewBox="0 0 600 ${140+lines.length*36}"><rect width="100%" height="100%" rx="28" fill="#fbf5ef"/><text x="40" y="45" font-family="sans-serif" font-size="16" fill="#a9476b">Wiffeyyyy OS · Gift receipt</text>${lines.map((line,i)=>`<text x="40" y="${100+i*36}" font-family="sans-serif" font-size="20" fill="#403532">${xml(line)}</text>`).join('')}</svg>`;}
type State={recent:string;document:PageDocument;editing:boolean;selectedId?:string;settings:SiteDocument;selections:Record<string,string>;choose:(group:string,id:string)=>void;answered:boolean;answer:(value:boolean)=>void;reveal:boolean;show:(value:boolean)=>void;bag:string[];setBag:(value:string[])=>void;receipt:CMSNode[];checkout:()=>void;favorites:string[];favorite:(id:string)=>void};
const Context=createContext<State|null>(null);
export function PageLayoutProvider({document,editing,selectedId,children,persist=false}:{document:PageDocument;editing:boolean;selectedId?:string;children:ReactNode;persist?:boolean}){
 const settings=useContext(DocumentSettingsContext);
 const [selections,setSelections]=useState<Record<string,string>>({}),[answered,answer]=useState(false),[reveal,show]=useState(false),[bag,setBag]=useState<string[]>([]),[receipt,setReceipt]=useState<CMSNode[]>([]),[favorites,setFavorites]=useState<string[]>([]);
 const [recent,setRecent]=useState('');
 useEffect(()=>{if(!persist)return;try{setRecent(localStorage.getItem('wiffeyyyy:recent-app:v1')??'');if(getPublicApp(document.layout?.page??''))localStorage.setItem('wiffeyyyy:recent-app:v1',document.layout!.page)}catch{}},[persist,document.layout?.page]);
 const [ready,setReady]=useState(!persist),[storageWarning,setStorageWarning]=useState(false);
 const storageKey='wiffeyyyy:layout:v1:'+String(document.layout?.page??'custom');
 useEffect(()=>{if(!persist)return;try{const saved=parseLayoutProgress(localStorage.getItem(storageKey),document);setSelections(saved.selections);setBag(saved.bag);setFavorites(saved.favorites);setReceipt(document.nodes.filter(n=>saved.receipt.includes(n.id)))}catch{setStorageWarning(true)}setReady(true)},[persist,storageKey]);
 useEffect(()=>{if(!persist||!ready)return;try{localStorage.setItem(storageKey,JSON.stringify({version:1,selections,bag,favorites,receipt:receipt.map(n=>n.id)}))}catch{setStorageWarning(true)}},[persist,ready,storageKey,selections,bag,favorites,receipt]);
 const value:State={recent,document,editing:editing||!ready,selectedId,settings,selections,choose:(group,id)=>setSelections(old=>({...old,[group]:id})),answered,answer,reveal,show,bag,setBag,receipt,checkout:()=>{setReceipt(document.nodes.filter(n=>bag.includes(n.id)&&n.visible&&n.props.available!==false&&n.props.available!=='false'));setBag([])},favorites,favorite:id=>setFavorites(old=>old.includes(id)?old.filter(x=>x!==id):[...old,id])};
 return <Context.Provider value={value}>{children}{storageWarning&&<p role="status" className="mt-4 text-xs">Your browser cannot save progress. Download gift receipts to keep them.</p>}</Context.Provider>;
}
function Photo({node,icon='♡'}:{node:CMSNode;icon?:string}){const [failed,setFailed]=useState(false);return node.props.src&&!failed?<img src={str(node,'src')} alt={str(node,'alt')} onError={()=>setFailed(true)} loading="lazy" decoding="async" className="mb-4 aspect-[4/3] w-full rounded-2xl object-cover"/>:<div aria-hidden="true" className="mb-4 grid aspect-[4/3] place-items-center rounded-2xl bg-gradient-to-br from-rose-100 to-orange-50 text-5xl text-[var(--w-accent)]">{icon}</div>}
function Recording({node,kind,disabled}:{node:CMSNode;kind:'audio'|'video';disabled:boolean}){return node.props.src?<MediaPlayer identity={'layout:'+node.id} src={str(node,'src')} kind={kind} title={str(node,'title',str(node,'alt'))} captions={str(node,'captions')} disabled={disabled} className="w-full rounded-2xl"/>:<div className="rounded-2xl bg-gradient-to-br from-rose-100 to-orange-50 p-6"><p aria-hidden="true" className="mb-3 text-4xl">{kind==='video'?'🎬':'♫'}</p><p className={muted}>{kind==='video'?'Your movie goes here. The story is ready to personalise below.':'A place for your recording. The message is available to read.'}</p></div>}
export function LayoutSection({node,children:blocks}:{node:CMSNode;children:CMSNode[]}){
 const state=useContext(Context)!;const [savedOnly,setSavedOnly]=useState(false);const navigation=useSiteNavigation();const p=node.props,kind=str(node,'sectionKind'),{editing}=state;
 const mark=(block:CMSNode,content:ReactNode)=><div key={block.id} data-layout-node-id={block.id} style={{...nodeStyle(block),outline:state.selectedId===block.id?'2px solid var(--w-accent)':undefined}} tabIndex={editing?0:undefined} role={editing?'button':undefined} aria-label={editing?'Select '+(block.label??block.component):undefined}>{content}</div>;
 const Heading=kind==='welcome-hero'||kind==='birthday-heading'?'h1':'h2';
 const copy=(block:CMSNode)=>mark(block,block.component==='heading'?<Heading style={{fontSize:block.props.size as number|undefined,fontWeight:block.props.weight as number|undefined}} className="font-serif text-3xl leading-tight">{state.document.layout?.page==='reasons'&&['Reasons I’m Obsessed','Reasons I Love You'].includes(str(block,'text'))?'Adore':str(block,'text')}</Heading>:<p style={{fontSize:block.props.size as number|undefined}} className={muted+' whitespace-pre-line'}>{block.props.binding==='nickname'?state.settings.nickname:str(block,'text')}</p>);
 const all=(component:string)=>{const byId=new Map(state.document.nodes.map(n=>[n.id,n]));const found:CMSNode[]=[];const visit=(id:string)=>{const n=byId.get(id);if(!n?.visible)return;if(n.component===component)found.push(n);n.children.forEach(visit)};state.document.rootIds.forEach(visit);return found};
 const active=(items:CMSNode[],group:string)=>items.find(n=>n.id===state.selectedId)??items.find(n=>n.id===state.selections[group])??items[0];
 const playback=(item:CMSNode|undefined,media:'audio'|'video',enabled=true)=>item?mark(item,<><h3 className="mb-4 font-serif text-2xl">{str(item,'title')}</h3>{enabled&&(item.props.mediaKind==='image'?<Photo node={item} icon="🎬"/>:<Recording key={item.id+str(item,'src')} node={item} kind={media} disabled={editing}/>)}<p className={muted+' mt-4 whitespace-pre-line'}>{str(item,'body')}</p></>):<p className={muted}>Add a {media==='audio'?'message':'scene'} in this section.</p>;
 if(['startup-greeting','keepsake-note','intro','movie-credits','birthday-ending','redemption-note','text-versions','birthday-heading'].includes(kind))return <section className={kind==='startup-greeting'?'text-xs uppercase tracking-widest text-[var(--w-accent)]':'space-y-3'}>{blocks.map(copy)}</section>;
 if(kind==='welcome-hero')return <section className="space-y-5 text-center"><div aria-hidden="true" className="mx-auto grid h-28 w-28 rotate-[-7deg] place-items-center rounded-[32px] bg-rose-100 font-serif text-7xl text-[var(--w-accent)]">♡</div>{blocks.map(copy)}</section>;
 if(kind==='enter-action')return <div className="text-center">{blocks.map(block=>mark(block,<a href={editing?undefined:str(block,'href','/home')} className={primary+' inline-flex items-center gap-4'}>{str(block,'title')} <span aria-hidden="true">→</span></a>))}</div>;
 if(kind==='date-widget'){const date=state.settings.birthdate&&p.dateMode==='birthday'?new Date(state.settings.birthdate+'T12:00:00Z'):new Date();return <section className={card+' flex items-center gap-4'}><span aria-hidden="true" className="text-3xl">♡</span><div><time suppressHydrationWarning className="font-serif text-xl">{new Intl.DateTimeFormat('en',{month:'long',day:'numeric',timeZone:state.settings.timezone}).format(date)}</time>{blocks.map(copy)}</div></section>}
 if(kind==='app-launcher')return <>{blocks.map(block=>mark(block,navigation?<HomeNavigation items={navigation} editing={editing} style={{display:'grid',gridTemplateColumns:`repeat(${block.props.columns??2},minmax(0,1fr))`,gap:Number(block.props.gap??12)}}/>:<div className="grid grid-cols-2 gap-3" style={{gridTemplateColumns:`repeat(${block.props.columns??2},minmax(0,1fr))`,gap:Number(block.props.gap??12)}}>{[['💗','Adore','reasons'],['☎️','Birthday Hotline','hotline'],['🧭','Our Next Adventure','adventure'],['🎬','Our Birthday Movie','movie'],['💋','The Kiss Shop','kiss-shop'],['📻','Birthday Radio','radio']].map(([icon,title,slug])=><a key={slug} href={editing?undefined:'/app/'+slug} className={card+' min-w-0 p-4'}><span className="text-3xl">{icon}</span>{slug==='hotline'&&<span className="ml-2 rounded-full bg-rose-100 px-2 py-1 text-[9px]">Start here</span>}<h3 className="mt-3 text-sm font-semibold">{title}</h3><p className="mt-2 text-xs opacity-60">Open app →</p></a>)}</div>))}</>;
 if(kind==='recent-app'&&!editing&&!getPublicApp(state.recent))return null;
 if(kind==='recent-app')return <section className="rounded-2xl border-l-2 border-[var(--w-accent)] px-4 py-2">{blocks.map(copy)}{getPublicApp(state.recent)?<a className="inline-flex min-h-11 items-center text-sm" href={editing?undefined:'/app/'+state.recent}>{getPublicApp(state.recent)!.icon} {getPublicApp(state.recent)!.title} →</a>:<p className="text-xs opacity-60">A recently opened app will appear here.</p>}</section>;
 if(kind==='heartfelt-card')return <section className={card+' bg-gradient-to-br from-rose-100 to-orange-50 space-y-4'}><span aria-hidden="true" className="text-4xl">💗</span>{blocks.map(copy)}</section>;
 if(kind==='reason-deck'){
  const allReasons=blocks.filter(n=>n.component==='reason'),items=allReasons.filter(n=>!savedOnly||editing||state.favorites.includes(n.id)),selected=active(items,node.id),index=items.indexOf(selected!);
  const move=(offset:number)=>{if(items.length)state.choose(node.id,items[Math.max(0,Math.min(items.length-1,index+offset))].id)};
  return <section className="adore-deck space-y-4"><div className="adore-segments" aria-label="Reason collection"><button disabled={editing} aria-pressed={!savedOnly} onClick={()=>setSavedOnly(false)}>All reasons</button><button disabled={editing} aria-pressed={savedOnly} onClick={()=>setSavedOnly(true)}>Saved ({allReasons.filter(n=>state.favorites.includes(n.id)).length})</button></div><p className="adore-count" role="status">{items.length?index+1:0} / {items.length} reasons</p>{!items.length&&<p className="adore-empty">Save a reason with the heart to keep it here. ♡</p>}{selected&&mark(selected,<div className={card+" adore-reason"} tabIndex={0} onKeyDown={e=>{if(!editing&&["ArrowLeft","ArrowRight"].includes(e.key)){e.preventDefault();move(e.key==="ArrowRight"?1:-1)}}} onTouchStart={e=>{e.currentTarget.dataset.startX=String(e.touches[0].clientX)}} onTouchEnd={e=>{const delta=e.changedTouches[0].clientX-Number(e.currentTarget.dataset.startX);if(!editing&&Math.abs(delta)>50)move(delta<0?1:-1)}}><Photo node={selected}/><p className="text-xs uppercase tracking-widest">{str(selected,'category')}</p><h3 className="my-3 font-serif text-2xl">{str(selected,'title')}</h3><p className="leading-7">{str(selected,'body')}</p><button disabled={editing} aria-pressed={state.favorites.includes(selected.id)} className={button+' mt-4'} onClick={()=>state.favorite(selected.id)}>{state.favorites.includes(selected.id)?'♥ Saved':str(node,'favoriteLabel','Save favourite')}</button></div>)}<div className="flex justify-between gap-3"><button className={button} disabled={editing||index<=0} onClick={()=>move(-1)}>{str(node,'previousLabel','Previous')}</button><button className={button} disabled={editing||index>=items.length-1} onClick={()=>move(1)}>{str(node,'nextLabel','Next')}</button></div></section>;
 }
 if(kind==='incoming-call')return <LiveHotline preview={editing} title={str(node,'incomingTitle')==='Incoming birthday call'?undefined:str(node,'incomingTitle')||undefined} name={str(node,'callerName')==='A message from me'?undefined:str(node,'callerName')||undefined} recipientName={str(node,'recipientName','Wiffeyyyy')} photo={str(node,'callerPhoto')} callLabel={str(node,'answerLabel')==='Answer'?undefined:str(node,'answerLabel')||undefined}/>;
 if(kind==='birthday-message')return <details className={'hotline-recorded '+card} open={editing||undefined}><summary>Birthday voice message</summary>{playback(blocks[0],'audio',true)}</details>;
 if(kind==='affection-keypad'){const selected=active(blocks,node.id);return <details className="hotline-recorded space-y-4" open={editing||undefined}><summary>A little extra affection</summary><div className="grid grid-cols-3 gap-3">{blocks.map(block=>mark(block,<button className={button+' w-full'} disabled={editing} aria-pressed={selected?.id===block.id} onClick={()=>state.choose(node.id,block.id)}><span className="block text-2xl">{str(block,'digit')}</span><span className="text-xs">{str(block,'title')}</span></button>))}</div><div className={card}>{playback(selected,'audio',true)}</div></details>}
 if(kind==='choice-group')return <section className="space-y-3"><h2 className="font-serif text-xl">{node.label}</h2><div className="grid grid-cols-2 gap-3">{blocks.map(block=>mark(block,<button className={card+' w-full text-left '+(state.selections[node.id]===block.id?'ring-2 ring-[var(--w-accent)]':'')} disabled={editing} aria-pressed={state.selections[node.id]===block.id} onClick={()=>state.choose(node.id,block.id)}><h3 className="font-semibold">{str(block,'title')}</h3><p className={muted+' mt-2'}>{str(block,'body')}</p></button>))}</div></section>;
 if(kind==='invitation-reveal')return <section className="space-y-4"><button className={primary} disabled={editing} onClick={()=>state.show(!state.reveal)}>{state.reveal?str(node,'backLabel','Change my choices'):str(node,'directLabel','See your invitation')}</button>{(editing||state.reveal)&&blocks.map(block=>mark(block,<div className={card+' space-y-3'}><p className="text-xs uppercase tracking-widest">Your invitation</p><h3 className="font-serif text-2xl">{str(block,'title')}</h3><p className={muted}>{str(block,'body')}</p><p className="text-sm">{state.document.nodes.filter(n=>Object.values(state.selections).includes(n.id)&&n.component==='adventure-choice').map(n=>str(n,'title')).join(' · ')}</p><dl className="text-sm">{['date','time','place'].map(key=><div className="mt-2" key={key}><dt className="inline font-semibold capitalize">{key}: </dt><dd className="inline">{str(block,key)}</dd></div>)}</dl></div>))}</section>;
 if(kind==='movie-player'){const selected=active(blocks,'movie');return <section className={card}>{playback(selected,'video')}</section>}
 if(kind==='movie-chapters')return <nav aria-label="Movie chapters" className="space-y-2">{blocks.map((block,i)=>mark(block,<button className={button+' w-full text-left'} disabled={editing} onClick={()=>state.choose('movie',str(block,'sceneId'))}>{i+1}. {str(block,'title')}</button>))}</nav>;
 if(kind==='product-collection')return <section className="grid gap-4">{blocks.map(block=>mark(block,<article className={card}><Photo node={block} icon="💋"/><p className="text-xs font-semibold text-[var(--w-accent)]">{str(block,'price')}</p><h3 className="mt-2 font-serif text-2xl">{str(block,'title')}</h3><details className="my-3"><summary className="cursor-pointer py-2 text-sm">{str(node,'detailsLabel','Gift details')}</summary><p className={muted}>{str(block,'body')}</p></details><button className={primary} disabled={editing||block.props.available===false||block.props.available==='false'||state.bag.includes(block.id)} onClick={()=>state.setBag([...state.bag,block.id])}>{state.bag.includes(block.id)?'In your bag':str(node,'addLabel','Add to bag')}</button></article>))}</section>;
 if(kind==='gift-bag'){const items=all('kiss-gift').filter(n=>state.bag.includes(n.id));return <section className={card}><h2 className="font-serif text-2xl">{str(node,'title','Your bag')} ({items.length})</h2>{items.length?<ul>{items.map(item=><li key={item.id} className="mt-3 flex items-center justify-between gap-2"><span>{str(item,'title')}</span><button className={button} disabled={editing} onClick={()=>state.setBag(state.bag.filter(id=>id!==item.id))}>{str(node,'removeLabel','Remove')}</button></li>)}</ul>:<p className={muted+' mt-3'}>{str(node,'emptyMessage','Your bag is waiting.')}</p>}</section>}
 if(kind==='gift-checkout')return <section className="space-y-3"><h2 className="font-serif text-xl">{str(node,'title')}</h2><button className={primary} disabled={editing||!state.bag.length} onClick={state.checkout}>{str(node,'checkoutLabel','Create my gift receipt')}</button></section>;
 if(kind==='gift-receipt'){const gifts=state.receipt.length?state.receipt:editing?all('kiss-gift').slice(0,1):[];const save=()=>{const url=URL.createObjectURL(new Blob([giftReceiptSvg(gifts,str(node,'title'),str(node,'note'))],{type:'image/svg+xml'}));const a=document.createElement('a');a.href=url;a.download='wiffeyyyy-gift-receipt.svg';a.click();URL.revokeObjectURL(url)};return <section className={card+' border-dashed'}><p className="text-xs uppercase tracking-widest">Gift receipt</p><h2 className="mt-3 font-serif text-2xl">{str(node,'title')}</h2>{gifts.length?<ul className="my-4 space-y-2">{gifts.map(gift=><li key={gift.id}>♡ {str(gift,'title')}</li>)}</ul>:<p className={muted+' my-4'}>Your gift receipt appears here after checkout.</p>}<p className={muted}>{str(node,'note')}</p><button className={button+' mt-4'} disabled={editing||!gifts.length} onClick={save}>{str(node,'downloadLabel','Save receipt')}</button></section>}
 if(kind==='station-selector'){const selected=active(blocks,'station');return <section className="space-y-3"><p className="text-xs uppercase tracking-widest">Choose a station</p>{blocks.map(block=>mark(block,<button className={card+' w-full text-left '+(selected?.id===block.id?'ring-2 ring-[var(--w-accent)]':'')} disabled={editing} aria-pressed={selected?.id===block.id} onClick={()=>{state.choose('station',block.id);state.choose('track','')}}>{block.props.src&&<Photo node={block} icon="📻"/>}<h2 className="font-serif text-xl">📻 {str(block,'title')}</h2><p className={muted}>{str(block,'body')}</p></button>))}</section>}
 const stations=all('station'),selectedNode=state.document.nodes.find(n=>n.id===state.selectedId),station=stations.find(n=>editing&&n.id===selectedNode?.props.stationId)??active(stations,'station');const tracks=all('radio-track').filter(n=>!n.props.stationId||n.props.stationId===station?.id),track=active(tracks,'track');
 if(kind==='track-list')return <nav aria-label="Station tracks" className="space-y-2">{blocks.filter(n=>tracks.some(t=>t.id===n.id)).map((block,i)=>mark(block,<button className={button+' w-full text-left'} disabled={editing} aria-pressed={track?.id===block.id} onClick={()=>state.choose('track',block.id)}>{i+1}. {str(block,'title')}</button>))}</nav>;
 if(kind==='dedication')return <section className={card}>{blocks.map(copy)}<p className={muted+' mt-3'}>{str(track,'body','Choose a track to read its dedication.')}</p></section>;
 if(kind==='radio-player'){const index=tracks.indexOf(track!);return <section className={card+' space-y-4'}><p className="text-xs uppercase tracking-widest">{str(node,'title','Now playing')}</p>{track&&str(track,'introSrc')&&<MediaPlayer identity={'intro:'+track.id} src={str(track,'introSrc')} kind="audio" title="Recorded introduction" disabled={editing}/>} {playback(track,'audio')}<div className="flex gap-3"><button className={button} disabled={editing||index<=0} onClick={()=>state.choose('track',tracks[index-1].id)}>{str(node,'previousLabel','Previous track')}</button><button className={button} disabled={editing||index<0||index>=tracks.length-1} onClick={()=>state.choose('track',tracks[index+1].id)}>{str(node,'nextLabel','Next track')}</button></div></section>}
 return <section className="space-y-4">{blocks.map(copy)}</section>;
}
