'use client';
import {useContext,useEffect,useRef,useState} from 'react';
import type {PageDocument,CMSNode} from '@wiffeyyyy/content';
import {useCameraRoll} from './use-camera-roll';
import {captureFilename,deleteCameraCapture,saveCameraCapture,type CameraCapture} from './camera-roll-store';
import {DocumentSettingsContext} from './page-layout';
const value=(n:CMSNode,key:string)=>String(n.props[key]??'');
function Icon({kind}:{kind:string}){return <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{kind==='search'?<><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></>:kind==='heart'?<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>:kind==='video'?<><rect x="3" y="5" width="13" height="14" rx="3"/><path d="m16 10 5-3v10l-5-3"/></>:kind==='collections'?<><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></>:<><rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1.5"/><path d="m3 17 5-5 4 4 4-6 5 7"/></>}</svg>}
export function PhotoLibrary({document,onSelect,selectedId,persist=false}:{document:PageDocument;onSelect?:(id:string)=>void;selectedId?:string;persist?:boolean}){
 const settings=useContext(DocumentSettingsContext);
 const [tab,setTab]=useState('Library'),[filter,setFilter]=useState('All'),[album,setAlbum]=useState(''),[period,setPeriod]=useState('All'),[dateGroup,setDateGroup]=useState(''),[query,setQuery]=useState(''),[columns,setColumns]=useState(3),[newest,setNewest]=useState(true),[opened,setOpened]=useState<string|null>(null),[favorites,setFavorites]=useState<string[]>([]),[ready,setReady]=useState(!persist),[clock,setClock]=useState('9:41');
 const [deleting,setDeleting]=useState(false),[deleteError,setDeleteError]=useState(''),[deleted,setDeleted]=useState<{capture:CameraCapture;favorite:boolean}|null>(null);
 const deletePending=useRef(false);
 const dialog=useRef<HTMLDialogElement>(null),gesture=useRef<number|null>(null),byId=new Map(document.nodes.map(n=>[n.id,n]));
 const visible=(n:CMSNode):boolean=>n.visible&&(!n.parentId||!!byId.get(n.parentId)&&visible(byId.get(n.parentId)!));
 const library=document.nodes.find(n=>n.props.sectionKind==='photo-library');
 const cameraRoll=useCameraRoll(persist&&!onSelect);
 const cameraItems:CMSNode[]=cameraRoll.items.map(c=>({id:c.id,type:'block',component:c.kind,label:'Camera '+(c.kind==='image'?'photo':'video'),parentId:null,children:[],visible:true,props:{src:c.url,title:c.kind==='image'?'Camera photo':'Camera video',alt:'Captured with Clicksara',date:c.createdAt,album:'Camera',body:'Captured with Clicksara · saved on this device'}}));
 const items=[...document.nodes.filter(n=>['image','video'].includes(n.component)&&visible(n)),...cameraItems];
 const populated=items.filter(n=>value(n,'src'));
 const source=onSelect?items:populated;
 const shown=source.filter(n=>(filter!=='Favourites'||favorites.includes(n.id))&&(!album||(value(n,'album')||'Fit checks')===album)&&(filter!=='Photos'||n.component==='image')&&(filter!=='Videos'||n.component==='video')&&(!dateGroup||(dateGroup==='Undated'?!value(n,'date'):value(n,'date').startsWith(dateGroup)))&&(!query||[value(n,'title'),value(n,'alt'),value(n,'body'),value(n,'album'),value(n,'date')].join(' ').toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>newest?value(b,'date').localeCompare(value(a,'date')):value(a,'date').localeCompare(value(b,'date')));
 const albums=[...new Set(items.map(n=>value(n,'album')||'Fit checks'))];
 const groups=[...new Set(shown.map(n=>value(n,'date').slice(0,period==='Years'?4:7)||'Undated'))];
 const current=items.find(n=>n.id===opened),index=shown.findIndex(n=>n.id===opened);
 useEffect(()=>{if(persist&&!onSelect&&new URLSearchParams(window.location.search).get('album')==='Camera')setAlbum('Camera')},[persist,onSelect]);
 useEffect(()=>{const tick=()=>setClock(new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit'}).format(new Date()));tick();const timer=setInterval(tick,30000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(!persist)return;try{const saved=JSON.parse(localStorage.getItem('wiffeyyyy:pardanasheen:favourites:v1')??'[]');if(Array.isArray(saved))setFavorites(saved.filter(x=>typeof x==='string'))}catch{}setReady(true)},[persist]);
 useEffect(()=>{if(persist&&ready)try{localStorage.setItem('wiffeyyyy:pardanasheen:favourites:v1',JSON.stringify(favorites))}catch{}},[favorites,ready,persist]);
 useEffect(()=>{if(opened&&!dialog.current?.open)dialog.current?.showModal();else if(!opened)dialog.current?.close()},[opened]);
 useEffect(()=>{if(opened&&!current&&!cameraRoll.loading)setOpened(null)},[opened,current,cameraRoll.loading]);
 const capture=cameraRoll.items.find(c=>c.id===opened);
 async function removeCapture(){
  if(!capture||deletePending.current)return;deletePending.current=true;setDeleting(true);setDeleteError('');
  try{await deleteCameraCapture(capture.id);setDeleted({capture,favorite:favorites.includes(capture.id)});setFavorites(old=>old.filter(id=>id!==capture.id));setOpened(null)}
  catch{setDeleteError('Could not delete this capture. Please try again.')}finally{deletePending.current=false;setDeleting(false)}
 }
 async function undoDelete(){
  if(!deleted||deletePending.current)return;deletePending.current=true;setDeleting(true);setDeleteError('');
  try{await saveCameraCapture(deleted.capture.blob,deleted.capture.kind,deleted.capture);if(deleted.favorite)setFavorites(old=>old.includes(deleted.capture.id)?old:[...old,deleted.capture.id]);setDeleted(null)}
  catch{setDeleteError('Could not restore this capture. Please try again.')}finally{deletePending.current=false;setDeleting(false)}
 }
 const navigate=(next:string)=>{setTab(next);setAlbum('');setFilter('All');setDateGroup('');setPeriod('All');setQuery('')};
 const collection=(name:string,type:string)=>{navigate('Library');if(type==='album')setAlbum(name);else setFilter(name)};
 const move=(offset:number)=>{if(deletePending.current)return;const next=shown[index+offset];if(next)setOpened(next.id)};
 const thumbnail=(n:CMSNode)=>value(n,'src')?(n.component==='image'?<img src={value(n,'src')} alt={value(n,'alt')} loading="lazy" decoding="async"/>:<video src={value(n,'src')} muted playsInline preload="metadata"/>):<span className="pard-slot"><Icon kind={n.component==='video'?'video':'photo'}/><small>{n.label}</small></span>;
 const grid=<div className="pard-grid" style={{gridTemplateColumns:`repeat(${columns},minmax(0,1fr))`}}>{shown.map(n=><button key={n.id} data-layout-node-id={n.id} aria-label={onSelect?'Select '+(n.label??n.component):'Open '+(value(n,'title')||value(n,'alt')||n.component)} style={{outline:selectedId===n.id?'3px solid #0a84ff':undefined}} onClick={()=>onSelect?onSelect(n.id):setOpened(n.id)}>{thumbnail(n)}{n.component==='video'&&<span className="pard-video-badge"><Icon kind="video"/></span>}{favorites.includes(n.id)&&<span className="pard-favorite-badge">♥</span>}</button>)}</div>;
 return <div className="pard-app"><div className="pard-status"><span>{clock}</span><span className="pard-island" aria-hidden="true"/><span aria-label="Connected to network">▥ ◔ ▰</span></div><header className="pard-header"><a href="/home" aria-label="Return to home screen">‹ Home</a><span>{library&&value(library,'title')||'Pardanasheen'}</span><span className="pard-avatar" aria-label={'Made for '+settings.nickname}>{(settings.nickname==='favourite person'?'W':settings.nickname.charAt(0)).toUpperCase()}</span></header><div className="pard-content">{deleted&&<div className="pard-delete-notice" role="status"><span>{deleted.capture.kind==='image'?'Photo':'Video'} deleted</span><button disabled={deleting} onClick={()=>void undoDelete()}>{deleting?'Restoring…':'Undo'}</button></div>}{deleteError&&!opened&&<p className="pard-storage-error" role="alert">{deleteError}</p>}{cameraRoll.error&&<p className="pard-storage-error" role="alert">{cameraRoll.error}</p>}<div className="pard-heading"><div><h1 role={onSelect?'button':undefined} tabIndex={onSelect?0:undefined} aria-label={onSelect?'Select Fit-check library':undefined} onClick={()=>onSelect&&library&&onSelect(library.id)} onKeyDown={e=>{if(onSelect&&library&&['Enter',' '].includes(e.key)){e.preventDefault();onSelect(library.id)}}}>{album||dateGroup|| (filter!=='All'?filter:tab)}</h1><p className="pard-subtitle">{tab==='Collections'?'Albums and media types':`${populated.length} items`}</p></div>{tab!=='Collections'&&<div className="pard-tools"><button aria-label="Change thumbnail size" onClick={()=>setColumns(old=>old===3?2:old===2?5:3)}><Icon kind="collections"/></button><button aria-label={newest?'Sort oldest first':'Sort newest first'} onClick={()=>setNewest(old=>!old)}>{newest?'↓':'↑'}</button></div>}</div>
 {tab==='Search'&&<label className="pard-search"><Icon kind="search"/><input aria-label="Search photos and videos" placeholder="Photos, captions, albums, dates" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}>×</button>}</label>}
 {tab==='Collections'?<><h2 className="pard-section-title">Pinned Collections</h2><div className="pard-pinned">{[['Favourites','heart',favorites.filter(id=>populated.some(n=>n.id===id)).length],['Videos','video',populated.filter(n=>n.component==='video').length],['Photos','photo',populated.filter(n=>n.component==='image').length]].map(([name,icon,count])=><button key={name} onClick={()=>collection(String(name),'filter')}><Icon kind={String(icon)}/><strong>{name}</strong><span>{count}</span></button>)}</div><h2 className="pard-section-title">Albums <span>{albums.length}</span></h2><div className="pard-albums">{albums.map(name=>{const media=populated.filter(n=>(value(n,'album')||'Fit checks')===name);return <button key={name} onClick={()=>collection(name,'album')}><div>{media[0]?thumbnail(media[0]):<Icon kind="collections"/>}</div><strong>{name}</strong><span>{media.length} items</span></button>})}</div></>:<>{(album||dateGroup||filter==='Favourites')&&<button className="pard-back" onClick={()=>navigate('Collections')}>‹ Collections</button>}<div className="pard-filters" aria-label="Media filter">{['All','Photos','Videos'].map(name=><button key={name} aria-pressed={filter===name} onClick={()=>setFilter(name)}>{name}</button>)}</div>{shown.length?(period==='All'||tab==='Search'?grid:<div className="pard-date-groups">{groups.map(group=>{const cover=shown.find(n=>(value(n,'date').slice(0,period==='Years'?4:7)||'Undated')===group)!;return <button key={group} onClick={()=>{setDateGroup(group);setPeriod('All')}}>{thumbnail(cover)}<strong>{group}</strong></button>})}</div>):<div className="pard-empty"><Icon kind={tab==='Search'?'search':filter==='Favourites'?'heart':'photo'}/><h2>{query?'No results':filter==='Favourites'?'No Favourites Yet':'No Photos or Videos'}</h2><p>{query?'Try another title, caption, album or date.':filter==='Favourites'?'Tap the heart on a photo or video to save it here.':'Your fit checks will appear in your library once added.'}</p></div>}<p className="pard-count">{shown.filter(n=>n.component==='image').length} Photos, {shown.filter(n=>n.component==='video').length} Videos</p></>}
 </div>{tab==='Library'&&<div className="pard-periods" aria-label="Library display">{['Years','Months','All'].map(name=><button key={name} aria-pressed={period===name} onClick={()=>{setPeriod(name);setDateGroup('')}}>{name}</button>)}</div>}<nav className="pard-tabs" aria-label="Photos app">{[['Library','photo'],['Collections','collections'],['Search','search']].map(([name,icon])=><button key={name} aria-current={tab===name?'page':undefined} onClick={()=>navigate(name)}><Icon kind={icon}/>{name}</button>)}</nav><a className="pard-home" href="/home" aria-label="Return to home screen"/>
 <dialog ref={dialog} className="pard-viewer" aria-label="Media viewer" onCancel={()=>setOpened(null)} onClose={()=>setOpened(null)} onKeyDown={e=>{if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1)}}>{current&&<><header><button onClick={()=>setOpened(null)} aria-label="Close media viewer">×</button><div><strong>{value(current,'title')||value(current,'alt')}</strong><small>{value(current,'date')}</small></div><button disabled={!ready} aria-label="Save favourite" aria-pressed={favorites.includes(current.id)} onClick={()=>setFavorites(old=>old.includes(current.id)?old.filter(id=>id!==current.id):[...old,current.id])}>{favorites.includes(current.id)?'♥':<Icon kind="heart"/>}</button></header><div className="pard-viewer-media" onTouchStart={e=>{gesture.current=e.touches[0].clientX}} onTouchEnd={e=>{if(gesture.current!==null){const delta=e.changedTouches[0].clientX-gesture.current;if(Math.abs(delta)>60)move(delta<0?1:-1)}gesture.current=null}}>{current.component==='video'?<video key={current.id} src={value(current,'src')} controls playsInline preload="metadata"/>:<img src={value(current,'src')} alt={value(current,'alt')}/>}</div><p>{value(current,'body')}</p>{capture&&<div className="pard-capture-actions"><a className="pard-capture-download" href={value(current,'src')} download={captureFilename(capture)}>Save to device</a><button className="pard-capture-delete" disabled={deleting} onClick={()=>void removeCapture()} aria-label={capture.kind==='image'?'Delete captured photo':'Delete captured video'}><svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3M6 7l1 14h10l1-14M10 11v6M14 11v6"/></svg>{deleting?'Deleting…':capture.kind==='image'?'Delete photo':'Delete video'}</button></div>}{deleteError&&<p className="pard-storage-error" role="alert">{deleteError}</p>}<footer><button disabled={index<=0} onClick={()=>move(-1)}>Previous</button><button disabled={index<0||index>=shown.length-1} onClick={()=>move(1)}>Next</button></footer></>}</dialog></div>;
}
