import {defaultPuzzleLevels,type PuzzleLevel} from '../../content/src/app-settings';
export const LEVELS=defaultPuzzleLevels;
export type LevelProgress={placed:number[];order:number[]};
export type PuzzleJourney={version:2;levels:LevelProgress[]};
export function shuffledPieces(count:number,random=Math.random){const a=Array.from({length:count},(_,i)=>i);for(let i=a.length-1;i>0;i--){const j=Math.min(i,Math.max(0,Math.floor(random()*(i+1))));[a[i],a[j]]=[a[j],a[i]]}return a}
export const pieceCount=(level:number,levels:readonly PuzzleLevel[]=LEVELS)=>levels[level].cols*levels[level].rows;
export const freshLevel=(level:number,levels:readonly PuzzleLevel[]=LEVELS):LevelProgress=>({placed:[],order:shuffledPieces(pieceCount(level,levels))});
export const freshJourney=(levels:readonly PuzzleLevel[]=LEVELS):PuzzleJourney=>({version:2,levels:levels.map((_,i)=>freshLevel(i,levels))});
export const levelSolved=(state:PuzzleJourney,level:number,levels:readonly PuzzleLevel[]=LEVELS)=>!!state.levels[level]&&state.levels[level].placed.length===pieceCount(level,levels);
export const levelUnlocked=(state:PuzzleJourney,level:number,levels:readonly PuzzleLevel[]=LEVELS)=>Number.isInteger(level)&&level>=0&&level<levels.length&&!!state.levels[level]&&state.levels.slice(0,level).every((_,i)=>levelSolved(state,i,levels));
export const journeySolved=(state:PuzzleJourney,levels:readonly PuzzleLevel[]=LEVELS)=>levels.every((_,i)=>levelSolved(state,i,levels));
export function placePiece(state:PuzzleJourney,level:number,piece:number,slot:number,levels:readonly PuzzleLevel[]=LEVELS):PuzzleJourney{if(!levelUnlocked(state,level,levels)||piece!==slot||!Number.isInteger(piece)||piece<0||piece>=pieceCount(level,levels)||state.levels[level].placed.includes(piece))return state;return {...state,levels:state.levels.map((p,i)=>i===level?{...p,placed:[...p.placed,piece]}:p)}}
export function restartFrom(state:PuzzleJourney,level:number,levels:readonly PuzzleLevel[]=LEVELS):PuzzleJourney{return levelUnlocked(state,level,levels)?{...state,levels:state.levels.map((p,i)=>i>=level?freshLevel(i,levels):p)}:state}
export function readJourney(raw:string|null,levels:readonly PuzzleLevel[]=LEVELS):PuzzleJourney|null{try{const d=JSON.parse(raw??'null');if(d?.version!==2||!Array.isArray(d.levels)||d.levels.length!==levels.length)return null;const progress:LevelProgress[]=[];for(let i=0;i<levels.length;i++){const p=d.levels[i],count=pieceCount(i,levels),valid=(x:unknown)=>Number.isInteger(x)&&Number(x)>=0&&Number(x)<count;if(!Array.isArray(p?.placed)||!Array.isArray(p?.order)||p.order.length!==count||new Set(p.order).size!==count||!p.order.every(valid))return null;const unlocked=progress.every((l,j)=>l.placed.length===pieceCount(j,levels));progress.push({order:p.order,placed:unlocked?[...new Set<number>(p.placed.filter(valid))]:[]})}return {version:2,levels:progress}}catch{return null}}
// Adjacent pieces share tab geometry; outer edges stay straight.
export function piecePath(id:number,cols:number,rows:number){const c=id%cols,r=Math.floor(id/cols);const top=r?'L35 0 C35 0 35 -17 50 -17 C65 -17 65 0 65 0 L100 0':'L100 0';const right=c<cols-1?'L100 35 C100 35 117 35 117 50 C117 65 100 65 100 65 L100 100':'L100 100';const bottom=r<rows-1?'L65 100 C65 100 65 83 50 83 C35 83 35 100 35 100 L0 100':'L0 100';const left=c?'L0 65 C0 65 17 65 17 50 C17 35 0 35 0 35 L0 0':'L0 0';return `M0 0 ${top} ${right} ${bottom} ${left} Z`}
