'use client';
import {useEffect,useRef,useState} from 'react';
import type {VaultStory} from '../../../lib/vault-story';
function Lock({open=false}:{open?:boolean}){return <svg viewBox="0 0 24 24" width="19" height="19" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><rect x="5" y="10" width="14" height="11" rx="3"/>{open?<path d="M8 10V6a4 4 0 0 1 8 0"/>:<path d="M8 10V6a4 4 0 0 1 8 0v4"/>}<path d="M12 14v3"/></svg>}
export default function VaultClient(){
 const [answer,setAnswer]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[story,setStory]=useState<VaultStory|null>(null);
 const [phase,setPhase]=useState<'locked'|'opening'|'open'|'closing'>('locked');
 useEffect(()=>{if(phase==='open')heading.current?.focus();if(phase==='locked')input.current?.focus()},[phase]);
 const input=useRef<HTMLInputElement>(null),heading=useRef<HTMLHeadingElement>(null),pending=useRef(false);
 const unlock=async(event:React.FormEvent)=>{
  event.preventDefault();if(pending.current||!answer.trim())return;pending.current=true;setBusy(true);setError('');
  try{const response=await fetch('/api/vault',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answer}),cache:'no-store'});const data=await response.json();
   if(!response.ok)throw new Error(data.error||'Vault couldn’t open. Please try again.');
   if(!data.story||!Array.isArray(data.story.chapters))throw new Error('Vault couldn’t open. Please try again.');
   setStory(data.story);setAnswer('');setPhase('opening');
  }catch(e){setError(e instanceof Error?e.message:'Connection lost. Please try again.');input.current?.focus()}finally{pending.current=false;setBusy(false)}
 };
 const lock=()=>{if(phase!=='open')return;setPhase('closing');setAnswer('');setError('')};
 const completeTransition=()=>{if(phase==='opening')setPhase('open');else if(phase==='closing'){setStory(null);setPhase('locked')}};
 return <main data-phase={phase} className={'vault-app'+(story?' is-unlocked':'')}><div className="vault-grain" aria-hidden="true"/><header className="vault-header"><a href="/home" aria-label="Return to home screen">‹ Home</a><span>VAULT</span>{story?<button onClick={lock} disabled={phase!=='open'} aria-label="Lock Vault"><Lock/></button>:<span className="vault-secure" aria-label="Vault is locked"><Lock/></span>}</header>
 {story?<section className="vault-story"><div className="vault-eyebrow"><span/> JUST BETWEEN US</div><h1 ref={heading} tabIndex={-1}>{story.title}</h1><p className="vault-story-subtitle">{story.subtitle}</p><div className="vault-story-rule"><span/>♡<span/></div>{story.chapters.length?<div className="vault-chapters">{story.chapters.map((chapter,index)=><article key={chapter.id}><span className="vault-chapter-number">CHAPTER {String(index+1).padStart(2,'0')}</span><h2>{chapter.title}</h2><p>{chapter.body}</p></article>)}</div>:<div className="vault-unwritten"><span className="vault-page-mark" aria-hidden="true">✧</span><h2>Some stories are worth<br/>keeping close.</h2><p>Ours will unfold here.<br/>One memory. One moment. One chapter at a time.</p><div className="vault-chapter-preview"><span>01</span><div><strong>The beginning</strong><small>A story waiting to be told</small></div><span aria-hidden="true">♡</span></div></div>}<button className="vault-lock-again" disabled={phase!=='open'} onClick={lock}><Lock/> Close our story</button></section>:<section className="vault-entrance"><div className="vault-eyebrow"><span/> A LOVE STORY, KEPT SAFE</div><div className="vault-door" aria-hidden="true"><div className="vault-dial"><span className="vault-dial-center">♡</span><i/><i/><i/></div><span className="vault-door-hinge"/><span className="vault-door-label">OUR PRECIOUS STORY</span></div><h1>The most precious<br/>things stay close.</h1><p className="vault-intro">Our story. Protected by a memory only we share.</p><form onSubmit={unlock} className="vault-form"><label htmlFor="vault-answer">What’s my favourite memory about us?</label><div className={'vault-input-wrap'+(error?' has-error':'')}><input ref={input} id="vault-answer" value={answer} onChange={event=>{setAnswer(event.target.value);if(error)setError('')}} maxLength={160} autoComplete="off" autoCapitalize="sentences" placeholder="Write your memory…" disabled={busy} aria-invalid={!!error} aria-describedby={error?'vault-error':'vault-answer-note'}/><span aria-hidden="true">♡</span></div><p id="vault-answer-note" className="vault-answer-note">Say it in your own words.</p>{error&&<p id="vault-error" className="vault-error" role="alert">{error}</p>}<button className="vault-unlock" type="submit" disabled={busy||!answer.trim()}>{busy?<span className="vault-spinner" aria-hidden="true"/>:<Lock open/>}{busy?'Opening our story…':'Unlock our story'}<span aria-hidden="true">→</span></button></form><p className="vault-footnote">One memory. A key only we share.</p></section>}
 {(phase==='opening'||phase==='closing')&&<div className="vault-cinematic" aria-hidden="true" onAnimationEnd={event=>{if(event.target===event.currentTarget)completeTransition()}}><div className="vault-inner-light"/><div className="vault-door-leaf vault-door-left"><div className="vault-door-inlay"/><span className="vault-cinematic-monogram">♡</span><span className="vault-cinematic-label">OUR STORY</span></div><div className="vault-door-leaf vault-door-right"><div className="vault-door-inlay"/><div className="vault-cinematic-lock"><Lock open={phase==='opening'}/></div><span className="vault-cinematic-label">KEPT CLOSE</span></div><div className="vault-light-dust"><i/><i/><i/><i/><i/></div></div>}
 <span className="vault-transition-status" role="status">{phase==='opening'?'Unlocking your precious story…':phase==='closing'?'Keeping our story safe.':''}</span>
 <a className="vault-home" href="/home" aria-label="Return to home screen"><span/></a></main>;
}
