'use client';
import {useEffect,useRef,useState} from 'react';
import {usePathname} from 'next/navigation';
import {defaultAudioSettings,type SiteDocument} from '@wiffeyyyy/content';
import {playbackCoordinator} from '../../../packages/audio/src/controller';
export function BirthdaySoundtrack({settings}:{settings:SiteDocument}){
 const playlist=settings.audio??defaultAudioSettings;const [id,setId]=useState(playlist.defaultTrack),[failed,setFailed]=useState(false);const advance=useRef(false);const ref=useRef<HTMLAudioElement>(null),pathname=usePathname();const track=playlist.tracks.find(t=>t.assetId===id)??playlist.tracks[0];
 useEffect(()=>{const player=ref.current;if(player&&advance.current){advance.current=false;player.play().catch(()=>setFailed(true))}return()=>{if(player){player.pause();playbackCoordinator.release(player)}}},[track?.assetId]);
 useEffect(()=>{setId(playlist.defaultTrack);setFailed(false)},[playlist.defaultTrack]);
 useEffect(()=>{const player=ref.current;if(!player)return;player.volume=settings.defaultVolume;player.muted=settings.defaultMuted;return()=>{player.pause();playbackCoordinator.release(player)}},[settings.defaultVolume,settings.defaultMuted]);
 useEffect(()=>{const player=ref.current;const hide=()=>{if(document.hidden)player?.pause()};document.addEventListener('visibilitychange',hide);if(playlist.background==='home-only'&&pathname!=='/home')player?.pause();return()=>document.removeEventListener('visibilitychange',hide)},[pathname,playlist.background]);
 if(!track)return null;return <aside aria-label="Birthday soundtrack" style={{position:'fixed',bottom:12,left:12,zIndex:40,maxWidth:'min(320px,calc(100vw - 24px))',padding:12,borderRadius:16,background:settings.surface,color:settings.text,boxShadow:'0 2px 16px #0002'}}><details><summary style={{cursor:'pointer',fontSize:12}}>♫ {track.title}</summary><select aria-label="Soundtrack track" value={track.assetId} onChange={e=>{ref.current?.pause();setId(e.target.value);setFailed(false)}}>{playlist.tracks.map(t=><option key={t.assetId} value={t.assetId}>{t.title}</option>)}</select><audio key={track.assetId} ref={ref} controls preload="none" src={'/media/'+track.assetId} style={{width:'100%',marginTop:8}} onLoadedMetadata={e=>{e.currentTarget.volume=settings.defaultVolume;e.currentTarget.muted=settings.defaultMuted}} onPlay={e=>{if(document.hidden||playlist.background==='home-only'&&pathname!=='/home'){e.currentTarget.pause();return}playbackCoordinator.claim(e.currentTarget)}} onPause={e=>playbackCoordinator.release(e.currentTarget)} onError={()=>setFailed(true)} onEnded={e=>{playbackCoordinator.release(e.currentTarget);const index=playlist.tracks.findIndex(t=>t.assetId===track.assetId);if(index+1<playlist.tracks.length||playlist.loop){if(playlist.tracks.length===1){e.currentTarget.currentTime=0;e.currentTarget.play().catch(()=>setFailed(true))}else{advance.current=true;setId(playlist.tracks[(index+1)%playlist.tracks.length].assetId)}}}}/>{failed&&<p role="status">Audio could not play. The transcript is available below.</p>}{track.transcript&&<p style={{whiteSpace:'pre-wrap',fontSize:12,maxHeight:160,overflow:'auto'}}>{track.transcript}</p>}<p style={{fontSize:11}}>Press Play to listen. App audio pauses the soundtrack.</p></details></aside>;
}
