'use client';
import { createContext, useCallback, useContext, useEffect, useRef, useState, type ReactNode } from 'react';
import { usePathname } from 'next/navigation';
import Link from 'next/link';
import {NotificationShade,useNotificationShade} from '@wiffeyyyy/ui/notification-shade';
import {defaultSiteDocument,installPhoneHome,createDefaultPage,type PageDocument, type SiteDocument} from '@wiffeyyyy/content';
import {DocumentSettingsProvider} from '@wiffeyyyy/ui/page-layout';
import {AudioDefaultsProvider} from '@wiffeyyyy/ui/media-player';
import { getPublicApp } from '@wiffeyyyy/content';
import { VISITOR_KEY, initialVisitorState, parseVisitorState, reduceVisitorState, type VisitorState, type VisitorAction } from '../lib/visitor-state';
const notifications=[{id:'welcome',title:'Your birthday home is ready',body:'Six little places to explore, all in one birthday world.',href:'/home'},{id:'hotline',title:'Start with the Birthday Hotline',body:'A little birthday message is waiting for you.',href:'/app/hotline'},{id:'explore',title:'Take your time',body:'You can come back to your favourite apps whenever you like.',href:'/home'}];
const SettingsContext=createContext(defaultSiteDocument);
export const useSiteSettings=()=>useContext(SettingsContext);
const Context=createContext<{state:VisitorState;ready:boolean;dispatch:(action:VisitorAction)=>void}>({state:initialVisitorState(),ready:false,dispatch:()=>{}});
export const useBirthdayOS=()=>useContext(Context);
function NotificationBridge({open}:{open:boolean}){const show=useNotificationShade();const first=useRef(true);useEffect(()=>{if(first.current){first.current=false;return;}show?.()},[open]);return null;}
export function OSProvider({children,settings=defaultSiteDocument,homeDocument}:{children:ReactNode;settings?:SiteDocument;homeDocument?:PageDocument|null}){
 const [state,setState]=useState(initialVisitorState),[ready,setReady]=useState(false),[storageAvailable,setStorageAvailable]=useState(true),[open,setOpen]=useState(false),[date,setDate]=useState('Birthday edition');
 const [phoneFit,setPhoneFit]=useState({scale:1,top:23});
 const pathname=usePathname(),dialog=useRef<HTMLDialogElement>(null),stateRef=useRef(state),readyRef=useRef(false);
 useEffect(()=>{if(pathname!=='/home'&&pathname!=='/app/hotline'&&pathname!=='/app/reasons'&&pathname!=='/app/adventure'&&pathname!=='/app/movie')return;const fit=()=>{const scale=Math.min(1,Math.max(1,window.innerWidth-32)/390,Math.max(1,window.innerHeight-32)/844);setPhoneFit({scale,top:(window.innerHeight-844*scale)/2/scale+7})};fit();window.addEventListener('resize',fit);return()=>window.removeEventListener('resize',fit)},[pathname]);
 const dispatch=useCallback((action:VisitorAction)=>{if(!readyRef.current)return;const next=reduceVisitorState(stateRef.current,action);stateRef.current=next;setState(next);try{localStorage.setItem(VISITOR_KEY,JSON.stringify(next))}catch{setStorageAvailable(false)}},[]);
 useEffect(()=>{let restored=initialVisitorState();try{restored=parseVisitorState(localStorage.getItem(VISITOR_KEY))}catch{setStorageAvailable(false)}stateRef.current=restored;readyRef.current=true;setState(restored);setReady(true);const sync=(e:StorageEvent)=>{if(e.key===VISITOR_KEY){const next=parseVisitorState(e.newValue);stateRef.current=next;setState(next)}};window.addEventListener('storage',sync);setDate(new Intl.DateTimeFormat('en',{month:'short',day:'numeric',timeZone:settings.timezone}).format(new Date()));return()=>window.removeEventListener('storage',sync)},[settings.timezone]);
 useEffect(()=>{if(!ready)return;const slug=pathname.startsWith('/app/')?pathname.split('/')[2]:null;if(slug)dispatch({type:'visit',slug});else if(pathname==='/home')dispatch({type:'enter'})},[pathname,ready,dispatch]);

 const home=homeDocument??installPhoneHome(createDefaultPage('home'));const inbox=home.nodes.find(n=>n.visible&&n.props.phonePart==='notifications');const shadeNotifications=(inbox?.children??[]).map(id=>home.nodes.find(n=>n.id===id)!).filter(n=>n?.visible).map(n=>({id:n.id,title:String(n.props.title??''),body:String(n.props.body??''),icon:String(n.props.icon??'♡'),href:n.props.pageSlug==='home'?'/home':getPublicApp(String(n.props.pageSlug))?'/app/'+n.props.pageSlug:'/home'}));
 const app=pathname.startsWith('/app/')?getPublicApp(pathname.split('/')[2]):null,unread=notifications.filter(n=>!state.readNotifications.includes(n.id)).length;
 return <DocumentSettingsProvider value={settings}><SettingsContext.Provider value={settings}><AudioDefaultsProvider value={{volume:settings.defaultVolume,muted:settings.defaultMuted}}><Context.Provider value={{state,ready,dispatch}}><div style={{"--phone-scale":phoneFit.scale,"--phone-fit-top":phoneFit.top+"px",background:settings.background,color:settings.text,"--w-accent":settings.accent,"--w-surface":settings.surface,"--w-text":settings.text,"--w-radius":settings.radius+"px"} as React.CSSProperties} className={"birthday-os"+(pathname==='/home'||pathname==='/app/hotline'||pathname==='/app/reasons'||(pathname==='/app/adventure'||pathname==='/app/movie')?' birthday-os-phone':'')} data-reduced-motion={state.reducedMotion?'true':undefined}><NotificationShade title={String(inbox?.props.title??'Notifications')} emptyMessage={String(inbox?.props.emptyMessage??'All caught up. ♡')} background={inbox?.props.background?String(inbox.props.background):undefined} notifications={shadeNotifications} app={pathname!=='/home'} reducedMotion={state.reducedMotion}><NotificationBridge open={open}/><a className="os-skip" href="#birthday-content">Skip to content</a>{pathname!=='/home'&&pathname!=='/app/hotline'&&pathname!=='/app/reasons'&&pathname!=='/app/adventure'&&pathname!=='/app/movie'&&<header className="os-topbar"><div className="os-topbar-inner"><Link href="/home" className="os-brand" aria-label={settings.siteTitle+" home"}><span aria-hidden="true">♡</span> {settings.siteTitle}</Link><div className="os-status"><span>{date}</span><button className="os-icon-button" aria-label={'Notifications'+(unread?', '+unread+' unread':'')} onClick={()=>setOpen(old=>!old)}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true" style={{margin:"auto"}}><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M9 20a3 3 0 0 0 6 0"/></svg>{unread>0&&<span className="os-badge">{unread}</span>}</button></div></div></header>}
 {app&&pathname!=='/app/hotline'&&pathname!=='/app/reasons'&&pathname!=='/app/adventure'&&pathname!=='/app/movie'&&<nav className="os-app-nav" aria-label="App navigation"><Link href="/home" className="os-back">← Home</Link><h1 style={{margin:0,fontSize:"inherit"}}>{app.icon} {app.title}</h1></nav>}
 <div id="birthday-content" tabIndex={-1}>{children}</div>
 {pathname!=='/home'&&pathname!=='/app/hotline'&&pathname!=='/app/reasons'&&pathname!=='/app/adventure'&&pathname!=='/app/movie'&&<footer className="os-footer"><span>A little world, just for you.</span><Link href="/">Welcome screen</Link></footer>}
 </NotificationShade></div></Context.Provider></AudioDefaultsProvider></SettingsContext.Provider></DocumentSettingsProvider>;
}
