'use client';
import { createContext, useCallback, useContext, useEffect, useRef, useState, type ReactNode } from 'react';
import { usePathname } from 'next/navigation';
import Link from 'next/link';
import { getPublicApp } from '@wiffeyyyy/content';
import { VISITOR_KEY, initialVisitorState, parseVisitorState, reduceVisitorState, type VisitorState, type VisitorAction } from '../lib/visitor-state';
const notifications=[{id:'welcome',title:'Your birthday home is ready',body:'Six little places to explore, all in one birthday world.',href:'/home'},{id:'hotline',title:'Start with the Birthday Hotline',body:'A little birthday message is waiting for you.',href:'/app/hotline'},{id:'explore',title:'Take your time',body:'You can come back to your favourite apps whenever you like.',href:'/home'}];
const Context=createContext<{state:VisitorState;ready:boolean;dispatch:(action:VisitorAction)=>void}>({state:initialVisitorState(),ready:false,dispatch:()=>{}});
export const useBirthdayOS=()=>useContext(Context);
export function OSProvider({children}:{children:ReactNode}){
 const [state,setState]=useState(initialVisitorState),[ready,setReady]=useState(false),[storageAvailable,setStorageAvailable]=useState(true),[open,setOpen]=useState(false),[date,setDate]=useState('Birthday edition');
 const pathname=usePathname(),dialog=useRef<HTMLDialogElement>(null),stateRef=useRef(state),readyRef=useRef(false);
 const dispatch=useCallback((action:VisitorAction)=>{if(!readyRef.current)return;const next=reduceVisitorState(stateRef.current,action);stateRef.current=next;setState(next);try{localStorage.setItem(VISITOR_KEY,JSON.stringify(next))}catch{setStorageAvailable(false)}},[]);
 useEffect(()=>{let restored=initialVisitorState();try{restored=parseVisitorState(localStorage.getItem(VISITOR_KEY))}catch{setStorageAvailable(false)}stateRef.current=restored;readyRef.current=true;setState(restored);setReady(true);const sync=(e:StorageEvent)=>{if(e.key===VISITOR_KEY){const next=parseVisitorState(e.newValue);stateRef.current=next;setState(next)}};window.addEventListener('storage',sync);setDate(new Intl.DateTimeFormat('en',{month:'short',day:'numeric',timeZone:'Asia/Kolkata'}).format(new Date()));return()=>window.removeEventListener('storage',sync)},[]);
 useEffect(()=>{if(!ready)return;const slug=pathname.startsWith('/app/')?pathname.split('/')[2]:null;if(slug)dispatch({type:'visit',slug});else if(pathname==='/home')dispatch({type:'enter'})},[pathname,ready,dispatch]);
 useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close()},[open]);
 const app=pathname.startsWith('/app/')?getPublicApp(pathname.split('/')[2]):null,unread=notifications.filter(n=>!state.readNotifications.includes(n.id)).length;
 return <Context.Provider value={{state,ready,dispatch}}><div className="birthday-os" data-reduced-motion={state.reducedMotion?'true':undefined}><a className="os-skip" href="#birthday-content">Skip to content</a><header className="os-topbar"><div className="os-topbar-inner"><Link href="/home" className="os-brand" aria-label="Wiffeyyyy OS home"><span aria-hidden="true">♡</span> Wiffeyyyy OS</Link><div className="os-status"><span>{date}</span><button className="os-icon-button" aria-label={'Notifications'+(unread?', '+unread+' unread':'')} onClick={()=>setOpen(true)}><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true" style={{margin:"auto"}}><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M9 20a3 3 0 0 0 6 0"/></svg>{unread>0&&<span className="os-badge">{unread}</span>}</button></div></div></header>
 {app&&<nav className="os-app-nav" aria-label="App navigation"><Link href="/home" className="os-back">← Home</Link><h1 style={{margin:0,fontSize:"inherit"}}>{app.icon} {app.title}</h1></nav>}
 <div id="birthday-content" tabIndex={-1}>{children}</div>
 <footer className="os-footer"><span>A little world, just for you.</span><Link href="/">Welcome screen</Link></footer>
 <dialog ref={dialog} className="os-dialog" onCancel={()=>setOpen(false)} onClose={()=>setOpen(false)} aria-labelledby="notifications-title"><header className="os-dialog-header"><div><p className="os-eyebrow">Birthday inbox</p><h2 id="notifications-title">Notifications</h2></div><button className="os-icon-button" aria-label="Close notifications" onClick={()=>setOpen(false)}>×</button></header><button className="os-text-button" onClick={()=>dispatch({type:'read',ids:notifications.map(n=>n.id)})}>Mark all as read</button><ul className="os-notifications">{notifications.map(n=><li key={n.id} data-unread={!state.readNotifications.includes(n.id)}><Link href={n.href} onClick={()=>{dispatch({type:'read',ids:[n.id]});setOpen(false)}}><strong>{n.title}</strong><p>{n.body}</p><span>{state.readNotifications.includes(n.id)?'Read':'Unread'} · Open →</span></Link></li>)}</ul><div className="os-preferences"><label><input type="checkbox" checked={state.reducedMotion} onChange={e=>dispatch({type:'motion',value:e.target.checked})}/> Reduce motion</label><p>{storageAvailable?'Your visits and preferences are saved on this browser.':'Browser storage is unavailable. Your preferences will last for this visit.'}</p><button className="os-text-button" onClick={()=>dispatch({type:'reset'})}>Reset this browser’s progress</button></div></dialog></div></Context.Provider>;
}
