'use client';
import {useCallback,useEffect,useRef,useState,type MouseEvent as ReactMouseEvent,type PointerEvent as ReactPointerEvent,type ReactNode} from 'react';

type Origin={x:number;y:number;width:number;height:number;radius:number;color:string;label:string;artwork?:string};
type Motion={id:number;kind:'opening'|'closing';origin:Origin;target:string;started:number};
const STORAGE='wiffeyyyy:last-app-origin';
const OPEN_MS=410,CLOSE_MS=360,REVEAL_MS=165;
const IOS_EASE='cubic-bezier(.32,.72,0,1)';
const SETTLE_EASE='cubic-bezier(.22,.78,.16,1)';
const FALLBACK:Origin={x:165,y:720,width:60,height:60,radius:18,color:'#e8d9e8',label:'Home',artwork:''};
const surfaceFor=(path:string)=>path.includes('/reasons')?'#f4eee7':path.includes('/hotline')?'#101014':path.includes('/adventure')?'#f5f5f7':path.includes('/movie')?'#050505':path.includes('/camera')?'#050505':path.includes('/vault')?'#17131c':path.includes('/kiss-shop')?'#fff7f5':path.includes('/pieces')?'#f6efe9':'#f8f6f8';
const validOrigin=(value:unknown):value is Origin=>{if(!value||typeof value!=='object')return false;const v=value as Partial<Origin>;return ['x','y','width','height','radius'].every(key=>Number.isFinite(v[key as keyof Origin]))&&typeof v.color==='string'&&typeof v.label==='string'};

export function PhoneAppTransition({pathname,reducedMotion=false,children}:{pathname:string;reducedMotion?:boolean;children:ReactNode}){
 const host=useRef<HTMLDivElement>(null),content=useRef<HTMLDivElement>(null),layer=useRef<HTMLDivElement>(null),artwork=useRef<HTMLDivElement>(null),backdrop=useRef<HTMLDivElement>(null),lastOrigin=useRef<Origin|null>(null),active=useRef(false),previousPath=useRef(pathname),counter=useRef(0);
 const [motion,setMotion]=useState<Motion|null>(null),[revealing,setRevealing]=useState(false);
 useEffect(()=>{try{const parsed=JSON.parse(sessionStorage.getItem(STORAGE)??'null');if(validOrigin(parsed))lastOrigin.current=parsed}catch{}},[]);
 const remember=useCallback((origin:Origin)=>{lastOrigin.current=origin;try{sessionStorage.setItem(STORAGE,JSON.stringify(origin))}catch{}},[]);
 const measure=useCallback((anchor:HTMLAnchorElement):Origin=>{const root=host.current,icon=anchor.querySelector<HTMLElement>('.phone-icon')??anchor;if(!root)return FALLBACK;const rootRect=root.getBoundingClientRect(),rect=icon.getBoundingClientRect(),scale=Math.max(.01,rootRect.width/Math.max(1,root.offsetWidth));const style=getComputedStyle(icon),radius=parseFloat(style.borderTopLeftRadius)||18,label=(anchor.getAttribute('aria-label')??anchor.textContent??'App').replace(/^Open\s+/i,'').trim()||'App';return{x:(rect.left-rootRect.left)/scale,y:(rect.top-rootRect.top)/scale,width:rect.width/scale,height:rect.height/scale,radius,color:style.backgroundColor||'#e8d9e8',label,artwork:icon.innerHTML}},[]);
 const resolveLink=useCallback((target:EventTarget|null)=>{const anchor=(target as HTMLElement|null)?.closest?.<HTMLAnchorElement>('a[href]');if(!anchor||anchor.target||anchor.hasAttribute('download'))return null;const url=new URL(anchor.href,window.location.href);if(url.origin!==window.location.origin)return null;return{anchor,path:url.pathname}},[]);
 const begin=useCallback((target:EventTarget|null)=>{if(reducedMotion||active.current)return;const item=resolveLink(target);if(!item)return;let kind:'opening'|'closing'|null=null,origin:Origin|null=null;if(pathname==='/home'&&item.path.startsWith('/app/')){kind='opening';origin=measure(item.anchor);remember(origin)}else if(pathname.startsWith('/app/')&&item.path==='/home'){kind='closing';origin=lastOrigin.current??FALLBACK}if(!kind||!origin)return;active.current=true;setRevealing(false);setMotion({id:++counter.current,kind,origin,target:item.path,started:performance.now()})},[measure,pathname,reducedMotion,remember,resolveLink]);
 const pointer=useCallback((event:ReactPointerEvent<HTMLDivElement>)=>{if(event.button===0)begin(event.target)},[begin]);
 const click=useCallback((event:ReactMouseEvent<HTMLDivElement>)=>{if(event.button===0)begin(event.target)},[begin]);
 useEffect(()=>{const current=motion;if(!current||reducedMotion)return;const el=layer.current,iconArt=artwork.current,shade=backdrop.current,box=host.current,base=content.current;if(!el||!shade||!box||!base)return;const width=Math.max(1,box.offsetWidth),height=Math.max(1,box.offsetHeight),sx=current.origin.width/width,sy=current.origin.height/height;
  const morph=(progress:number)=>`translate3d(${current.origin.x*(1-progress)}px,${current.origin.y*(1-progress)}px,0) scale(${sx+(1-sx)*progress},${sy+(1-sy)*progress})`;
  const from=morph(0),near=morph(.94),pressed=`translate3d(${current.origin.x+current.origin.width*.035}px,${current.origin.y+current.origin.height*.035}px,0) scale(${sx*.93},${sy*.93})`,full='translate3d(0,0,0) scale(1,1)',surface=surfaceFor(current.target),duration=current.kind==='opening'?OPEN_MS:CLOSE_MS;el.style.background=surface;
  const keyframes=current.kind==='opening'?
   [{offset:0,transform:from,borderRadius:current.origin.radius+'px',background:current.origin.color,easing:'ease-out'},{offset:.11,transform:pressed,borderRadius:Math.max(8,current.origin.radius*.96)+'px',background:current.origin.color,easing:IOS_EASE},{offset:.76,transform:near,borderRadius:'9px',background:surface,easing:SETTLE_EASE},{offset:1,transform:full,borderRadius:'0px',background:surface}]:
   [{offset:0,transform:full,borderRadius:'0px',background:surface,easing:'ease-out'},{offset:.28,transform:near,borderRadius:'8px',background:surface,easing:IOS_EASE},{offset:.88,transform:morph(.05),borderRadius:Math.max(8,current.origin.radius*.94)+'px',background:current.origin.color,easing:SETTLE_EASE},{offset:1,transform:from,borderRadius:current.origin.radius+'px',background:current.origin.color}];
  const animation=el.animate(keyframes,{duration,easing:'linear',fill:'forwards'});
  const shadeAnimation=shade.animate(current.kind==='opening'?[{opacity:0},{offset:.2,opacity:.018},{opacity:.052}]:[{opacity:.052},{offset:.75,opacity:.018},{opacity:0}],{duration,easing:IOS_EASE,fill:'forwards'});
  const baseAnimation=base.animate(current.kind==='opening'?[{offset:0,transform:'scale(1)',opacity:1},{offset:.18,transform:'scale(.994)',opacity:.985},{offset:1,transform:'scale(.974)',opacity:.945}]:[{offset:0,transform:'scale(.974)',opacity:.945},{offset:.72,transform:'scale(.994)',opacity:.985},{offset:1,transform:'scale(1)',opacity:1}],{duration,easing:IOS_EASE,fill:'forwards'});
  const artAnimation=iconArt?.animate(current.kind==='opening'?[{offset:0,opacity:1,transform:'scale(1)'},{offset:.11,opacity:1,transform:'scale(.93)'},{offset:.24,opacity:1,transform:'scale(1)'},{offset:.46,opacity:.28,transform:'scale(1.045)'},{offset:.58,opacity:0,transform:'scale(1.07)'},{offset:1,opacity:0,transform:'scale(1.07)'}]:[{offset:0,opacity:0,transform:'scale(1.07)'},{offset:.62,opacity:0,transform:'scale(1.05)'},{offset:.78,opacity:.35,transform:'scale(1.025)'},{offset:.9,opacity:.9,transform:'scale(.97)'},{offset:1,opacity:1,transform:'scale(1)'}],{duration,easing:IOS_EASE,fill:'forwards'});
  return()=>{animation.cancel();shadeAnimation.cancel();baseAnimation.cancel();artAnimation?.cancel()}
 },[motion?.id,reducedMotion]);
 useEffect(()=>{const prev=previousPath.current;previousPath.current=pathname;if(!motion&&prev.startsWith('/app/')&&pathname==='/home'&&!reducedMotion&&lastOrigin.current){active.current=true;setMotion({id:++counter.current,kind:'closing',origin:lastOrigin.current,target:'/home',started:performance.now()});return}if(!motion)return;const arrived=pathname===motion.target;if(!arrived)return;const duration=motion.kind==='opening'?OPEN_MS:CLOSE_MS,remaining=Math.max(0,duration-(performance.now()-motion.started));const timer=window.setTimeout(()=>setRevealing(true),remaining);return()=>window.clearTimeout(timer)},[pathname,motion?.id,reducedMotion]);
 useEffect(()=>{if(!revealing||!motion)return;const el=layer.current,shade=backdrop.current,base=content.current;if(!el||!shade){active.current=false;setMotion(null);setRevealing(false);return}const fade=el.animate([{opacity:1},{offset:.72,opacity:.24},{opacity:0}],{duration:REVEAL_MS,easing:SETTLE_EASE,fill:'forwards'}),shadeFade=shade.animate([{opacity:Number(getComputedStyle(shade).opacity)||.052},{opacity:0}],{duration:REVEAL_MS,easing:SETTLE_EASE,fill:'forwards'}),baseSettle=base?.animate([{transform:getComputedStyle(base).transform==='none'?'scale(.985)':getComputedStyle(base).transform,opacity:Number(getComputedStyle(base).opacity)||.96},{offset:.72,transform:'scale(1.003)',opacity:1},{transform:'scale(1)',opacity:1}],{duration:REVEAL_MS,easing:SETTLE_EASE,fill:'forwards'});const done=()=>{active.current=false;setMotion(null);setRevealing(false)};Promise.allSettled([fade.finished,shadeFade.finished,baseSettle?.finished??Promise.resolve()]).then(done);return()=>{fade.cancel();shadeFade.cancel();baseSettle?.cancel()}},[revealing,motion?.id]);
 useEffect(()=>{if(!motion)return;const watchdog=window.setTimeout(()=>{active.current=false;setMotion(null);setRevealing(false)},6000);return()=>window.clearTimeout(watchdog)},[motion?.id]);
 return <div ref={host} className="phone-route-stage" onPointerDownCapture={pointer} onClickCapture={click}><div ref={content} className="phone-route-content">{children}</div>{motion&&<div className="phone-app-transition" data-motion={motion.kind} aria-hidden="true"><div ref={backdrop} className="phone-app-transition-backdrop"/><div ref={layer} className="phone-app-transition-surface"><div ref={artwork} className="phone-app-transition-artwork" dangerouslySetInnerHTML={{__html:motion.origin.artwork??''}}/></div></div>}</div>;
}
