"use server";
import { revalidatePath } from 'next/cache';
import { adminDb } from './supabase';
import { requireAdmin } from './auth';
export async function saveDraft(pageId:string,document:unknown){await requireAdmin('site:write');const db=await adminDb();const {error}=await db.from('pages').update({draft_document:document,updated_at:new Date().toISOString()}).eq('id',pageId);if(error)throw new Error(error.message);return{ok:true};}
export async function publishPage(pageId:string){const actor=await requireAdmin('site:publish');const db=await adminDb();const {data:page,error}=await db.from('pages').select('slug,draft_document').eq('id',pageId).single();if(error)throw new Error(error.message);const {data:last}=await db.from('page_versions').select('version_number').eq('page_id',pageId).order('version_number',{ascending:false}).limit(1).maybeSingle();const version=(last?.version_number??0)+1;const {data:v,error:ve}=await db.from('page_versions').insert({page_id:pageId,version_number:version,status:'published',created_by:actor.id,document:page.draft_document}).select('id').single();if(ve)throw new Error(ve.message);const {error:pe}=await db.from('pages').update({published_version_id:v.id,updated_at:new Date().toISOString()}).eq('id',pageId);if(pe)throw new Error(pe.message);revalidatePath('/');revalidatePath('/preview/'+page.slug);return{ok:true,version};}
export async function rollbackPage(pageId:string,versionId:string){await requireAdmin('site:publish');const db=await adminDb();const {error}=await db.from('pages').update({published_version_id:versionId,updated_at:new Date().toISOString()}).eq('id',pageId);if(error)throw new Error(error.message);return{ok:true};}
export async function saveSiteSettings(siteId:string,settings:Record<string,unknown>){await requireAdmin('site:settings');const db=await adminDb();const {error}=await db.from('site_settings').upsert({...settings,site_id:siteId,updated_at:new Date().toISOString()},{onConflict:'site_id'});if(error)throw new Error(error.message);return{ok:true};}
export async function saveAppItem(input:{siteId:string;appSlug:string;itemType:string;position:number;title?:string;body?:string;metadata?:Record<string,unknown>;enabled?:boolean}){await requireAdmin('site:write');const db=await adminDb();const row={site_id:input.siteId,app_slug:input.appSlug,item_type:input.itemType,position:input.position,title:input.title,body:input.body,metadata:input.metadata,enabled:input.enabled};const {error}=await db.from('app_content_items').upsert(row,{onConflict:'site_id,app_slug,item_type,position'});if(error)throw new Error(error.message);return{ok:true};}
